services:
  postgres:
    image: postgres:17
    container_name: panossoerp-postgres
    restart: always
    environment:
      POSTGRES_USER: panossoerp
      POSTGRES_PASSWORD: panossoerp_10203040
      POSTGRES_DB: panossoerpdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: