package planning_uc

import (
	"context"
	"fmt"

	"github.com/FelipePn10/panossoerp/internal/application/dto/request"
	"github.com/FelipePn10/panossoerp/internal/application/dto/response"
	"github.com/FelipePn10/panossoerp/internal/application/usecase/aps_uc"
	"github.com/FelipePn10/panossoerp/internal/application/usecase/crp_uc"
	"github.com/FelipePn10/panossoerp/internal/application/usecase/mrp_calculation_uc"
)

// RunPlanningPipelineUseCase chains the three planning engines that today are
// triggered separately: it runs MRP (explosion + planned orders), then CRP
// (capacity load) and APS (finite-capacity sequencing) over the same plan,
// returning a single viability verdict.
type RunPlanningPipelineUseCase struct {
	MRP *mrp_calculation_uc.RunMRPCalculationUseCase
	CRP *crp_uc.CRPUseCase
	APS *aps_uc.APSUseCase
}

func (uc *RunPlanningPipelineUseCase) Execute(ctx context.Context, dto request.RunPlanningPipelineDTO) (*response.PlanningPipelineResponse, error) {
	out := &response.PlanningPipelineResponse{PlanCode: dto.PlanCode, Viable: true}

	// 1) MRP — auth is enforced inside the MRP use case.
	mrpLog, err := uc.MRP.Execute(ctx, request.RunMRPCalculationDTO{
		PlanCode:    dto.PlanCode,
		GenerateLLC: dto.GenerateLLC,
	})
	if err != nil {
		return nil, fmt.Errorf("MRP step: %w", err)
	}
	out.MRPItems = mrpLog.TotalItems
	out.MRPOrders = mrpLog.TotalOrders
	out.MRPStatus = mrpLog.Status
	if mrpLog.Status != "" && mrpLog.Status != "SUCCESS" && mrpLog.Status != "COMPLETED" {
		out.Viable = false
		out.Notes = append(out.Notes, fmt.Sprintf("MRP terminou com status %q", mrpLog.Status))
	}

	// 2) CRP — load the planned orders generated by MRP against capacity.
	crpSummary, err := uc.CRP.CalculateCRP(ctx, request.CalculateCRPDTO{PlanCode: dto.PlanCode})
	if err != nil {
		return nil, fmt.Errorf("CRP step: %w", err)
	}
	out.CRPEntries = crpSummary.TotalEntries
	out.CRPOverload = crpSummary.OverloadCount
	if crpSummary.OverloadCount > 0 {
		out.Viable = false
		out.Notes = append(out.Notes, fmt.Sprintf("%d centro(s)/dia em sobrecarga de capacidade (CRP)", crpSummary.OverloadCount))
	}

	// 3) APS — sequence the open production orders in finite capacity.
	apsSummary, err := uc.APS.SequenceOrders(ctx, request.SequenceOrdersDTO{StartFrom: dto.StartFrom})
	if err != nil {
		return nil, fmt.Errorf("APS step: %w", err)
	}
	out.APSOrders = apsSummary.OrdersProcessed
	out.APSOperations = apsSummary.ScheduledOperations

	if out.Viable {
		out.Notes = append(out.Notes, "Plano viável: sem sobrecarga de capacidade detectada.")
	}
	return out, nil
}
