BEGIN;

ALTER TABLE public.fiscal_exit_items
    ADD COLUMN IF NOT EXISTS aliq_pis    NUMERIC(7,4) NOT NULL DEFAULT 0.0165,
    ADD COLUMN IF NOT EXISTS aliq_cofins NUMERIC(7,4) NOT NULL DEFAULT 0.0760;

COMMIT;
