DROP INDEX IF EXISTS idx_mrp_exceptions_tenant;
DROP INDEX IF EXISTS idx_stock_balances_tenant;
DROP INDEX IF EXISTS idx_sales_divisions_tenant;
DROP INDEX IF EXISTS idx_machine_schedules_tenant;
DROP INDEX IF EXISTS idx_item_planning_extras_tenant;
DROP INDEX IF EXISTS idx_mps_schedule_tenant;
DROP INDEX IF EXISTS idx_kanban_cards_tenant;
DROP INDEX IF EXISTS idx_item_machine_times_tenant;
DROP INDEX IF EXISTS idx_order_priorities_tenant;
DROP INDEX IF EXISTS idx_planning_params_tenant;
DROP INDEX IF EXISTS idx_mrp_suggestions_tenant;
DROP INDEX IF EXISTS idx_configured_rules_tenant;
DROP INDEX IF EXISTS idx_sales_order_demands_tenant;
DROP INDEX IF EXISTS idx_stock_snapshots_tenant;
DROP INDEX IF EXISTS idx_mrp_logs_tenant;
DROP INDEX IF EXISTS idx_mrp_profiles_tenant;
DROP INDEX IF EXISTS idx_planned_orders_tenant;
DROP INDEX IF EXISTS idx_independent_demands_tenant;
ALTER TABLE mrp_exception_messages DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE mrp_planned_suggestions DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE configured_item_rules DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE sales_order_demands DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE stock_snapshots DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE mrp_calculation_logs DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE mrp_item_profiles DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE planned_orders DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE independent_demands DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE production_plans DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE stock_balances DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE sales_divisions DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE machine_schedules DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE item_planning_extras DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE mps_schedule DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE kanban_cards DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE item_machine_times DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE order_priorities DROP COLUMN IF EXISTS enterprise_id;
ALTER TABLE planning_params DROP COLUMN IF EXISTS enterprise_id;
DROP TABLE IF EXISTS user_enterprises;
