-- 000285-000295 are intentionally reserved by the cutting-plan work in develop.
ALTER TABLE items
    ADD COLUMN IF NOT EXISTS commercial_description VARCHAR(255),
    ADD COLUMN IF NOT EXISTS commercial_sale_type VARCHAR(10),
    ADD COLUMN IF NOT EXISTS commercial_volume_conversion_factor NUMERIC(18,6),
    ADD COLUMN IF NOT EXISTS commercial_sale_multiple NUMERIC(18,6),
    ADD COLUMN IF NOT EXISTS commercial_minimum_sale_quantity NUMERIC(18,6),
    ADD COLUMN IF NOT EXISTS commercial_estimated_delivery_days INTEGER,
    ADD COLUMN IF NOT EXISTS commercial_transfer_warehouse_code VARCHAR(100),
    ADD COLUMN IF NOT EXISTS commercial_technical_assistance_warehouse_code VARCHAR(100),
    ADD COLUMN IF NOT EXISTS commercial_packaging_item_code BIGINT,
    ADD COLUMN IF NOT EXISTS commercial_allow_billing_description_change BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_issue_loading_labels BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_assemble_shipping_volumes BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_requires_special_packaging BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_withhold_pis_cofins BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_is_packaging BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_mobile_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_export_packaging BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS commercial_classification_code VARCHAR(40),
    ADD COLUMN IF NOT EXISTS commercial_notes VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS accounting_sale_fiscal_classification_code VARCHAR(40),
    ADD COLUMN IF NOT EXISTS accounting_purchase_fiscal_classification_code VARCHAR(40),
    ADD COLUMN IF NOT EXISTS accounting_origin SMALLINT,
    ADD COLUMN IF NOT EXISTS accounting_sale_ipi_type VARCHAR(12),
    ADD COLUMN IF NOT EXISTS accounting_sale_ipi_rate NUMERIC(18,6),
    ADD COLUMN IF NOT EXISTS accounting_purchase_ipi_type VARCHAR(12),
    ADD COLUMN IF NOT EXISTS accounting_purchase_ipi_rate NUMERIC(18,6),
    ADD COLUMN IF NOT EXISTS accounting_icms_rate NUMERIC(18,6),
    ADD COLUMN IF NOT EXISTS accounting_sale_unit_of_measurement VARCHAR(20),
    ADD COLUMN IF NOT EXISTS accounting_purchase_unit_of_measurement VARCHAR(20),
    ADD COLUMN IF NOT EXISTS accounting_inventory_group_code BIGINT,
    ADD COLUMN IF NOT EXISTS accounting_classification_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS accounting_cest CHAR(7),
    ADD COLUMN IF NOT EXISTS accounting_input_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS accounting_notes VARCHAR(1000);

ALTER TABLE items
    ADD CONSTRAINT chk_items_commercial_sale_type CHECK (commercial_sale_type IS NULL OR commercial_sale_type IN ('VENDA','REVENDA')),
    ADD CONSTRAINT chk_items_commercial_positive CHECK ((commercial_volume_conversion_factor IS NULL OR commercial_volume_conversion_factor > 0) AND (commercial_sale_multiple IS NULL OR commercial_sale_multiple > 0) AND (commercial_minimum_sale_quantity IS NULL OR commercial_minimum_sale_quantity >= 0) AND (commercial_estimated_delivery_days IS NULL OR commercial_estimated_delivery_days >= 0)),
    ADD CONSTRAINT chk_items_accounting_origin CHECK (accounting_origin IS NULL OR accounting_origin BETWEEN 0 AND 8),
    ADD CONSTRAINT chk_items_accounting_ipi_types CHECK ((accounting_sale_ipi_type IS NULL OR accounting_sale_ipi_type IN ('PERCENTUAL','VALOR')) AND (accounting_purchase_ipi_type IS NULL OR accounting_purchase_ipi_type IN ('PERCENTUAL','VALOR'))),
    ADD CONSTRAINT chk_items_accounting_rates CHECK ((accounting_sale_ipi_rate IS NULL OR accounting_sale_ipi_rate >= 0) AND (accounting_purchase_ipi_rate IS NULL OR accounting_purchase_ipi_rate >= 0) AND (accounting_icms_rate IS NULL OR accounting_icms_rate >= 0)),
    ADD CONSTRAINT chk_items_accounting_cest CHECK (accounting_cest IS NULL OR accounting_cest ~ '^[0-9]{7}$'),
    ADD CONSTRAINT chk_items_packaging_not_self CHECK (commercial_packaging_item_code IS NULL OR commercial_packaging_item_code <> code),
    ADD CONSTRAINT fk_items_commercial_transfer_warehouse FOREIGN KEY (commercial_transfer_warehouse_code) REFERENCES warehouse(code),
    ADD CONSTRAINT fk_items_commercial_assistance_warehouse FOREIGN KEY (commercial_technical_assistance_warehouse_code) REFERENCES warehouse(code),
    ADD CONSTRAINT fk_items_commercial_packaging_item FOREIGN KEY (commercial_packaging_item_code) REFERENCES items(code),
    ADD CONSTRAINT fk_items_accounting_inventory_group FOREIGN KEY (accounting_inventory_group_code) REFERENCES groups(code);
