DROP INDEX IF EXISTS idx_cfg_sets_enterprise;
ALTER TABLE cfg_sets DROP CONSTRAINT IF EXISTS fk_cfg_sets_enterprise;
ALTER TABLE cfg_sets DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_variables_enterprise;
ALTER TABLE cfg_variables DROP CONSTRAINT IF EXISTS fk_cfg_variables_enterprise;
ALTER TABLE cfg_variables DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_variable_languages_enterprise;
ALTER TABLE cfg_variable_languages DROP CONSTRAINT IF EXISTS fk_cfg_variable_languages_enterprise;
ALTER TABLE cfg_variable_languages DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_characteristics_enterprise;
ALTER TABLE cfg_characteristics DROP CONSTRAINT IF EXISTS fk_cfg_characteristics_enterprise;
ALTER TABLE cfg_characteristics DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_characteristic_languages_enterprise;
ALTER TABLE cfg_characteristic_languages DROP CONSTRAINT IF EXISTS fk_cfg_characteristic_languages_enterprise;
ALTER TABLE cfg_characteristic_languages DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_characteristic_receiving_items_enterprise;
ALTER TABLE cfg_characteristic_receiving_items DROP CONSTRAINT IF EXISTS fk_cfg_characteristic_receiving_items_enterprise;
ALTER TABLE cfg_characteristic_receiving_items DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_item_characteristics_enterprise;
ALTER TABLE cfg_item_characteristics DROP CONSTRAINT IF EXISTS fk_cfg_item_characteristics_enterprise;
ALTER TABLE cfg_item_characteristics DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_item_char_default_answers_enterprise;
ALTER TABLE cfg_item_char_default_answers DROP CONSTRAINT IF EXISTS fk_cfg_item_char_default_answers_enterprise;
ALTER TABLE cfg_item_char_default_answers DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_item_mask_answers_enterprise;
ALTER TABLE cfg_item_mask_answers DROP CONSTRAINT IF EXISTS fk_cfg_item_mask_answers_enterprise;
ALTER TABLE cfg_item_mask_answers DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_description_types_enterprise;
ALTER TABLE cfg_description_types DROP CONSTRAINT IF EXISTS fk_cfg_description_types_enterprise;
ALTER TABLE cfg_description_types DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_item_descriptions_enterprise;
ALTER TABLE cfg_item_descriptions DROP CONSTRAINT IF EXISTS fk_cfg_item_descriptions_enterprise;
ALTER TABLE cfg_item_descriptions DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_item_description_lines_enterprise;
ALTER TABLE cfg_item_description_lines DROP CONSTRAINT IF EXISTS fk_cfg_item_description_lines_enterprise;
ALTER TABLE cfg_item_description_lines DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_item_rules_enterprise;
ALTER TABLE cfg_item_rules DROP CONSTRAINT IF EXISTS fk_cfg_item_rules_enterprise;
ALTER TABLE cfg_item_rules DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_item_rule_conditions_enterprise;
ALTER TABLE cfg_item_rule_conditions DROP CONSTRAINT IF EXISTS fk_cfg_item_rule_conditions_enterprise;
ALTER TABLE cfg_item_rule_conditions DROP COLUMN IF EXISTS enterprise_id;
DROP INDEX IF EXISTS idx_cfg_equivalent_rules_enterprise;
ALTER TABLE cfg_equivalent_rules DROP CONSTRAINT IF EXISTS fk_cfg_equivalent_rules_enterprise;
ALTER TABLE cfg_equivalent_rules DROP COLUMN IF EXISTS enterprise_id;
