DROP TRIGGER IF EXISTS trg_notification_characteristic_active ON cfg_characteristics;
DROP TRIGGER IF EXISTS trg_notification_item_characteristic ON cfg_item_characteristics;
DROP TRIGGER IF EXISTS trg_notification_item_configured ON items;
DROP FUNCTION IF EXISTS notification_characteristic_active_trigger();
DROP FUNCTION IF EXISTS notification_item_characteristic_trigger();
DROP FUNCTION IF EXISTS notification_item_configured_trigger();
DROP FUNCTION IF EXISTS notification_sync_configured_item(BIGINT);
DROP TABLE IF EXISTS stock_cycle_count_audit;
DROP TABLE IF EXISTS stock_cycle_counts;
DROP TABLE IF EXISTS notification_dead_letters;
DROP TABLE IF EXISTS notification_provider_circuit;
DROP TABLE IF EXISTS notification_provider_rate_windows;
DROP TABLE IF EXISTS notification_delivery_attachments;
DROP TABLE IF EXISTS notification_delivery_attempts;
DROP TABLE IF EXISTS notification_deliveries;
DROP TABLE IF EXISTS notification_digest_items;
DROP TABLE IF EXISTS notification_digest_runs;
DROP TABLE IF EXISTS notification_alerts;
DROP TABLE IF EXISTS notification_outbox;
DROP TABLE IF EXISTS enterprise_notification_recipients;
DROP TABLE IF EXISTS enterprise_notification_subscriptions;
DROP TABLE IF EXISTS enterprise_notification_settings;
DROP TABLE IF EXISTS enterprise_department_users;
DROP TABLE IF EXISTS enterprise_departments;
DROP TABLE IF EXISTS notification_event_catalog;
ALTER TABLE users DROP COLUMN IF EXISTS is_active;
