BEGIN;

ALTER TABLE notification_event_catalog
    ADD COLUMN producer_status VARCHAR(12) NOT NULL DEFAULT 'FUTURO',
    ADD COLUMN producer_description TEXT NOT NULL DEFAULT 'Produtor ainda não conectado ao processo operacional.';

ALTER TABLE notification_event_catalog
    ADD CONSTRAINT notification_event_catalog_producer_status_check
    CHECK (producer_status IN ('ATIVO','FUTURO'));

UPDATE notification_event_catalog
SET producer_status='ATIVO',
    producer_description='Produtor conectado e monitorado pelo backend.'
WHERE event_key IN (
    'COMERCIAL_ORCAMENTO_CONVERTIDO_PEDIDO',
    'CADASTRO_ITEM_CONFIGURADO_SEM_PERGUNTAS',
    'MRP_EXCECAO',
    'FISCAL_NFE_SAIDA_CRIADA','FISCAL_NFE_SAIDA_AGUARDANDO_AUTORIZACAO',
    'FISCAL_NFE_SAIDA_AUTORIZADA','FISCAL_NFE_SAIDA_REJEITADA','FISCAL_NFE_SAIDA_CANCELADA',
    'FISCAL_NFE_ENTRADA_IMPORTADA','FISCAL_NFE_ENTRADA_APROVADA',
    'FISCAL_NFE_ENTRADA_ITEM_NAO_IDENTIFICADO','FISCAL_NFE_ENTRADA_DIVERGENCIA_FISCAL',
    'FISCAL_NFE_ENTRADA_DIVERGENCIA_QUANTIDADE','FISCAL_NFE_ENTRADA_CANCELADA',
    'ESTOQUE_CONTAGEM_PROXIMA_VENCIMENTO','ESTOQUE_CONTAGEM_VENCIDA',
    'ESTOQUE_CONTAGEM_DIVERGENCIA','ESTOQUE_CONTAGEM_CONCLUIDA','ESTOQUE_CONTAGEM_APROVADA',
    'ESTOQUE_ABAIXO_MINIMO','ESTOQUE_NEGATIVO','ESTOQUE_LOTE_PROXIMO_VENCIMENTO',
    'ESTOQUE_MOVIMENTACAO_INCOMUM'
);

COMMIT;
