package entity

import (
	"time"

	"github.com/google/uuid"
)

type MRPItemProfile struct {
	ItemCode        int64
	PlanCode        int64
	CalculationDate time.Time
	Demand          float64
	OrdersPlanned   float64
	OrdersFirm      float64
	StockProjected  float64
	LLC             int
	NeedDate        time.Time
	CreatedAt       time.Time
}

type MRPCalculationLog struct {
	Code        int64
	PlanCode    int64
	StartedAt   time.Time
	FinishedAt  *time.Time
	Status      string
	Errors      map[string]interface{}
	TotalItems  int
	TotalOrders int
	CreatedAt   time.Time
}

type StockSnapshot struct {
	ItemCode      int64
	WarehouseCode int64
	Quantity      float64
	ReservedQty   float64
	SafetyStock   float64
	SnapshotDate  time.Time
	CreatedAt     time.Time
}

type SalesOrderDemand struct {
	Code           int64
	SalesOrderCode int64
	ItemCode       int64
	Mask           *string
	Quantity       float64
	DeliveredQty   float64
	DeliveryDate   time.Time
	DivisionCode   *int64
	Status         string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ConfiguredItemRule struct {
	Code      int64
	ItemCode  int64
	TableType string
	FieldName string
	RuleType  string
	RuleValue string
	Sequence  int
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.UUID
}

// MRPInput holds all inputs for MRP calculation
type MRPInput struct {
	PlanCode       int64
	ItemCode       int64
	Mask           string
	Quantity       float64
	NeedDate       time.Time
	SalesOrderCode *int64
	ParentItemCode *int64
	LLC            int
}

// MRPOutput holds the result of MRP calculation for one item
type MRPOutput struct {
	ItemCode       int64
	LLC            int
	Demand         float64
	StockProjected float64
	NetRequirement float64
	PlannedOrders  []*PlannedOrderSuggestion
}

type PlannedOrderSuggestion struct {
	Code           int64
	PlanCode       int64
	ItemCode       int64
	Quantity       float64
	NeedDate       time.Time
	StartDate      *time.Time
	OrderType      string
	DemandType     string
	ParentItemCode *int64
	LLC            int
	MachineID      *int64
	ProductionTime *float64
	Priority       *string
	Notes          *string
}

// ExceptionMessageType classifies an MRP exception so planners can act
// on it without reading the description text.
type ExceptionMessageType string

const (
	// ExceptionRescheduleIn — an existing firm order arrives after the demand
	// need date. The planner must expedite or reschedule it earlier.
	ExceptionRescheduleIn ExceptionMessageType = "RESCHEDULE_IN"

	// ExceptionRescheduleOut — an existing firm order arrives well before the
	// demand need date (>30 days). Delaying it would free up cash and storage.
	ExceptionRescheduleOut ExceptionMessageType = "RESCHEDULE_OUT"

	// ExceptionCancel — an existing firm order has no covering demand in this
	// MRP run. Cancelling it avoids unnecessary production or purchase.
	ExceptionCancel ExceptionMessageType = "CANCEL"

	// ExceptionExpedite — demand is urgent and an existing order must be
	// accelerated beyond its normal lead time.
	ExceptionExpedite ExceptionMessageType = "EXPEDITE"

	// ExceptionExcess — total firm supply significantly exceeds the net
	// requirement. Projected excess stock after all demands are satisfied.
	ExceptionExcess ExceptionMessageType = "EXCESS_PROJECTED"
)

// MRPExceptionMessage is generated by the MRP engine when it detects that an
// existing firm order is misaligned with current demand. Each message is
// actionable — the planner knows exactly what to do without needing to run
// a manual analysis.
type MRPExceptionMessage struct {
	Code        int64
	PlanCode    int64
	ItemCode    int64
	MessageType ExceptionMessageType
	SourceCode  *int64  // PK of the planned_order that triggered this (nil = demand-driven)
	SourceType  *string // e.g. "PLANNED_ORDER", "PURCHASE_ORDER"
	Description string  // human-readable explanation in Brazilian Portuguese
	CreatedAt   time.Time
}

// ---------- New entity types for enhanced MRP features ----------

// MachineTimeInfo holds the relationship between an item, a machine, and its
// unit production time. Used for machine scheduling during MRP.
type MachineTimeInfo struct {
	ItemCode       int64
	MachineID      int64
	Priority       int // lower = higher importance
	ProductionTime float64
}

// KanbanCardInfo represents an active kanban card tied to an item.
type KanbanCardInfo struct {
	CardCode        int64
	ItemCode        int64
	ReorderPoint    float64
	QuantityPerCard float64
	CardCount       int
	IsActive        bool
}

// MPSItemInfo is a single entry from the Master Production Schedule.
type MPSItemInfo struct {
	ItemCode    int64
	Mask        string
	PeriodType  string
	PeriodValue int
	Year        int
	Quantity    float64
	IsFirm      bool
}

// ItemPlanningExtra holds extra planning parameters per item that are not
// part of the main item record (e.g. maximum stock level for MIN_MAX).
type ItemPlanningExtra struct {
	ItemCode     int64
	MaximumStock float64
	SafetyTime   int
	Coverage     int
	GroupingKey  *string
	IsCritical   bool
	UseTankDate  bool
}

// MachineScheduleInfo is a machine allocation record generated by MRP
// for FABRICACAO-type planned orders.
type MachineScheduleInfo struct {
	PlanCode         int64
	PlannedOrderCode int64
	MachineID        int64
	ScheduleDate     time.Time
	ProductionTime   float64
}
