package production_order_uc

import (
	"context"
	"fmt"

	"github.com/FelipePn10/panossoerp/internal/application/dto/request"
	"github.com/FelipePn10/panossoerp/internal/application/ports"
	errorsuc "github.com/FelipePn10/panossoerp/internal/application/usecase/errors"
	"github.com/FelipePn10/panossoerp/internal/domain/production_order/repository"
	stockentity "github.com/FelipePn10/panossoerp/internal/domain/stock/entity"
	stockrepo "github.com/FelipePn10/panossoerp/internal/domain/stock/repository"
)

// ReturnScrapUseCase returns the scrap/offcut generated by a production order to
// stock as a valued by-product (e.g. metal scrap or sheet/bar offcuts that the
// shop sells back or reuses). It posts an IN movement of the scrap item at the
// informed unit value, so the by-product carries a cost in inventory.
type ReturnScrapUseCase struct {
	Repo      repository.ProductionOrderRepository
	Auth      ports.AuthService
	StockRepo stockrepo.StockRepository
}

func (uc *ReturnScrapUseCase) Execute(ctx context.Context, dto request.ReturnScrapDTO) (*stockentity.StockMovement, error) {
	if !uc.Auth.CanCreatePlannedOrder(ctx) {
		return nil, errorsuc.ErrUnauthorized
	}
	if uc.StockRepo == nil {
		return nil, fmt.Errorf("scrap return not configured: stock repository missing")
	}
	if dto.Quantity <= 0 {
		return nil, fmt.Errorf("scrap quantity must be positive")
	}

	// Ensure the order exists and derive the authoring user.
	order, err := uc.Repo.GetByCode(ctx, dto.ProductionOrderID)
	if err != nil {
		return nil, err
	}

	refType := stockentity.ReferenceTypeProductionOrder
	refCode := order.ID
	mov := &stockentity.StockMovement{
		ItemCode:      dto.ScrapItemCode,
		Mask:          dto.Mask,
		WarehouseID:   dto.WarehouseID,
		MovementType:  stockentity.MovementTypeIn,
		Quantity:      dto.Quantity,
		UnitPrice:     dto.UnitValue,
		TotalPrice:    dto.UnitValue * dto.Quantity,
		ReferenceType: &refType,
		ReferenceCode: &refCode,
		Lot:           dto.Lot,
		Notes:         dto.Notes,
		CreatedBy:     order.CreatedBy,
	}
	return uc.StockRepo.CreateMovement(ctx, mov)
}
