// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allocation.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addAllocationBaseItem = `-- name: AddAllocationBaseItem :one
INSERT INTO allocation_base_items (allocation_base_id, cost_center_id, amount, percentage)
VALUES ($1, $2, $3, $4)
    RETURNING id, allocation_base_id, cost_center_id, amount, percentage, created_at
`

type AddAllocationBaseItemParams struct {
	AllocationBaseID int64
	CostCenterID     int64
	Amount           float64
	Percentage       float64
}

func (q *Queries) AddAllocationBaseItem(ctx context.Context, arg AddAllocationBaseItemParams) (AllocationBaseItem, error) {
	row := q.db.QueryRowContext(ctx, addAllocationBaseItem,
		arg.AllocationBaseID,
		arg.CostCenterID,
		arg.Amount,
		arg.Percentage,
	)
	var i AllocationBaseItem
	err := row.Scan(
		&i.ID,
		&i.AllocationBaseID,
		&i.CostCenterID,
		&i.Amount,
		&i.Percentage,
		&i.CreatedAt,
	)
	return i, err
}

const createAllocationBase = `-- name: CreateAllocationBase :one
INSERT INTO allocation_bases (code, description, period, observation, created_by)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, code, description, period, observation, created_at, updated_at, created_by
`

type CreateAllocationBaseParams struct {
	Code        string
	Description string
	Period      string
	Observation sql.NullString
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateAllocationBase(ctx context.Context, arg CreateAllocationBaseParams) (AllocationBasis, error) {
	row := q.db.QueryRowContext(ctx, createAllocationBase,
		arg.Code,
		arg.Description,
		arg.Period,
		arg.Observation,
		arg.CreatedBy,
	)
	var i AllocationBasis
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Period,
		&i.Observation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteAllocationBase = `-- name: DeleteAllocationBase :exec
DELETE FROM allocation_bases WHERE id = $1
`

func (q *Queries) DeleteAllocationBase(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllocationBase, id)
	return err
}

const deleteAllocationBaseItems = `-- name: DeleteAllocationBaseItems :exec
DELETE FROM allocation_base_items WHERE allocation_base_id = $1
`

func (q *Queries) DeleteAllocationBaseItems(ctx context.Context, allocationBaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllocationBaseItems, allocationBaseID)
	return err
}

const getAllocationBaseByID = `-- name: GetAllocationBaseByID :one
SELECT id, code, description, period, observation, created_at, updated_at, created_by FROM allocation_bases WHERE id = $1
`

func (q *Queries) GetAllocationBaseByID(ctx context.Context, id int64) (AllocationBasis, error) {
	row := q.db.QueryRowContext(ctx, getAllocationBaseByID, id)
	var i AllocationBasis
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Period,
		&i.Observation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAllocationBaseItems = `-- name: GetAllocationBaseItems :many
SELECT id, allocation_base_id, cost_center_id, amount, percentage, created_at FROM allocation_base_items WHERE allocation_base_id = $1
`

func (q *Queries) GetAllocationBaseItems(ctx context.Context, allocationBaseID int64) ([]AllocationBaseItem, error) {
	rows, err := q.db.QueryContext(ctx, getAllocationBaseItems, allocationBaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllocationBaseItem
	for rows.Next() {
		var i AllocationBaseItem
		if err := rows.Scan(
			&i.ID,
			&i.AllocationBaseID,
			&i.CostCenterID,
			&i.Amount,
			&i.Percentage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationBases = `-- name: ListAllocationBases :many
SELECT id, code, description, period, observation, created_at, updated_at, created_by FROM allocation_bases ORDER BY created_at DESC
`

func (q *Queries) ListAllocationBases(ctx context.Context) ([]AllocationBasis, error) {
	rows, err := q.db.QueryContext(ctx, listAllocationBases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllocationBasis
	for rows.Next() {
		var i AllocationBasis
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Period,
			&i.Observation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
