// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allocation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAllocationBaseItem = `-- name: AddAllocationBaseItem :one
INSERT INTO allocation_base_items (allocation_base_code, cost_center_code, amount, percentage)
SELECT $1, $2, $3, $4
FROM allocation_bases b
WHERE b.code = $1 AND b.enterprise_id = $5
    RETURNING id, amount, percentage, created_at, allocation_base_code, cost_center_code
`

type AddAllocationBaseItemParams struct {
	AllocationBaseCode int32
	CostCenterCode     int32
	Amount             float64
	Percentage         float64
	EnterpriseID       *int64
}

func (q *Queries) AddAllocationBaseItem(ctx context.Context, arg AddAllocationBaseItemParams) (AllocationBaseItem, error) {
	row := q.db.QueryRow(ctx, addAllocationBaseItem,
		arg.AllocationBaseCode,
		arg.CostCenterCode,
		arg.Amount,
		arg.Percentage,
		arg.EnterpriseID,
	)
	var i AllocationBaseItem
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Percentage,
		&i.CreatedAt,
		&i.AllocationBaseCode,
		&i.CostCenterCode,
	)
	return i, err
}

const createAllocationBase = `-- name: CreateAllocationBase :one
INSERT INTO allocation_bases (code, description, period, observation, created_by, enterprise_id)
VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, code, description, period, observation, created_at, updated_at, created_by, enterprise_id
`

type CreateAllocationBaseParams struct {
	Code         int32
	Description  string
	Period       string
	Observation  pgtype.Text
	CreatedBy    pgtype.UUID
	EnterpriseID *int64
}

func (q *Queries) CreateAllocationBase(ctx context.Context, arg CreateAllocationBaseParams) (AllocationBasis, error) {
	row := q.db.QueryRow(ctx, createAllocationBase,
		arg.Code,
		arg.Description,
		arg.Period,
		arg.Observation,
		arg.CreatedBy,
		arg.EnterpriseID,
	)
	var i AllocationBasis
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Period,
		&i.Observation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.EnterpriseID,
	)
	return i, err
}

const deleteAllocationBase = `-- name: DeleteAllocationBase :exec
DELETE FROM allocation_bases WHERE code = $1 AND enterprise_id = $2
`

type DeleteAllocationBaseParams struct {
	Code         int32
	EnterpriseID *int64
}

func (q *Queries) DeleteAllocationBase(ctx context.Context, arg DeleteAllocationBaseParams) error {
	_, err := q.db.Exec(ctx, deleteAllocationBase, arg.Code, arg.EnterpriseID)
	return err
}

const deleteAllocationBaseItems = `-- name: DeleteAllocationBaseItems :exec
DELETE FROM allocation_base_items i
USING allocation_bases b
WHERE i.allocation_base_code = $1
  AND b.code = i.allocation_base_code
  AND b.enterprise_id = $2
`

type DeleteAllocationBaseItemsParams struct {
	AllocationBaseCode int32
	EnterpriseID       *int64
}

func (q *Queries) DeleteAllocationBaseItems(ctx context.Context, arg DeleteAllocationBaseItemsParams) error {
	_, err := q.db.Exec(ctx, deleteAllocationBaseItems, arg.AllocationBaseCode, arg.EnterpriseID)
	return err
}

const getAllocationBaseByCode = `-- name: GetAllocationBaseByCode :one
SELECT id, code, description, period, observation, created_at, updated_at, created_by, enterprise_id FROM allocation_bases WHERE code = $1 AND enterprise_id = $2
`

type GetAllocationBaseByCodeParams struct {
	Code         int32
	EnterpriseID *int64
}

func (q *Queries) GetAllocationBaseByCode(ctx context.Context, arg GetAllocationBaseByCodeParams) (AllocationBasis, error) {
	row := q.db.QueryRow(ctx, getAllocationBaseByCode, arg.Code, arg.EnterpriseID)
	var i AllocationBasis
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Period,
		&i.Observation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.EnterpriseID,
	)
	return i, err
}

const getAllocationBaseItems = `-- name: GetAllocationBaseItems :many
SELECT i.id, i.amount, i.percentage, i.created_at, i.allocation_base_code, i.cost_center_code FROM allocation_base_items i
JOIN allocation_bases b ON b.code = i.allocation_base_code AND b.enterprise_id = $2
WHERE i.allocation_base_code = $1
`

type GetAllocationBaseItemsParams struct {
	AllocationBaseCode int32
	EnterpriseID       *int64
}

// As linhas seguem a base: `allocation_base_items` não tem coluna de empresa, e
// a posse dela é a da base de rateio referenciada.
func (q *Queries) GetAllocationBaseItems(ctx context.Context, arg GetAllocationBaseItemsParams) ([]AllocationBaseItem, error) {
	rows, err := q.db.Query(ctx, getAllocationBaseItems, arg.AllocationBaseCode, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllocationBaseItem
	for rows.Next() {
		var i AllocationBaseItem
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Percentage,
			&i.CreatedAt,
			&i.AllocationBaseCode,
			&i.CostCenterCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationBases = `-- name: ListAllocationBases :many
SELECT id, code, description, period, observation, created_at, updated_at, created_by, enterprise_id FROM allocation_bases WHERE enterprise_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAllocationBases(ctx context.Context, enterpriseID *int64) ([]AllocationBasis, error) {
	rows, err := q.db.Query(ctx, listAllocationBases, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllocationBasis
	for rows.Next() {
		var i AllocationBasis
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Period,
			&i.Observation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.EnterpriseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
