// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bom.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBom = `-- name: CreateBom :one
INSERT INTO boms (
    product_id,
    mask,
    bom_type,
    version,
    status,
    valid_from
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, product_id, bom_type, version, status, valid_from, created_at, mask
`

type CreateBomParams struct {
	ProductID int64
	Mask      int64
	BomType   string
	Version   int32
	Status    string
	ValidFrom pgtype.Date
}

func (q *Queries) CreateBom(ctx context.Context, arg CreateBomParams) (Bom, error) {
	row := q.db.QueryRow(ctx, createBom,
		arg.ProductID,
		arg.Mask,
		arg.BomType,
		arg.Version,
		arg.Status,
		arg.ValidFrom,
	)
	var i Bom
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BomType,
		&i.Version,
		&i.Status,
		&i.ValidFrom,
		&i.CreatedAt,
		&i.Mask,
	)
	return i, err
}
