// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bomitems.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBomItem = `-- name: CreateBomItem :one
INSERT INTO bom_items (
    bom_id,
    component_id,
    quantity,
    uom,
    scrap_percent,
    operation_id,
    mask_component
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, bom_id, component_id, quantity, uom, scrap_percent, operation_id, created_at, mask_component
`

type CreateBomItemParams struct {
	BomID         int64
	ComponentID   int64
	Quantity      pgtype.Numeric
	Uom           pgtype.Text
	ScrapPercent  pgtype.Numeric
	OperationID   int64
	MaskComponent int64
}

func (q *Queries) CreateBomItem(ctx context.Context, arg CreateBomItemParams) (BomItem, error) {
	row := q.db.QueryRow(ctx, createBomItem,
		arg.BomID,
		arg.ComponentID,
		arg.Quantity,
		arg.Uom,
		arg.ScrapPercent,
		arg.OperationID,
		arg.MaskComponent,
	)
	var i BomItem
	err := row.Scan(
		&i.ID,
		&i.BomID,
		&i.ComponentID,
		&i.Quantity,
		&i.Uom,
		&i.ScrapPercent,
		&i.OperationID,
		&i.CreatedAt,
		&i.MaskComponent,
	)
	return i, err
}
