// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_center.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCostCenter = `-- name: CreateCostCenter :one

INSERT INTO cost_centers (code, description, parent_code, type, is_ratio, start_date, end_date, created_by, enterprise_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by, enterprise_id
`

type CreateCostCenterParams struct {
	Code         int32
	Description  string
	ParentCode   *int32
	Type         TypeCcEnum
	IsRatio      bool
	StartDate    pgtype.Date
	EndDate      *time.Time
	CreatedBy    pgtype.UUID
	EnterpriseID *int64
}

// Toda consulta filtra por empresa (migração 343). `cost_centers` não tinha
// coluna de empresa: era global por construção.
func (q *Queries) CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, createCostCenter,
		arg.Code,
		arg.Description,
		arg.ParentCode,
		arg.Type,
		arg.IsRatio,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
		arg.EnterpriseID,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.ParentCode,
		&i.Type,
		&i.IsRatio,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.EnterpriseID,
	)
	return i, err
}

const deleteCostCenter = `-- name: DeleteCostCenter :exec
UPDATE cost_centers SET is_active = FALSE, updated_at = NOW()
WHERE code = $1 AND enterprise_id = $2
`

type DeleteCostCenterParams struct {
	Code         int32
	EnterpriseID *int64
}

func (q *Queries) DeleteCostCenter(ctx context.Context, arg DeleteCostCenterParams) error {
	_, err := q.db.Exec(ctx, deleteCostCenter, arg.Code, arg.EnterpriseID)
	return err
}

const getCostCenterByCode = `-- name: GetCostCenterByCode :one
SELECT id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by, enterprise_id FROM cost_centers WHERE code = $1 AND enterprise_id = $2
`

type GetCostCenterByCodeParams struct {
	Code         int32
	EnterpriseID *int64
}

func (q *Queries) GetCostCenterByCode(ctx context.Context, arg GetCostCenterByCodeParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, getCostCenterByCode, arg.Code, arg.EnterpriseID)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.ParentCode,
		&i.Type,
		&i.IsRatio,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.EnterpriseID,
	)
	return i, err
}

const listCostCenters = `-- name: ListCostCenters :many
SELECT id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by, enterprise_id FROM cost_centers
WHERE is_active = TRUE AND enterprise_id = $1
ORDER BY code
`

func (q *Queries) ListCostCenters(ctx context.Context, enterpriseID *int64) ([]CostCenter, error) {
	rows, err := q.db.Query(ctx, listCostCenters, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.ParentCode,
			&i.Type,
			&i.IsRatio,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.EnterpriseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostCentersByType = `-- name: ListCostCentersByType :many
SELECT id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by, enterprise_id FROM cost_centers
WHERE type = $1 AND is_active = TRUE AND enterprise_id = $2
ORDER BY code
`

type ListCostCentersByTypeParams struct {
	Type         TypeCcEnum
	EnterpriseID *int64
}

func (q *Queries) ListCostCentersByType(ctx context.Context, arg ListCostCentersByTypeParams) ([]CostCenter, error) {
	rows, err := q.db.Query(ctx, listCostCentersByType, arg.Type, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.ParentCode,
			&i.Type,
			&i.IsRatio,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.EnterpriseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCostCenter = `-- name: UpdateCostCenter :one
UPDATE cost_centers
SET description = $1,
    parent_code = $2,
    type = $3,
    is_ratio = $4,
    start_date = $5,
    end_date = $6,
    updated_at = NOW()
WHERE id = $7 AND enterprise_id = $8
    RETURNING id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by, enterprise_id
`

type UpdateCostCenterParams struct {
	Description  string
	ParentCode   *int32
	Type         TypeCcEnum
	IsRatio      bool
	StartDate    pgtype.Date
	EndDate      *time.Time
	ID           int64
	EnterpriseID *int64
}

func (q *Queries) UpdateCostCenter(ctx context.Context, arg UpdateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, updateCostCenter,
		arg.Description,
		arg.ParentCode,
		arg.Type,
		arg.IsRatio,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
		arg.EnterpriseID,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.ParentCode,
		&i.Type,
		&i.IsRatio,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.EnterpriseID,
	)
	return i, err
}
