// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_center.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCostCenter = `-- name: CreateCostCenter :one
INSERT INTO cost_centers (code, description, parent_code, type, is_ratio, start_date, end_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by
`

type CreateCostCenterParams struct {
	Code        int32
	Description string
	ParentCode  *int32
	Type        TypeCcEnum
	IsRatio     bool
	StartDate   time.Time
	EndDate     *time.Time
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRowContext(ctx, createCostCenter,
		arg.Code,
		arg.Description,
		arg.ParentCode,
		arg.Type,
		arg.IsRatio,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.ParentCode,
		&i.Type,
		&i.IsRatio,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteCostCenter = `-- name: DeleteCostCenter :exec
UPDATE cost_centers SET is_active = FALSE, updated_at = NOW() WHERE code = $1
`

func (q *Queries) DeleteCostCenter(ctx context.Context, code int32) error {
	_, err := q.db.ExecContext(ctx, deleteCostCenter, code)
	return err
}

const getCostCenterByCode = `-- name: GetCostCenterByCode :one
SELECT id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by FROM cost_centers WHERE code = $1
`

func (q *Queries) GetCostCenterByCode(ctx context.Context, code int32) (CostCenter, error) {
	row := q.db.QueryRowContext(ctx, getCostCenterByCode, code)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.ParentCode,
		&i.Type,
		&i.IsRatio,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listCostCenters = `-- name: ListCostCenters :many
SELECT id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by FROM cost_centers WHERE is_active = TRUE ORDER BY code
`

func (q *Queries) ListCostCenters(ctx context.Context) ([]CostCenter, error) {
	rows, err := q.db.QueryContext(ctx, listCostCenters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.ParentCode,
			&i.Type,
			&i.IsRatio,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostCentersByType = `-- name: ListCostCentersByType :many
SELECT id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by FROM cost_centers WHERE type = $1 AND is_active = TRUE ORDER BY code
`

func (q *Queries) ListCostCentersByType(ctx context.Context, type_ TypeCcEnum) ([]CostCenter, error) {
	rows, err := q.db.QueryContext(ctx, listCostCentersByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.ParentCode,
			&i.Type,
			&i.IsRatio,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCostCenter = `-- name: UpdateCostCenter :one
UPDATE cost_centers
SET description = $1,
    parent_code = $2,
    type = $3,
    is_ratio = $4,
    start_date = $5,
    end_date = $6,
    updated_at = NOW()
WHERE id = $7
    RETURNING id, code, description, parent_code, type, is_ratio, start_date, end_date, is_active, created_at, updated_at, created_by
`

type UpdateCostCenterParams struct {
	Description string
	ParentCode  *int32
	Type        TypeCcEnum
	IsRatio     bool
	StartDate   time.Time
	EndDate     *time.Time
	ID          int64
}

func (q *Queries) UpdateCostCenter(ctx context.Context, arg UpdateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRowContext(ctx, updateCostCenter,
		arg.Description,
		arg.ParentCode,
		arg.Type,
		arg.IsRatio,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.ParentCode,
		&i.Type,
		&i.IsRatio,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
