// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employee (
    enterprise_id,
    code,
    description,
    name
) VALUES (
$1, $2, $3, $4
)
RETURNING id, enterprise_id, code, description, name, created_at
`

type CreateEmployeeParams struct {
	EnterpriseID int32
	Code         int32
	Description  pgtype.Text
	Name         string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.EnterpriseID,
		arg.Code,
		arg.Description,
		arg.Name,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
