// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enterprise.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnterprise = `-- name: CreateEnterprise :one
INSERT INTO enterprise (
    code,
    name,
    created_by,
    created_at
) VALUES (
    $1, $2, $3, now()
) RETURNING id, code, name, created_at, created_by
`

type CreateEnterpriseParams struct {
	Code      int32
	Name      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateEnterprise(ctx context.Context, arg CreateEnterpriseParams) (Enterprise, error) {
	row := q.db.QueryRow(ctx, createEnterprise, arg.Code, arg.Name, arg.CreatedBy)
	var i Enterprise
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
