// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry_operation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addStateGroupUF = `-- name: AddStateGroupUF :exec
INSERT INTO state_group_ufs (state_group_code, uf)
VALUES ($1, $2)
ON CONFLICT (state_group_code, uf) DO NOTHING
`

type AddStateGroupUFParams struct {
	StateGroupCode int64
	Uf             string
}

func (q *Queries) AddStateGroupUF(ctx context.Context, arg AddStateGroupUFParams) error {
	_, err := q.db.Exec(ctx, addStateGroupUF, arg.StateGroupCode, arg.Uf)
	return err
}

const createEntryOperationType = `-- name: CreateEntryOperationType :one

INSERT INTO entry_operation_types (
    code, description, invoice_type_code, nature_operation,
    classification_type, classification_code, state_group_code, supplier_type_code, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, description, invoice_type_code, nature_operation, classification_type, classification_code, state_group_code, supplier_type_code, is_active, created_at, created_by
`

type CreateEntryOperationTypeParams struct {
	Code               int64
	Description        string
	InvoiceTypeCode    *int64
	NatureOperation    string
	ClassificationType pgtype.Text
	ClassificationCode pgtype.Text
	StateGroupCode     *int64
	SupplierTypeCode   *int64
	CreatedBy          pgtype.UUID
}

// ─── Entry Operation Types ────────────────────────────────────────────────────
func (q *Queries) CreateEntryOperationType(ctx context.Context, arg CreateEntryOperationTypeParams) (EntryOperationType, error) {
	row := q.db.QueryRow(ctx, createEntryOperationType,
		arg.Code,
		arg.Description,
		arg.InvoiceTypeCode,
		arg.NatureOperation,
		arg.ClassificationType,
		arg.ClassificationCode,
		arg.StateGroupCode,
		arg.SupplierTypeCode,
		arg.CreatedBy,
	)
	var i EntryOperationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.InvoiceTypeCode,
		&i.NatureOperation,
		&i.ClassificationType,
		&i.ClassificationCode,
		&i.StateGroupCode,
		&i.SupplierTypeCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createStateGroup = `-- name: CreateStateGroup :one

INSERT INTO state_groups (code, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, code, description, is_active, created_at, created_by
`

type CreateStateGroupParams struct {
	Code        int64
	Description string
	CreatedBy   pgtype.UUID
}

// ─── State Groups ─────────────────────────────────────────────────────────────
func (q *Queries) CreateStateGroup(ctx context.Context, arg CreateStateGroupParams) (StateGroup, error) {
	row := q.db.QueryRow(ctx, createStateGroup, arg.Code, arg.Description, arg.CreatedBy)
	var i StateGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getEntryOperationTypeByCode = `-- name: GetEntryOperationTypeByCode :one
SELECT id, code, description, invoice_type_code, nature_operation, classification_type, classification_code, state_group_code, supplier_type_code, is_active, created_at, created_by FROM entry_operation_types WHERE code = $1
`

func (q *Queries) GetEntryOperationTypeByCode(ctx context.Context, code int64) (EntryOperationType, error) {
	row := q.db.QueryRow(ctx, getEntryOperationTypeByCode, code)
	var i EntryOperationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.InvoiceTypeCode,
		&i.NatureOperation,
		&i.ClassificationType,
		&i.ClassificationCode,
		&i.StateGroupCode,
		&i.SupplierTypeCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getStateGroupByCode = `-- name: GetStateGroupByCode :one
SELECT id, code, description, is_active, created_at, created_by FROM state_groups WHERE code = $1
`

func (q *Queries) GetStateGroupByCode(ctx context.Context, code int64) (StateGroup, error) {
	row := q.db.QueryRow(ctx, getStateGroupByCode, code)
	var i StateGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listEntryOperationTypes = `-- name: ListEntryOperationTypes :many
SELECT id, code, description, invoice_type_code, nature_operation, classification_type, classification_code, state_group_code, supplier_type_code, is_active, created_at, created_by FROM entry_operation_types
WHERE ($1::BOOLEAN = FALSE OR is_active = TRUE)
ORDER BY code
`

func (q *Queries) ListEntryOperationTypes(ctx context.Context, dollar_1 bool) ([]EntryOperationType, error) {
	rows, err := q.db.Query(ctx, listEntryOperationTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryOperationType
	for rows.Next() {
		var i EntryOperationType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.InvoiceTypeCode,
			&i.NatureOperation,
			&i.ClassificationType,
			&i.ClassificationCode,
			&i.StateGroupCode,
			&i.SupplierTypeCode,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateGroupUFs = `-- name: ListStateGroupUFs :many
SELECT uf FROM state_group_ufs WHERE state_group_code = $1 ORDER BY uf
`

func (q *Queries) ListStateGroupUFs(ctx context.Context, stateGroupCode int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listStateGroupUFs, stateGroupCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var uf string
		if err := rows.Scan(&uf); err != nil {
			return nil, err
		}
		items = append(items, uf)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStateGroups = `-- name: ListStateGroups :many
SELECT id, code, description, is_active, created_at, created_by FROM state_groups ORDER BY code
`

func (q *Queries) ListStateGroups(ctx context.Context) ([]StateGroup, error) {
	rows, err := q.db.Query(ctx, listStateGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StateGroup
	for rows.Next() {
		var i StateGroup
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEntryOperationTypeCode = `-- name: NextEntryOperationTypeCode :one
SELECT COALESCE(MAX(code), 0) + 1 AS next_code FROM entry_operation_types
`

func (q *Queries) NextEntryOperationTypeCode(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextEntryOperationTypeCode)
	var next_code int32
	err := row.Scan(&next_code)
	return next_code, err
}

const nextStateGroupCode = `-- name: NextStateGroupCode :one
SELECT COALESCE(MAX(code), 0) + 1 AS next_code FROM state_groups
`

func (q *Queries) NextStateGroupCode(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextStateGroupCode)
	var next_code int32
	err := row.Scan(&next_code)
	return next_code, err
}

const uFInStateGroup = `-- name: UFInStateGroup :one
SELECT EXISTS (
    SELECT 1 FROM state_group_ufs WHERE state_group_code = $1 AND uf = $2
) AS in_group
`

type UFInStateGroupParams struct {
	StateGroupCode int64
	Uf             string
}

func (q *Queries) UFInStateGroup(ctx context.Context, arg UFInStateGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, uFInStateGroup, arg.StateGroupCode, arg.Uf)
	var in_group bool
	err := row.Scan(&in_group)
	return in_group, err
}

const updateEntryOperationType = `-- name: UpdateEntryOperationType :one
UPDATE entry_operation_types SET
    description = $2, invoice_type_code = $3, nature_operation = $4,
    classification_type = $5, classification_code = $6, state_group_code = $7,
    supplier_type_code = $8, is_active = $9
WHERE code = $1
RETURNING id, code, description, invoice_type_code, nature_operation, classification_type, classification_code, state_group_code, supplier_type_code, is_active, created_at, created_by
`

type UpdateEntryOperationTypeParams struct {
	Code               int64
	Description        string
	InvoiceTypeCode    *int64
	NatureOperation    string
	ClassificationType pgtype.Text
	ClassificationCode pgtype.Text
	StateGroupCode     *int64
	SupplierTypeCode   *int64
	IsActive           bool
}

func (q *Queries) UpdateEntryOperationType(ctx context.Context, arg UpdateEntryOperationTypeParams) (EntryOperationType, error) {
	row := q.db.QueryRow(ctx, updateEntryOperationType,
		arg.Code,
		arg.Description,
		arg.InvoiceTypeCode,
		arg.NatureOperation,
		arg.ClassificationType,
		arg.ClassificationCode,
		arg.StateGroupCode,
		arg.SupplierTypeCode,
		arg.IsActive,
	)
	var i EntryOperationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.InvoiceTypeCode,
		&i.NatureOperation,
		&i.ClassificationType,
		&i.ClassificationCode,
		&i.StateGroupCode,
		&i.SupplierTypeCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
