// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fiscal_classification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFiscalClassification = `-- name: CreateFiscalClassification :one

INSERT INTO fiscal_classifications (
    code, description, ncm, cest,
    ipi_rate, ipi_indicator, apuracao, cst_ipi_entrada, cst_ipi_saida,
    pis_rate, pis_indicator, cst_pis_entrada, cst_pis_saida,
    cofins_rate, cofins_indicator, cst_cofins_entrada, cst_cofins_saida, cofins_majorado_pct,
    pis_st_pct, cofins_st_pct,
    pis_consumo_pct, cst_pis_consumo_entrada, cst_pis_consumo_saida,
    cofins_consumo_pct, cst_cofins_consumo_entrada, cst_cofins_consumo_saida,
    pis_retencao_pct, cst_pis_retencao, cofins_retencao_pct, cst_cofins_retencao,
    pis_reducao_pct, cst_pis_reducao, cofins_reducao_pct, cst_cofins_reducao,
    desc_pis_zf_pct, desc_cofins_zf_pct,
    ex_tarifario, un_ipi, un_tributacao, mod_bc_icms, mod_bc_icms_st,
    cod_clas_trib, cod_clas_trib_trib_reg, obs_fiscal, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20,
    $21, $22, $23,
    $24, $25, $26,
    $27, $28, $29, $30,
    $31, $32, $33, $34,
    $35, $36,
    $37, $38, $39, $40, $41,
    $42, $43, $44, $45
) RETURNING id, code, description, ncm, cest, ipi_rate, ipi_indicator, apuracao, cst_ipi_entrada, cst_ipi_saida, pis_rate, pis_indicator, cst_pis_entrada, cst_pis_saida, cofins_rate, cofins_indicator, cst_cofins_entrada, cst_cofins_saida, cofins_majorado_pct, pis_st_pct, cofins_st_pct, pis_consumo_pct, cst_pis_consumo_entrada, cst_pis_consumo_saida, cofins_consumo_pct, cst_cofins_consumo_entrada, cst_cofins_consumo_saida, pis_retencao_pct, cst_pis_retencao, cofins_retencao_pct, cst_cofins_retencao, pis_reducao_pct, cst_pis_reducao, cofins_reducao_pct, cst_cofins_reducao, desc_pis_zf_pct, desc_cofins_zf_pct, ex_tarifario, un_ipi, un_tributacao, mod_bc_icms, mod_bc_icms_st, cod_clas_trib, cod_clas_trib_trib_reg, obs_fiscal, is_active, created_at, created_by, updated_at
`

type CreateFiscalClassificationParams struct {
	Code                    int64
	Description             string
	Ncm                     pgtype.Text
	Cest                    pgtype.Text
	IpiRate                 pgtype.Numeric
	IpiIndicator            string
	Apuracao                pgtype.Text
	CstIpiEntrada           pgtype.Text
	CstIpiSaida             pgtype.Text
	PisRate                 pgtype.Numeric
	PisIndicator            string
	CstPisEntrada           pgtype.Text
	CstPisSaida             pgtype.Text
	CofinsRate              pgtype.Numeric
	CofinsIndicator         string
	CstCofinsEntrada        pgtype.Text
	CstCofinsSaida          pgtype.Text
	CofinsMajoradoPct       pgtype.Numeric
	PisStPct                pgtype.Numeric
	CofinsStPct             pgtype.Numeric
	PisConsumoPct           pgtype.Numeric
	CstPisConsumoEntrada    pgtype.Text
	CstPisConsumoSaida      pgtype.Text
	CofinsConsumoPct        pgtype.Numeric
	CstCofinsConsumoEntrada pgtype.Text
	CstCofinsConsumoSaida   pgtype.Text
	PisRetencaoPct          pgtype.Numeric
	CstPisRetencao          pgtype.Text
	CofinsRetencaoPct       pgtype.Numeric
	CstCofinsRetencao       pgtype.Text
	PisReducaoPct           pgtype.Numeric
	CstPisReducao           pgtype.Text
	CofinsReducaoPct        pgtype.Numeric
	CstCofinsReducao        pgtype.Text
	DescPisZfPct            pgtype.Numeric
	DescCofinsZfPct         pgtype.Numeric
	ExTarifario             pgtype.Text
	UnIpi                   pgtype.Text
	UnTributacao            pgtype.Text
	ModBcIcms               pgtype.Text
	ModBcIcmsSt             pgtype.Text
	CodClasTrib             pgtype.Text
	CodClasTribTribReg      pgtype.Text
	ObsFiscal               pgtype.Text
	CreatedBy               pgtype.UUID
}

// ─── Fiscal Classifications ───────────────────────────────────────────────────
func (q *Queries) CreateFiscalClassification(ctx context.Context, arg CreateFiscalClassificationParams) (FiscalClassification, error) {
	row := q.db.QueryRow(ctx, createFiscalClassification,
		arg.Code,
		arg.Description,
		arg.Ncm,
		arg.Cest,
		arg.IpiRate,
		arg.IpiIndicator,
		arg.Apuracao,
		arg.CstIpiEntrada,
		arg.CstIpiSaida,
		arg.PisRate,
		arg.PisIndicator,
		arg.CstPisEntrada,
		arg.CstPisSaida,
		arg.CofinsRate,
		arg.CofinsIndicator,
		arg.CstCofinsEntrada,
		arg.CstCofinsSaida,
		arg.CofinsMajoradoPct,
		arg.PisStPct,
		arg.CofinsStPct,
		arg.PisConsumoPct,
		arg.CstPisConsumoEntrada,
		arg.CstPisConsumoSaida,
		arg.CofinsConsumoPct,
		arg.CstCofinsConsumoEntrada,
		arg.CstCofinsConsumoSaida,
		arg.PisRetencaoPct,
		arg.CstPisRetencao,
		arg.CofinsRetencaoPct,
		arg.CstCofinsRetencao,
		arg.PisReducaoPct,
		arg.CstPisReducao,
		arg.CofinsReducaoPct,
		arg.CstCofinsReducao,
		arg.DescPisZfPct,
		arg.DescCofinsZfPct,
		arg.ExTarifario,
		arg.UnIpi,
		arg.UnTributacao,
		arg.ModBcIcms,
		arg.ModBcIcmsSt,
		arg.CodClasTrib,
		arg.CodClasTribTribReg,
		arg.ObsFiscal,
		arg.CreatedBy,
	)
	var i FiscalClassification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Ncm,
		&i.Cest,
		&i.IpiRate,
		&i.IpiIndicator,
		&i.Apuracao,
		&i.CstIpiEntrada,
		&i.CstIpiSaida,
		&i.PisRate,
		&i.PisIndicator,
		&i.CstPisEntrada,
		&i.CstPisSaida,
		&i.CofinsRate,
		&i.CofinsIndicator,
		&i.CstCofinsEntrada,
		&i.CstCofinsSaida,
		&i.CofinsMajoradoPct,
		&i.PisStPct,
		&i.CofinsStPct,
		&i.PisConsumoPct,
		&i.CstPisConsumoEntrada,
		&i.CstPisConsumoSaida,
		&i.CofinsConsumoPct,
		&i.CstCofinsConsumoEntrada,
		&i.CstCofinsConsumoSaida,
		&i.PisRetencaoPct,
		&i.CstPisRetencao,
		&i.CofinsRetencaoPct,
		&i.CstCofinsRetencao,
		&i.PisReducaoPct,
		&i.CstPisReducao,
		&i.CofinsReducaoPct,
		&i.CstCofinsReducao,
		&i.DescPisZfPct,
		&i.DescCofinsZfPct,
		&i.ExTarifario,
		&i.UnIpi,
		&i.UnTributacao,
		&i.ModBcIcms,
		&i.ModBcIcmsSt,
		&i.CodClasTrib,
		&i.CodClasTribTribReg,
		&i.ObsFiscal,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createFiscalClassificationExportAttribute = `-- name: CreateFiscalClassificationExportAttribute :one

INSERT INTO fiscal_classification_export_attributes (classification_id, code, description, domain, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, classification_id, code, description, domain, start_date, end_date
`

type CreateFiscalClassificationExportAttributeParams struct {
	ClassificationID int64
	Code             string
	Description      pgtype.Text
	Domain           pgtype.Text
	StartDate        pgtype.Date
	EndDate          pgtype.Date
}

// ─── Export attributes ──────────────────────────────────────────────────────
func (q *Queries) CreateFiscalClassificationExportAttribute(ctx context.Context, arg CreateFiscalClassificationExportAttributeParams) (FiscalClassificationExportAttribute, error) {
	row := q.db.QueryRow(ctx, createFiscalClassificationExportAttribute,
		arg.ClassificationID,
		arg.Code,
		arg.Description,
		arg.Domain,
		arg.StartDate,
		arg.EndDate,
	)
	var i FiscalClassificationExportAttribute
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.Code,
		&i.Description,
		&i.Domain,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const createFiscalClassificationLanguage = `-- name: CreateFiscalClassificationLanguage :one

INSERT INTO fiscal_classification_languages (classification_id, language, description)
VALUES ($1, $2, $3)
ON CONFLICT (classification_id, language) DO UPDATE SET description = EXCLUDED.description
RETURNING id, classification_id, language, description
`

type CreateFiscalClassificationLanguageParams struct {
	ClassificationID int64
	Language         string
	Description      string
}

// ─── Languages ────────────────────────────────────────────────────────────────
func (q *Queries) CreateFiscalClassificationLanguage(ctx context.Context, arg CreateFiscalClassificationLanguageParams) (FiscalClassificationLanguage, error) {
	row := q.db.QueryRow(ctx, createFiscalClassificationLanguage, arg.ClassificationID, arg.Language, arg.Description)
	var i FiscalClassificationLanguage
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.Language,
		&i.Description,
	)
	return i, err
}

const deleteFiscalClassificationExportAttribute = `-- name: DeleteFiscalClassificationExportAttribute :exec
DELETE FROM fiscal_classification_export_attributes WHERE id = $1
`

func (q *Queries) DeleteFiscalClassificationExportAttribute(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFiscalClassificationExportAttribute, id)
	return err
}

const deleteFiscalClassificationLanguage = `-- name: DeleteFiscalClassificationLanguage :exec
DELETE FROM fiscal_classification_languages WHERE id = $1
`

func (q *Queries) DeleteFiscalClassificationLanguage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFiscalClassificationLanguage, id)
	return err
}

const getFiscalClassificationByCode = `-- name: GetFiscalClassificationByCode :one
SELECT id, code, description, ncm, cest, ipi_rate, ipi_indicator, apuracao, cst_ipi_entrada, cst_ipi_saida, pis_rate, pis_indicator, cst_pis_entrada, cst_pis_saida, cofins_rate, cofins_indicator, cst_cofins_entrada, cst_cofins_saida, cofins_majorado_pct, pis_st_pct, cofins_st_pct, pis_consumo_pct, cst_pis_consumo_entrada, cst_pis_consumo_saida, cofins_consumo_pct, cst_cofins_consumo_entrada, cst_cofins_consumo_saida, pis_retencao_pct, cst_pis_retencao, cofins_retencao_pct, cst_cofins_retencao, pis_reducao_pct, cst_pis_reducao, cofins_reducao_pct, cst_cofins_reducao, desc_pis_zf_pct, desc_cofins_zf_pct, ex_tarifario, un_ipi, un_tributacao, mod_bc_icms, mod_bc_icms_st, cod_clas_trib, cod_clas_trib_trib_reg, obs_fiscal, is_active, created_at, created_by, updated_at FROM fiscal_classifications WHERE code = $1
`

func (q *Queries) GetFiscalClassificationByCode(ctx context.Context, code int64) (FiscalClassification, error) {
	row := q.db.QueryRow(ctx, getFiscalClassificationByCode, code)
	var i FiscalClassification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Ncm,
		&i.Cest,
		&i.IpiRate,
		&i.IpiIndicator,
		&i.Apuracao,
		&i.CstIpiEntrada,
		&i.CstIpiSaida,
		&i.PisRate,
		&i.PisIndicator,
		&i.CstPisEntrada,
		&i.CstPisSaida,
		&i.CofinsRate,
		&i.CofinsIndicator,
		&i.CstCofinsEntrada,
		&i.CstCofinsSaida,
		&i.CofinsMajoradoPct,
		&i.PisStPct,
		&i.CofinsStPct,
		&i.PisConsumoPct,
		&i.CstPisConsumoEntrada,
		&i.CstPisConsumoSaida,
		&i.CofinsConsumoPct,
		&i.CstCofinsConsumoEntrada,
		&i.CstCofinsConsumoSaida,
		&i.PisRetencaoPct,
		&i.CstPisRetencao,
		&i.CofinsRetencaoPct,
		&i.CstCofinsRetencao,
		&i.PisReducaoPct,
		&i.CstPisReducao,
		&i.CofinsReducaoPct,
		&i.CstCofinsReducao,
		&i.DescPisZfPct,
		&i.DescCofinsZfPct,
		&i.ExTarifario,
		&i.UnIpi,
		&i.UnTributacao,
		&i.ModBcIcms,
		&i.ModBcIcmsSt,
		&i.CodClasTrib,
		&i.CodClasTribTribReg,
		&i.ObsFiscal,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listFiscalClassificationExportAttributes = `-- name: ListFiscalClassificationExportAttributes :many
SELECT id, classification_id, code, description, domain, start_date, end_date FROM fiscal_classification_export_attributes WHERE classification_id = $1 ORDER BY code
`

func (q *Queries) ListFiscalClassificationExportAttributes(ctx context.Context, classificationID int64) ([]FiscalClassificationExportAttribute, error) {
	rows, err := q.db.Query(ctx, listFiscalClassificationExportAttributes, classificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiscalClassificationExportAttribute
	for rows.Next() {
		var i FiscalClassificationExportAttribute
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationID,
			&i.Code,
			&i.Description,
			&i.Domain,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalClassificationLanguages = `-- name: ListFiscalClassificationLanguages :many
SELECT id, classification_id, language, description FROM fiscal_classification_languages WHERE classification_id = $1 ORDER BY language
`

func (q *Queries) ListFiscalClassificationLanguages(ctx context.Context, classificationID int64) ([]FiscalClassificationLanguage, error) {
	rows, err := q.db.Query(ctx, listFiscalClassificationLanguages, classificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiscalClassificationLanguage
	for rows.Next() {
		var i FiscalClassificationLanguage
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationID,
			&i.Language,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalClassifications = `-- name: ListFiscalClassifications :many
SELECT id, code, description, ncm, cest, ipi_rate, ipi_indicator, apuracao, cst_ipi_entrada, cst_ipi_saida, pis_rate, pis_indicator, cst_pis_entrada, cst_pis_saida, cofins_rate, cofins_indicator, cst_cofins_entrada, cst_cofins_saida, cofins_majorado_pct, pis_st_pct, cofins_st_pct, pis_consumo_pct, cst_pis_consumo_entrada, cst_pis_consumo_saida, cofins_consumo_pct, cst_cofins_consumo_entrada, cst_cofins_consumo_saida, pis_retencao_pct, cst_pis_retencao, cofins_retencao_pct, cst_cofins_retencao, pis_reducao_pct, cst_pis_reducao, cofins_reducao_pct, cst_cofins_reducao, desc_pis_zf_pct, desc_cofins_zf_pct, ex_tarifario, un_ipi, un_tributacao, mod_bc_icms, mod_bc_icms_st, cod_clas_trib, cod_clas_trib_trib_reg, obs_fiscal, is_active, created_at, created_by, updated_at FROM fiscal_classifications
WHERE ($1::BOOLEAN = FALSE OR is_active = TRUE)
ORDER BY code
`

func (q *Queries) ListFiscalClassifications(ctx context.Context, dollar_1 bool) ([]FiscalClassification, error) {
	rows, err := q.db.Query(ctx, listFiscalClassifications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiscalClassification
	for rows.Next() {
		var i FiscalClassification
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Ncm,
			&i.Cest,
			&i.IpiRate,
			&i.IpiIndicator,
			&i.Apuracao,
			&i.CstIpiEntrada,
			&i.CstIpiSaida,
			&i.PisRate,
			&i.PisIndicator,
			&i.CstPisEntrada,
			&i.CstPisSaida,
			&i.CofinsRate,
			&i.CofinsIndicator,
			&i.CstCofinsEntrada,
			&i.CstCofinsSaida,
			&i.CofinsMajoradoPct,
			&i.PisStPct,
			&i.CofinsStPct,
			&i.PisConsumoPct,
			&i.CstPisConsumoEntrada,
			&i.CstPisConsumoSaida,
			&i.CofinsConsumoPct,
			&i.CstCofinsConsumoEntrada,
			&i.CstCofinsConsumoSaida,
			&i.PisRetencaoPct,
			&i.CstPisRetencao,
			&i.CofinsRetencaoPct,
			&i.CstCofinsRetencao,
			&i.PisReducaoPct,
			&i.CstPisReducao,
			&i.CofinsReducaoPct,
			&i.CstCofinsReducao,
			&i.DescPisZfPct,
			&i.DescCofinsZfPct,
			&i.ExTarifario,
			&i.UnIpi,
			&i.UnTributacao,
			&i.ModBcIcms,
			&i.ModBcIcmsSt,
			&i.CodClasTrib,
			&i.CodClasTribTribReg,
			&i.ObsFiscal,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFiscalClassificationCode = `-- name: NextFiscalClassificationCode :one
SELECT COALESCE(MAX(code), 0) + 1 AS next_code FROM fiscal_classifications
`

func (q *Queries) NextFiscalClassificationCode(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextFiscalClassificationCode)
	var next_code int32
	err := row.Scan(&next_code)
	return next_code, err
}

const updateFiscalClassification = `-- name: UpdateFiscalClassification :one
UPDATE fiscal_classifications SET
    description = $2, ncm = $3, cest = $4,
    ipi_rate = $5, ipi_indicator = $6, apuracao = $7, cst_ipi_entrada = $8, cst_ipi_saida = $9,
    pis_rate = $10, pis_indicator = $11, cst_pis_entrada = $12, cst_pis_saida = $13,
    cofins_rate = $14, cofins_indicator = $15, cst_cofins_entrada = $16, cst_cofins_saida = $17, cofins_majorado_pct = $18,
    pis_st_pct = $19, cofins_st_pct = $20,
    pis_consumo_pct = $21, cst_pis_consumo_entrada = $22, cst_pis_consumo_saida = $23,
    cofins_consumo_pct = $24, cst_cofins_consumo_entrada = $25, cst_cofins_consumo_saida = $26,
    pis_retencao_pct = $27, cst_pis_retencao = $28, cofins_retencao_pct = $29, cst_cofins_retencao = $30,
    pis_reducao_pct = $31, cst_pis_reducao = $32, cofins_reducao_pct = $33, cst_cofins_reducao = $34,
    desc_pis_zf_pct = $35, desc_cofins_zf_pct = $36,
    ex_tarifario = $37, un_ipi = $38, un_tributacao = $39, mod_bc_icms = $40, mod_bc_icms_st = $41,
    cod_clas_trib = $42, cod_clas_trib_trib_reg = $43, obs_fiscal = $44, is_active = $45,
    updated_at = NOW()
WHERE code = $1
RETURNING id, code, description, ncm, cest, ipi_rate, ipi_indicator, apuracao, cst_ipi_entrada, cst_ipi_saida, pis_rate, pis_indicator, cst_pis_entrada, cst_pis_saida, cofins_rate, cofins_indicator, cst_cofins_entrada, cst_cofins_saida, cofins_majorado_pct, pis_st_pct, cofins_st_pct, pis_consumo_pct, cst_pis_consumo_entrada, cst_pis_consumo_saida, cofins_consumo_pct, cst_cofins_consumo_entrada, cst_cofins_consumo_saida, pis_retencao_pct, cst_pis_retencao, cofins_retencao_pct, cst_cofins_retencao, pis_reducao_pct, cst_pis_reducao, cofins_reducao_pct, cst_cofins_reducao, desc_pis_zf_pct, desc_cofins_zf_pct, ex_tarifario, un_ipi, un_tributacao, mod_bc_icms, mod_bc_icms_st, cod_clas_trib, cod_clas_trib_trib_reg, obs_fiscal, is_active, created_at, created_by, updated_at
`

type UpdateFiscalClassificationParams struct {
	Code                    int64
	Description             string
	Ncm                     pgtype.Text
	Cest                    pgtype.Text
	IpiRate                 pgtype.Numeric
	IpiIndicator            string
	Apuracao                pgtype.Text
	CstIpiEntrada           pgtype.Text
	CstIpiSaida             pgtype.Text
	PisRate                 pgtype.Numeric
	PisIndicator            string
	CstPisEntrada           pgtype.Text
	CstPisSaida             pgtype.Text
	CofinsRate              pgtype.Numeric
	CofinsIndicator         string
	CstCofinsEntrada        pgtype.Text
	CstCofinsSaida          pgtype.Text
	CofinsMajoradoPct       pgtype.Numeric
	PisStPct                pgtype.Numeric
	CofinsStPct             pgtype.Numeric
	PisConsumoPct           pgtype.Numeric
	CstPisConsumoEntrada    pgtype.Text
	CstPisConsumoSaida      pgtype.Text
	CofinsConsumoPct        pgtype.Numeric
	CstCofinsConsumoEntrada pgtype.Text
	CstCofinsConsumoSaida   pgtype.Text
	PisRetencaoPct          pgtype.Numeric
	CstPisRetencao          pgtype.Text
	CofinsRetencaoPct       pgtype.Numeric
	CstCofinsRetencao       pgtype.Text
	PisReducaoPct           pgtype.Numeric
	CstPisReducao           pgtype.Text
	CofinsReducaoPct        pgtype.Numeric
	CstCofinsReducao        pgtype.Text
	DescPisZfPct            pgtype.Numeric
	DescCofinsZfPct         pgtype.Numeric
	ExTarifario             pgtype.Text
	UnIpi                   pgtype.Text
	UnTributacao            pgtype.Text
	ModBcIcms               pgtype.Text
	ModBcIcmsSt             pgtype.Text
	CodClasTrib             pgtype.Text
	CodClasTribTribReg      pgtype.Text
	ObsFiscal               pgtype.Text
	IsActive                bool
}

func (q *Queries) UpdateFiscalClassification(ctx context.Context, arg UpdateFiscalClassificationParams) (FiscalClassification, error) {
	row := q.db.QueryRow(ctx, updateFiscalClassification,
		arg.Code,
		arg.Description,
		arg.Ncm,
		arg.Cest,
		arg.IpiRate,
		arg.IpiIndicator,
		arg.Apuracao,
		arg.CstIpiEntrada,
		arg.CstIpiSaida,
		arg.PisRate,
		arg.PisIndicator,
		arg.CstPisEntrada,
		arg.CstPisSaida,
		arg.CofinsRate,
		arg.CofinsIndicator,
		arg.CstCofinsEntrada,
		arg.CstCofinsSaida,
		arg.CofinsMajoradoPct,
		arg.PisStPct,
		arg.CofinsStPct,
		arg.PisConsumoPct,
		arg.CstPisConsumoEntrada,
		arg.CstPisConsumoSaida,
		arg.CofinsConsumoPct,
		arg.CstCofinsConsumoEntrada,
		arg.CstCofinsConsumoSaida,
		arg.PisRetencaoPct,
		arg.CstPisRetencao,
		arg.CofinsRetencaoPct,
		arg.CstCofinsRetencao,
		arg.PisReducaoPct,
		arg.CstPisReducao,
		arg.CofinsReducaoPct,
		arg.CstCofinsReducao,
		arg.DescPisZfPct,
		arg.DescCofinsZfPct,
		arg.ExTarifario,
		arg.UnIpi,
		arg.UnTributacao,
		arg.ModBcIcms,
		arg.ModBcIcmsSt,
		arg.CodClasTrib,
		arg.CodClasTribTribReg,
		arg.ObsFiscal,
		arg.IsActive,
	)
	var i FiscalClassification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Ncm,
		&i.Cest,
		&i.IpiRate,
		&i.IpiIndicator,
		&i.Apuracao,
		&i.CstIpiEntrada,
		&i.CstIpiSaida,
		&i.PisRate,
		&i.PisIndicator,
		&i.CstPisEntrada,
		&i.CstPisSaida,
		&i.CofinsRate,
		&i.CofinsIndicator,
		&i.CstCofinsEntrada,
		&i.CstCofinsSaida,
		&i.CofinsMajoradoPct,
		&i.PisStPct,
		&i.CofinsStPct,
		&i.PisConsumoPct,
		&i.CstPisConsumoEntrada,
		&i.CstPisConsumoSaida,
		&i.CofinsConsumoPct,
		&i.CstCofinsConsumoEntrada,
		&i.CstCofinsConsumoSaida,
		&i.PisRetencaoPct,
		&i.CstPisRetencao,
		&i.CofinsRetencaoPct,
		&i.CstCofinsRetencao,
		&i.PisReducaoPct,
		&i.CstPisReducao,
		&i.CofinsReducaoPct,
		&i.CstCofinsReducao,
		&i.DescPisZfPct,
		&i.DescCofinsZfPct,
		&i.ExTarifario,
		&i.UnIpi,
		&i.UnTributacao,
		&i.ModBcIcms,
		&i.ModBcIcmsSt,
		&i.CodClasTrib,
		&i.CodClasTribTribReg,
		&i.ObsFiscal,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
