// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generate_mask.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getOptionValueByID = `-- name: GetOptionValueByID :one
SELECT value FROM question_options WHERE id = $1
`

// SQLC query
func (q *Queries) GetOptionValueByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getOptionValueByID, id)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertItemMaskAnswer = `-- name: InsertItemMaskAnswer :exec
INSERT INTO item_mask_answers (mask_id, question_id, option_id, position)
VALUES ($1, $2, $3, $4)
`

type InsertItemMaskAnswerParams struct {
	MaskID     int64
	QuestionID int64
	OptionID   int64
	Position   int32
}

func (q *Queries) InsertItemMaskAnswer(ctx context.Context, arg InsertItemMaskAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertItemMaskAnswer,
		arg.MaskID,
		arg.QuestionID,
		arg.OptionID,
		arg.Position,
	)
	return err
}

const insertItemtMask = `-- name: InsertItemtMask :one
INSERT INTO item_masks (
    item_code,
    mask,
    mask_hash,
    created_by,
    created_at
)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, item_code, mask, mask_hash, created_by, created_at
`

type InsertItemtMaskParams struct {
	ItemCode  int64
	Mask      string
	MaskHash  string
	CreatedBy uuid.UUID
}

func (q *Queries) InsertItemtMask(ctx context.Context, arg InsertItemtMaskParams) (ItemMask, error) {
	row := q.db.QueryRowContext(ctx, insertItemtMask,
		arg.ItemCode,
		arg.Mask,
		arg.MaskHash,
		arg.CreatedBy,
	)
	var i ItemMask
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.Mask,
		&i.MaskHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
