// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    code,
    description,
    enterprise_id,
    created_by
) VALUES (
$1, $2, $3, $4
)
RETURNING id, code, description, enterprise_id, created_by, created_at
`

type CreateGroupParams struct {
	Code         int32
	Description  string
	EnterpriseID int64
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Code,
		arg.Description,
		arg.EnterpriseID,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.EnterpriseID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
