// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: independent_demand.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIndependentDemand = `-- name: CreateIndependentDemand :one
INSERT INTO independent_demands (code, item_code, mask, cost_center_code, quantity, demand_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, code, item_code, mask, cost_center_code, quantity, demand_date, is_active, created_at, updated_at, created_by
`

type CreateIndependentDemandParams struct {
	Code           int64
	ItemCode       int64
	Mask           pgtype.Text
	CostCenterCode pgtype.Int8
	Quantity       pgtype.Numeric
	DemandDate     pgtype.Date
	CreatedBy      pgtype.UUID
}

func (q *Queries) CreateIndependentDemand(ctx context.Context, arg CreateIndependentDemandParams) (IndependentDemand, error) {
	row := q.db.QueryRow(ctx, createIndependentDemand,
		arg.Code,
		arg.ItemCode,
		arg.Mask,
		arg.CostCenterCode,
		arg.Quantity,
		arg.DemandDate,
		arg.CreatedBy,
	)
	var i IndependentDemand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ItemCode,
		&i.Mask,
		&i.CostCenterCode,
		&i.Quantity,
		&i.DemandDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteIndependentDemand = `-- name: DeleteIndependentDemand :exec
UPDATE independent_demands SET is_active = FALSE, updated_at = NOW() WHERE code = $1
`

func (q *Queries) DeleteIndependentDemand(ctx context.Context, code int64) error {
	_, err := q.db.Exec(ctx, deleteIndependentDemand, code)
	return err
}

const getIndependentDemandByCode = `-- name: GetIndependentDemandByCode :one
SELECT id, code, item_code, mask, cost_center_code, quantity, demand_date, is_active, created_at, updated_at, created_by FROM independent_demands WHERE code = $1
`

func (q *Queries) GetIndependentDemandByCode(ctx context.Context, code int64) (IndependentDemand, error) {
	row := q.db.QueryRow(ctx, getIndependentDemandByCode, code)
	var i IndependentDemand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ItemCode,
		&i.Mask,
		&i.CostCenterCode,
		&i.Quantity,
		&i.DemandDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listDemandsByItem = `-- name: ListDemandsByItem :many
SELECT id, code, item_code, mask, cost_center_code, quantity, demand_date, is_active, created_at, updated_at, created_by FROM independent_demands WHERE item_code = $1 AND is_active = TRUE ORDER BY demand_date
`

func (q *Queries) ListDemandsByItem(ctx context.Context, itemCode int64) ([]IndependentDemand, error) {
	rows, err := q.db.Query(ctx, listDemandsByItem, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndependentDemand
	for rows.Next() {
		var i IndependentDemand
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ItemCode,
			&i.Mask,
			&i.CostCenterCode,
			&i.Quantity,
			&i.DemandDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDemandsFromDate = `-- name: ListDemandsFromDate :many
SELECT id, code, item_code, mask, cost_center_code, quantity, demand_date, is_active, created_at, updated_at, created_by FROM independent_demands WHERE demand_date >= $1 AND is_active = TRUE ORDER BY demand_date
`

func (q *Queries) ListDemandsFromDate(ctx context.Context, demandDate pgtype.Date) ([]IndependentDemand, error) {
	rows, err := q.db.Query(ctx, listDemandsFromDate, demandDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndependentDemand
	for rows.Next() {
		var i IndependentDemand
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ItemCode,
			&i.Mask,
			&i.CostCenterCode,
			&i.Quantity,
			&i.DemandDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndependentDemands = `-- name: ListIndependentDemands :many
SELECT id, code, item_code, mask, cost_center_code, quantity, demand_date, is_active, created_at, updated_at, created_by FROM independent_demands WHERE is_active = TRUE ORDER BY demand_date
`

func (q *Queries) ListIndependentDemands(ctx context.Context) ([]IndependentDemand, error) {
	rows, err := q.db.Query(ctx, listIndependentDemands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndependentDemand
	for rows.Next() {
		var i IndependentDemand
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ItemCode,
			&i.Mask,
			&i.CostCenterCode,
			&i.Quantity,
			&i.DemandDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndependentDemand = `-- name: UpdateIndependentDemand :one
UPDATE independent_demands
SET item_code = $1,
    mask = $2,
    cost_center_code = $3,
    quantity = $4,
    demand_date = $5,
    updated_at = NOW()
WHERE code = $6
    RETURNING id, code, item_code, mask, cost_center_code, quantity, demand_date, is_active, created_at, updated_at, created_by
`

type UpdateIndependentDemandParams struct {
	ItemCode       int64
	Mask           pgtype.Text
	CostCenterCode pgtype.Int8
	Quantity       pgtype.Numeric
	DemandDate     pgtype.Date
	Code           int64
}

func (q *Queries) UpdateIndependentDemand(ctx context.Context, arg UpdateIndependentDemandParams) (IndependentDemand, error) {
	row := q.db.QueryRow(ctx, updateIndependentDemand,
		arg.ItemCode,
		arg.Mask,
		arg.CostCenterCode,
		arg.Quantity,
		arg.DemandDate,
		arg.Code,
	)
	var i IndependentDemand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ItemCode,
		&i.Mask,
		&i.CostCenterCode,
		&i.Quantity,
		&i.DemandDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
