// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_questions.sql

package sqlc

import (
	"context"
	"time"
)

const associateQuestionItem = `-- name: AssociateQuestionItem :exec
INSERT INTO item_questions (
    item_code,
    question_id,
    position,
    created_at
) VALUES ($1, $2, $3, $4)
`

type AssociateQuestionItemParams struct {
	ItemCode   int64
	QuestionID int64
	Position   int32
	CreatedAt  time.Time
}

func (q *Queries) AssociateQuestionItem(ctx context.Context, arg AssociateQuestionItemParams) error {
	_, err := q.db.ExecContext(ctx, associateQuestionItem,
		arg.ItemCode,
		arg.QuestionID,
		arg.Position,
		arg.CreatedAt,
	)
	return err
}

const existsByItemAndPosition = `-- name: ExistsByItemAndPosition :one
SELECT EXISTS (
    SELECT 1
    FROM item_questions
    WHERE item_code = $1
      AND position = $2
)
`

type ExistsByItemAndPositionParams struct {
	ItemCode int64
	Position int32
}

func (q *Queries) ExistsByItemAndPosition(ctx context.Context, arg ExistsByItemAndPositionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByItemAndPosition, arg.ItemCode, arg.Position)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByItemAndQuestion = `-- name: ExistsByItemAndQuestion :one
SELECT EXISTS (
    SELECT 1
    FROM item_questions
    WHERE item_code = $1
      AND question_id = $2
)
`

type ExistsByItemAndQuestionParams struct {
	ItemCode   int64
	QuestionID int64
}

func (q *Queries) ExistsByItemAndQuestion(ctx context.Context, arg ExistsByItemAndQuestionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByItemAndQuestion, arg.ItemCode, arg.QuestionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
