// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_conversion.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemUnitConversion = `-- name: CreateItemUnitConversion :one

INSERT INTO item_unit_conversions (item_code, from_uom, to_uom, factor, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (item_code, from_uom, to_uom)
DO UPDATE SET factor = EXCLUDED.factor, is_active = TRUE
RETURNING id, item_code, from_uom, to_uom, factor, is_active, created_at, created_by
`

type CreateItemUnitConversionParams struct {
	ItemCode  int64
	FromUom   string
	ToUom     string
	Factor    pgtype.Numeric
	CreatedBy pgtype.UUID
}

// ─── Item Unit Conversions ────────────────────────────────────────────────────
func (q *Queries) CreateItemUnitConversion(ctx context.Context, arg CreateItemUnitConversionParams) (ItemUnitConversion, error) {
	row := q.db.QueryRow(ctx, createItemUnitConversion,
		arg.ItemCode,
		arg.FromUom,
		arg.ToUom,
		arg.Factor,
		arg.CreatedBy,
	)
	var i ItemUnitConversion
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.FromUom,
		&i.ToUom,
		&i.Factor,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteItemUnitConversion = `-- name: DeleteItemUnitConversion :exec
UPDATE item_unit_conversions SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeleteItemUnitConversion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItemUnitConversion, id)
	return err
}

const getItemUnitConversion = `-- name: GetItemUnitConversion :one
SELECT id, item_code, from_uom, to_uom, factor, is_active, created_at, created_by FROM item_unit_conversions
WHERE item_code = $1 AND from_uom = $2 AND to_uom = $3 AND is_active = TRUE
`

type GetItemUnitConversionParams struct {
	ItemCode int64
	FromUom  string
	ToUom    string
}

func (q *Queries) GetItemUnitConversion(ctx context.Context, arg GetItemUnitConversionParams) (ItemUnitConversion, error) {
	row := q.db.QueryRow(ctx, getItemUnitConversion, arg.ItemCode, arg.FromUom, arg.ToUom)
	var i ItemUnitConversion
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.FromUom,
		&i.ToUom,
		&i.Factor,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listItemUnitConversions = `-- name: ListItemUnitConversions :many
SELECT id, item_code, from_uom, to_uom, factor, is_active, created_at, created_by FROM item_unit_conversions
WHERE item_code = $1 AND is_active = TRUE
ORDER BY from_uom, to_uom
`

func (q *Queries) ListItemUnitConversions(ctx context.Context, itemCode int64) ([]ItemUnitConversion, error) {
	rows, err := q.db.Query(ctx, listItemUnitConversions, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemUnitConversion
	for rows.Next() {
		var i ItemUnitConversion
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.FromUom,
			&i.ToUom,
			&i.Factor,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
