// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    warehouse_code,
    code,
    complement,
    nature,
    situation,
    health,

    pdm_group_code,
    pdm_modifier_code,
    pdm_attributes,
    pdm_description_technique,

    warehouse_unit_of_measurement,
    warehouse_automatic_low,
    warehouse_cyclical_count_config,
    warehouse_minimum_stock,
    warehouse_avg_monthly_consumption_manual,

    engineering_item_base_code,
    engineering_weight,
    engineering_dimensions,
    engineering_type,
    engineering_type_struct,
    engineering_oem,

    planning_type_mrp,
    planning_llc,
    planning_reorder_point,
    planning_tank_code,
    planning_ghost,

    supplies_type_of_use,

    created_by,
    created_at
) VALUES (
             $1,  $2,  $3,  $4,
             $5,  $6,  $7,  $8,  $9,
             $10, $11, $12, $13, $14,
             $15, $16, $17, $18, $19,
             $20, $21, $22, $23, $24,
             $25, $26, $27, $28, NOW()
         )
    RETURNING id, warehouse_code, code, health, created_by, created_at, complement, nature, situation, pdm_group_code, pdm_modifier_code, pdm_attributes, pdm_description_technique, warehouse_unit_of_measurement, warehouse_automatic_low, warehouse_cyclical_count_config, warehouse_minimum_stock, warehouse_avg_monthly_consumption_manual, engineering_item_base_code, engineering_weight, engineering_dimensions, engineering_type, engineering_type_struct, engineering_oem, planning_type_mrp, planning_llc, planning_reorder_point, planning_tank_code, planning_ghost, planner_employee_code, supplies_type_of_use, production_reporting_type, material_issue_timing, accepts_fractional_quantity
`

type CreateItemParams struct {
	WarehouseCode                        int64
	Code                                 int64
	Complement                           pgtype.Text
	Nature                               int16
	Situation                            int16
	Health                               HealthEnum
	PdmGroupCode                         int64
	PdmModifierCode                      int64
	PdmAttributes                        []byte
	PdmDescriptionTechnique              string
	WarehouseUnitOfMeasurement           UnitOfMeasurementEnum
	WarehouseAutomaticLow                bool
	WarehouseCyclicalCountConfig         []byte
	WarehouseMinimumStock                int32
	WarehouseAvgMonthlyConsumptionManual *int32
	EngineeringItemBaseCode              *int64
	EngineeringWeight                    []byte
	EngineeringDimensions                []byte
	EngineeringType                      int16
	EngineeringTypeStruct                int16
	EngineeringOem                       bool
	PlanningTypeMrp                      int16
	PlanningLlc                          int32
	PlanningReorderPoint                 []byte
	PlanningTankCode                     *int64
	PlanningGhost                        bool
	SuppliesTypeOfUse                    int16
	CreatedBy                            pgtype.UUID
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.WarehouseCode,
		arg.Code,
		arg.Complement,
		arg.Nature,
		arg.Situation,
		arg.Health,
		arg.PdmGroupCode,
		arg.PdmModifierCode,
		arg.PdmAttributes,
		arg.PdmDescriptionTechnique,
		arg.WarehouseUnitOfMeasurement,
		arg.WarehouseAutomaticLow,
		arg.WarehouseCyclicalCountConfig,
		arg.WarehouseMinimumStock,
		arg.WarehouseAvgMonthlyConsumptionManual,
		arg.EngineeringItemBaseCode,
		arg.EngineeringWeight,
		arg.EngineeringDimensions,
		arg.EngineeringType,
		arg.EngineeringTypeStruct,
		arg.EngineeringOem,
		arg.PlanningTypeMrp,
		arg.PlanningLlc,
		arg.PlanningReorderPoint,
		arg.PlanningTankCode,
		arg.PlanningGhost,
		arg.SuppliesTypeOfUse,
		arg.CreatedBy,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.WarehouseCode,
		&i.Code,
		&i.Health,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Complement,
		&i.Nature,
		&i.Situation,
		&i.PdmGroupCode,
		&i.PdmModifierCode,
		&i.PdmAttributes,
		&i.PdmDescriptionTechnique,
		&i.WarehouseUnitOfMeasurement,
		&i.WarehouseAutomaticLow,
		&i.WarehouseCyclicalCountConfig,
		&i.WarehouseMinimumStock,
		&i.WarehouseAvgMonthlyConsumptionManual,
		&i.EngineeringItemBaseCode,
		&i.EngineeringWeight,
		&i.EngineeringDimensions,
		&i.EngineeringType,
		&i.EngineeringTypeStruct,
		&i.EngineeringOem,
		&i.PlanningTypeMrp,
		&i.PlanningLlc,
		&i.PlanningReorderPoint,
		&i.PlanningTankCode,
		&i.PlanningGhost,
		&i.PlannerEmployeeCode,
		&i.SuppliesTypeOfUse,
		&i.ProductionReportingType,
		&i.MaterialIssueTiming,
		&i.AcceptsFractionalQuantity,
	)
	return i, err
}

const findItemByCode = `-- name: FindItemByCode :one
SELECT id, warehouse_code, code, health, created_by, created_at, complement, nature, situation, pdm_group_code, pdm_modifier_code, pdm_attributes, pdm_description_technique, warehouse_unit_of_measurement, warehouse_automatic_low, warehouse_cyclical_count_config, warehouse_minimum_stock, warehouse_avg_monthly_consumption_manual, engineering_item_base_code, engineering_weight, engineering_dimensions, engineering_type, engineering_type_struct, engineering_oem, planning_type_mrp, planning_llc, planning_reorder_point, planning_tank_code, planning_ghost, planner_employee_code, supplies_type_of_use, production_reporting_type, material_issue_timing, accepts_fractional_quantity
FROM items
WHERE code = $1
`

func (q *Queries) FindItemByCode(ctx context.Context, code int64) (Item, error) {
	row := q.db.QueryRow(ctx, findItemByCode, code)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.WarehouseCode,
		&i.Code,
		&i.Health,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Complement,
		&i.Nature,
		&i.Situation,
		&i.PdmGroupCode,
		&i.PdmModifierCode,
		&i.PdmAttributes,
		&i.PdmDescriptionTechnique,
		&i.WarehouseUnitOfMeasurement,
		&i.WarehouseAutomaticLow,
		&i.WarehouseCyclicalCountConfig,
		&i.WarehouseMinimumStock,
		&i.WarehouseAvgMonthlyConsumptionManual,
		&i.EngineeringItemBaseCode,
		&i.EngineeringWeight,
		&i.EngineeringDimensions,
		&i.EngineeringType,
		&i.EngineeringTypeStruct,
		&i.EngineeringOem,
		&i.PlanningTypeMrp,
		&i.PlanningLlc,
		&i.PlanningReorderPoint,
		&i.PlanningTankCode,
		&i.PlanningGhost,
		&i.PlannerEmployeeCode,
		&i.SuppliesTypeOfUse,
		&i.ProductionReportingType,
		&i.MaterialIssueTiming,
		&i.AcceptsFractionalQuantity,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, warehouse_code, code, health, created_by, created_at, complement, nature, situation, pdm_group_code, pdm_modifier_code, pdm_attributes, pdm_description_technique, warehouse_unit_of_measurement, warehouse_automatic_low, warehouse_cyclical_count_config, warehouse_minimum_stock, warehouse_avg_monthly_consumption_manual, engineering_item_base_code, engineering_weight, engineering_dimensions, engineering_type, engineering_type_struct, engineering_oem, planning_type_mrp, planning_llc, planning_reorder_point, planning_tank_code, planning_ghost, planner_employee_code, supplies_type_of_use, production_reporting_type, material_issue_timing, accepts_fractional_quantity
FROM items
WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.WarehouseCode,
		&i.Code,
		&i.Health,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Complement,
		&i.Nature,
		&i.Situation,
		&i.PdmGroupCode,
		&i.PdmModifierCode,
		&i.PdmAttributes,
		&i.PdmDescriptionTechnique,
		&i.WarehouseUnitOfMeasurement,
		&i.WarehouseAutomaticLow,
		&i.WarehouseCyclicalCountConfig,
		&i.WarehouseMinimumStock,
		&i.WarehouseAvgMonthlyConsumptionManual,
		&i.EngineeringItemBaseCode,
		&i.EngineeringWeight,
		&i.EngineeringDimensions,
		&i.EngineeringType,
		&i.EngineeringTypeStruct,
		&i.EngineeringOem,
		&i.PlanningTypeMrp,
		&i.PlanningLlc,
		&i.PlanningReorderPoint,
		&i.PlanningTankCode,
		&i.PlanningGhost,
		&i.PlannerEmployeeCode,
		&i.SuppliesTypeOfUse,
		&i.ProductionReportingType,
		&i.MaterialIssueTiming,
		&i.AcceptsFractionalQuantity,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, warehouse_code, code, health, created_by, created_at, complement, nature, situation, pdm_group_code, pdm_modifier_code, pdm_attributes, pdm_description_technique, warehouse_unit_of_measurement, warehouse_automatic_low, warehouse_cyclical_count_config, warehouse_minimum_stock, warehouse_avg_monthly_consumption_manual, engineering_item_base_code, engineering_weight, engineering_dimensions, engineering_type, engineering_type_struct, engineering_oem, planning_type_mrp, planning_llc, planning_reorder_point, planning_tank_code, planning_ghost, planner_employee_code, supplies_type_of_use, production_reporting_type, material_issue_timing, accepts_fractional_quantity
FROM items
ORDER BY code
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseCode,
			&i.Code,
			&i.Health,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Complement,
			&i.Nature,
			&i.Situation,
			&i.PdmGroupCode,
			&i.PdmModifierCode,
			&i.PdmAttributes,
			&i.PdmDescriptionTechnique,
			&i.WarehouseUnitOfMeasurement,
			&i.WarehouseAutomaticLow,
			&i.WarehouseCyclicalCountConfig,
			&i.WarehouseMinimumStock,
			&i.WarehouseAvgMonthlyConsumptionManual,
			&i.EngineeringItemBaseCode,
			&i.EngineeringWeight,
			&i.EngineeringDimensions,
			&i.EngineeringType,
			&i.EngineeringTypeStruct,
			&i.EngineeringOem,
			&i.PlanningTypeMrp,
			&i.PlanningLlc,
			&i.PlanningReorderPoint,
			&i.PlanningTankCode,
			&i.PlanningGhost,
			&i.PlannerEmployeeCode,
			&i.SuppliesTypeOfUse,
			&i.ProductionReportingType,
			&i.MaterialIssueTiming,
			&i.AcceptsFractionalQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
