// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_conversion.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemUnitConversion = `-- name: CreateItemUnitConversion :one

INSERT INTO item_unit_conversions (item_code, mask, from_uom, to_uom, factor, rounding_percent, tolerance_value, tolerance_type, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (item_code, mask, from_uom, to_uom)
DO UPDATE SET factor = EXCLUDED.factor, rounding_percent=EXCLUDED.rounding_percent, tolerance_value=EXCLUDED.tolerance_value, tolerance_type=EXCLUDED.tolerance_type, is_active = TRUE
RETURNING id, item_code, from_uom, to_uom, factor, is_active, created_at, created_by, mask, rounding_percent, tolerance_value, tolerance_type
`

type CreateItemUnitConversionParams struct {
	ItemCode        int64
	Mask            string
	FromUom         string
	ToUom           string
	Factor          pgtype.Numeric
	RoundingPercent pgtype.Numeric
	ToleranceValue  pgtype.Numeric
	ToleranceType   string
	CreatedBy       pgtype.UUID
}

// ─── Item Unit Conversions ────────────────────────────────────────────────────
func (q *Queries) CreateItemUnitConversion(ctx context.Context, arg CreateItemUnitConversionParams) (ItemUnitConversion, error) {
	row := q.db.QueryRow(ctx, createItemUnitConversion,
		arg.ItemCode,
		arg.Mask,
		arg.FromUom,
		arg.ToUom,
		arg.Factor,
		arg.RoundingPercent,
		arg.ToleranceValue,
		arg.ToleranceType,
		arg.CreatedBy,
	)
	var i ItemUnitConversion
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.FromUom,
		&i.ToUom,
		&i.Factor,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Mask,
		&i.RoundingPercent,
		&i.ToleranceValue,
		&i.ToleranceType,
	)
	return i, err
}

const deleteItemUnitConversion = `-- name: DeleteItemUnitConversion :exec
UPDATE item_unit_conversions SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeleteItemUnitConversion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItemUnitConversion, id)
	return err
}

const getItemUnitConversion = `-- name: GetItemUnitConversion :one
SELECT id, item_code, from_uom, to_uom, factor, is_active, created_at, created_by, mask, rounding_percent, tolerance_value, tolerance_type FROM item_unit_conversions
WHERE item_code = $1 AND mask = $2 AND from_uom = $3 AND to_uom = $4 AND is_active = TRUE
`

type GetItemUnitConversionParams struct {
	ItemCode int64
	Mask     string
	FromUom  string
	ToUom    string
}

func (q *Queries) GetItemUnitConversion(ctx context.Context, arg GetItemUnitConversionParams) (ItemUnitConversion, error) {
	row := q.db.QueryRow(ctx, getItemUnitConversion,
		arg.ItemCode,
		arg.Mask,
		arg.FromUom,
		arg.ToUom,
	)
	var i ItemUnitConversion
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.FromUom,
		&i.ToUom,
		&i.Factor,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Mask,
		&i.RoundingPercent,
		&i.ToleranceValue,
		&i.ToleranceType,
	)
	return i, err
}

const listItemUnitConversions = `-- name: ListItemUnitConversions :many
SELECT id, item_code, from_uom, to_uom, factor, is_active, created_at, created_by, mask, rounding_percent, tolerance_value, tolerance_type FROM item_unit_conversions
WHERE item_code = $1 AND is_active = TRUE
ORDER BY mask, from_uom, to_uom
`

func (q *Queries) ListItemUnitConversions(ctx context.Context, itemCode int64) ([]ItemUnitConversion, error) {
	rows, err := q.db.Query(ctx, listItemUnitConversions, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemUnitConversion
	for rows.Next() {
		var i ItemUnitConversion
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.FromUom,
			&i.ToUom,
			&i.Factor,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Mask,
			&i.RoundingPercent,
			&i.ToleranceValue,
			&i.ToleranceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
