// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_supplier.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteItemPreferredSupplier = `-- name: DeleteItemPreferredSupplier :exec
UPDATE item_preferred_suppliers SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeleteItemPreferredSupplier(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItemPreferredSupplier, id)
	return err
}

const getPreferredSupplierForItem = `-- name: GetPreferredSupplierForItem :one
SELECT id, item_code, supplier_code, ranking, supplier_item_code, supplier_description, uom, lead_time_days, is_active, created_at, created_by FROM item_preferred_suppliers
WHERE item_code = $1 AND is_active = TRUE
ORDER BY ranking, supplier_code
LIMIT 1
`

func (q *Queries) GetPreferredSupplierForItem(ctx context.Context, itemCode int64) (ItemPreferredSupplier, error) {
	row := q.db.QueryRow(ctx, getPreferredSupplierForItem, itemCode)
	var i ItemPreferredSupplier
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.SupplierCode,
		&i.Ranking,
		&i.SupplierItemCode,
		&i.SupplierDescription,
		&i.Uom,
		&i.LeadTimeDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listItemPreferredSuppliers = `-- name: ListItemPreferredSuppliers :many
SELECT id, item_code, supplier_code, ranking, supplier_item_code, supplier_description, uom, lead_time_days, is_active, created_at, created_by FROM item_preferred_suppliers
WHERE item_code = $1 AND is_active = TRUE
ORDER BY ranking, supplier_code
`

func (q *Queries) ListItemPreferredSuppliers(ctx context.Context, itemCode int64) ([]ItemPreferredSupplier, error) {
	rows, err := q.db.Query(ctx, listItemPreferredSuppliers, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemPreferredSupplier
	for rows.Next() {
		var i ItemPreferredSupplier
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.SupplierCode,
			&i.Ranking,
			&i.SupplierItemCode,
			&i.SupplierDescription,
			&i.Uom,
			&i.LeadTimeDays,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItemPreferredSupplier = `-- name: UpsertItemPreferredSupplier :one

INSERT INTO item_preferred_suppliers (
    item_code, supplier_code, ranking, supplier_item_code, supplier_description, uom, lead_time_days, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (item_code, supplier_code) DO UPDATE SET
    ranking = EXCLUDED.ranking,
    supplier_item_code = EXCLUDED.supplier_item_code,
    supplier_description = EXCLUDED.supplier_description,
    uom = EXCLUDED.uom,
    lead_time_days = EXCLUDED.lead_time_days,
    is_active = TRUE
RETURNING id, item_code, supplier_code, ranking, supplier_item_code, supplier_description, uom, lead_time_days, is_active, created_at, created_by
`

type UpsertItemPreferredSupplierParams struct {
	ItemCode            int64
	SupplierCode        int64
	Ranking             int32
	SupplierItemCode    pgtype.Text
	SupplierDescription pgtype.Text
	Uom                 pgtype.Text
	LeadTimeDays        int32
	CreatedBy           pgtype.UUID
}

// ─── Item Preferred Suppliers ─────────────────────────────────────────────────
func (q *Queries) UpsertItemPreferredSupplier(ctx context.Context, arg UpsertItemPreferredSupplierParams) (ItemPreferredSupplier, error) {
	row := q.db.QueryRow(ctx, upsertItemPreferredSupplier,
		arg.ItemCode,
		arg.SupplierCode,
		arg.Ranking,
		arg.SupplierItemCode,
		arg.SupplierDescription,
		arg.Uom,
		arg.LeadTimeDays,
		arg.CreatedBy,
	)
	var i ItemPreferredSupplier
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.SupplierCode,
		&i.Ranking,
		&i.SupplierItemCode,
		&i.SupplierDescription,
		&i.Uom,
		&i.LeadTimeDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
