// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type WarehouseLocation string

const (
	WarehouseLocationLINHADEPRODUCAO WarehouseLocation = "LINHA_DE_PRODUCAO"
	WarehouseLocationNORMAL          WarehouseLocation = "NORMAL"
)

func (e *WarehouseLocation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WarehouseLocation(s)
	case string:
		*e = WarehouseLocation(s)
	default:
		return fmt.Errorf("unsupported scan type for WarehouseLocation: %T", src)
	}
	return nil
}

type NullWarehouseLocation struct {
	WarehouseLocation WarehouseLocation
	Valid             bool // Valid is true if WarehouseLocation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWarehouseLocation) Scan(value interface{}) error {
	if value == nil {
		ns.WarehouseLocation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WarehouseLocation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWarehouseLocation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WarehouseLocation), nil
}

type WarehouseType string

const (
	WarehouseTypeINTERNO     WarehouseType = "INTERNO"
	WarehouseTypeEXTERNO     WarehouseType = "EXTERNO"
	WarehouseTypeASSISTENCIA WarehouseType = "ASSISTENCIA"
	WarehouseTypeREJEICAO    WarehouseType = "REJEICAO"
	WarehouseTypeINSPECAO    WarehouseType = "INSPECAO"
	WarehouseTypeRESERVA     WarehouseType = "RESERVA"
	WarehouseTypeTRANSITO    WarehouseType = "TRANSITO"
	WarehouseTypeESPECIAL    WarehouseType = "ESPECIAL"
)

func (e *WarehouseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WarehouseType(s)
	case string:
		*e = WarehouseType(s)
	default:
		return fmt.Errorf("unsupported scan type for WarehouseType: %T", src)
	}
	return nil
}

type NullWarehouseType struct {
	WarehouseType WarehouseType
	Valid         bool // Valid is true if WarehouseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWarehouseType) Scan(value interface{}) error {
	if value == nil {
		ns.WarehouseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WarehouseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWarehouseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WarehouseType), nil
}


type CapacityPeriodEnum string

const (
	CapacityPeriodEnumMINUTO CapacityPeriodEnum = "MINUTO"
	CapacityPeriodEnumHORA   CapacityPeriodEnum = "HORA"
	CapacityPeriodEnumDIA    CapacityPeriodEnum = "DIA"
)

func (e *CapacityPeriodEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CapacityPeriodEnum(s)
	case string:
		*e = CapacityPeriodEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CapacityPeriodEnum: %T", src)
	}
	return nil
}

type NullCapacityPeriodEnum struct {
	CapacityPeriodEnum CapacityPeriodEnum
	Valid              bool // Valid is true if CapacityPeriodEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCapacityPeriodEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CapacityPeriodEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CapacityPeriodEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCapacityPeriodEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CapacityPeriodEnum), nil
}

type DemandTypeEnum string

const (
	DemandTypeEnumSALESORDER    DemandTypeEnum = "SALES_ORDER"
	DemandTypeEnumFORECAST      DemandTypeEnum = "FORECAST"
	DemandTypeEnumINDEPENDENT   DemandTypeEnum = "INDEPENDENT"
	DemandTypeEnumSAFETYSTOCK   DemandTypeEnum = "SAFETY_STOCK"
	DemandTypeEnumREPLENISHMENT DemandTypeEnum = "REPLENISHMENT"
)

func (e *DemandTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DemandTypeEnum(s)
	case string:
		*e = DemandTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DemandTypeEnum: %T", src)
	}
	return nil
}

type NullDemandTypeEnum struct {
	DemandTypeEnum DemandTypeEnum
	Valid          bool // Valid is true if DemandTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDemandTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DemandTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DemandTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDemandTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DemandTypeEnum), nil
}

type HealthEnum string

const (
	HealthEnumATIVO    HealthEnum = "ATIVO"
	HealthEnumINATIVO  HealthEnum = "INATIVO"
	HealthEnumFANTASMA HealthEnum = "FANTASMA"
)

func (e *HealthEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HealthEnum(s)
	case string:
		*e = HealthEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for HealthEnum: %T", src)
	}
	return nil
}

type NullHealthEnum struct {
	HealthEnum HealthEnum
	Valid      bool // Valid is true if HealthEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHealthEnum) Scan(value interface{}) error {
	if value == nil {
		ns.HealthEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HealthEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHealthEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HealthEnum), nil
}

type MachineCapacityUnitEnum string

const (
	MachineCapacityUnitEnumUN     MachineCapacityUnitEnum = "UN"
	MachineCapacityUnitEnumPEAS   MachineCapacityUnitEnum = "PEÇAS"
	MachineCapacityUnitEnumKG     MachineCapacityUnitEnum = "KG"
	MachineCapacityUnitEnumT      MachineCapacityUnitEnum = "T"
	MachineCapacityUnitEnumCHAPAS MachineCapacityUnitEnum = "CHAPAS"
	MachineCapacityUnitEnumM      MachineCapacityUnitEnum = "M"
	MachineCapacityUnitEnumM2     MachineCapacityUnitEnum = "M2"
	MachineCapacityUnitEnumM3     MachineCapacityUnitEnum = "M3"
	MachineCapacityUnitEnumLITROS MachineCapacityUnitEnum = "LITROS"
)

func (e *MachineCapacityUnitEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MachineCapacityUnitEnum(s)
	case string:
		*e = MachineCapacityUnitEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MachineCapacityUnitEnum: %T", src)
	}
	return nil
}

type NullMachineCapacityUnitEnum struct {
	MachineCapacityUnitEnum MachineCapacityUnitEnum
	Valid                   bool // Valid is true if MachineCapacityUnitEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMachineCapacityUnitEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MachineCapacityUnitEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MachineCapacityUnitEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMachineCapacityUnitEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MachineCapacityUnitEnum), nil
}

type MachineTypeEnum string

const (
	MachineTypeEnumCUT       MachineTypeEnum = "CUT"
	MachineTypeEnumBEND      MachineTypeEnum = "BEND"
	MachineTypeEnumWELD      MachineTypeEnum = "WELD"
	MachineTypeEnumASSEMBLE  MachineTypeEnum = "ASSEMBLE"
	MachineTypeEnumPAINT     MachineTypeEnum = "PAINT"
	MachineTypeEnumLATHE     MachineTypeEnum = "LATHE"
	MachineTypeEnumMILL      MachineTypeEnum = "MILL"
	MachineTypeEnumINJECTION MachineTypeEnum = "INJECTION"
	MachineTypeEnumPRESS     MachineTypeEnum = "PRESS"
)

func (e *MachineTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MachineTypeEnum(s)
	case string:
		*e = MachineTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MachineTypeEnum: %T", src)
	}
	return nil
}

type NullMachineTypeEnum struct {
	MachineTypeEnum MachineTypeEnum
	Valid           bool // Valid is true if MachineTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMachineTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MachineTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MachineTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMachineTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MachineTypeEnum), nil
}

type OrderStatusEnum string

const (
	OrderStatusEnumPLANNED    OrderStatusEnum = "PLANNED"
	OrderStatusEnumRELEASED   OrderStatusEnum = "RELEASED"
	OrderStatusEnumINPROGRESS OrderStatusEnum = "IN_PROGRESS"
	OrderStatusEnumFINISHED   OrderStatusEnum = "FINISHED"
	OrderStatusEnumCANCELLED  OrderStatusEnum = "CANCELLED"
)

func (e *OrderStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatusEnum(s)
	case string:
		*e = OrderStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatusEnum: %T", src)
	}
	return nil
}

type NullOrderStatusEnum struct {
	OrderStatusEnum OrderStatusEnum
	Valid           bool // Valid is true if OrderStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatusEnum), nil
}

type OrderTypeEnum string

const (
	OrderTypeEnumPRODUCTION          OrderTypeEnum = "PRODUCTION"
	OrderTypeEnumPURCHASE            OrderTypeEnum = "PURCHASE"
	OrderTypeEnumOUTSOURCING         OrderTypeEnum = "OUTSOURCING"
	OrderTypeEnumTECHNICALASSISTANCE OrderTypeEnum = "TECHNICAL_ASSISTANCE"
)

func (e *OrderTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderTypeEnum(s)
	case string:
		*e = OrderTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderTypeEnum: %T", src)
	}
	return nil
}

type NullOrderTypeEnum struct {
	OrderTypeEnum OrderTypeEnum
	Valid         bool // Valid is true if OrderTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OrderTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderTypeEnum), nil
}

type RestrictionConditionEnum string

const (
	RestrictionConditionEnumAND RestrictionConditionEnum = "AND"
	RestrictionConditionEnumOR  RestrictionConditionEnum = "OR"
)

func (e *RestrictionConditionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestrictionConditionEnum(s)
	case string:
		*e = RestrictionConditionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RestrictionConditionEnum: %T", src)
	}
	return nil
}

type NullRestrictionConditionEnum struct {
	RestrictionConditionEnum RestrictionConditionEnum
	Valid                    bool // Valid is true if RestrictionConditionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestrictionConditionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RestrictionConditionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestrictionConditionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestrictionConditionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestrictionConditionEnum), nil
}

type RestrictionOperatorEnum string

const (
	RestrictionOperatorEnumEQUAL      RestrictionOperatorEnum = "EQUAL"
	RestrictionOperatorEnumDIFFERENT  RestrictionOperatorEnum = "DIFFERENT"
	RestrictionOperatorEnumGREATER    RestrictionOperatorEnum = "GREATER"
	RestrictionOperatorEnumLESS       RestrictionOperatorEnum = "LESS"
	RestrictionOperatorEnumBELONGS    RestrictionOperatorEnum = "BELONGS"
	RestrictionOperatorEnumNOTBELONGS RestrictionOperatorEnum = "NOT_BELONGS"
	RestrictionOperatorEnumINVALID    RestrictionOperatorEnum = "INVALID"
)

func (e *RestrictionOperatorEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestrictionOperatorEnum(s)
	case string:
		*e = RestrictionOperatorEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RestrictionOperatorEnum: %T", src)
	}
	return nil
}

type NullRestrictionOperatorEnum struct {
	RestrictionOperatorEnum RestrictionOperatorEnum
	Valid                   bool // Valid is true if RestrictionOperatorEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestrictionOperatorEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RestrictionOperatorEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestrictionOperatorEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestrictionOperatorEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestrictionOperatorEnum), nil
}

type RestrictionSituationEnum string

const (
	RestrictionSituationEnumACTIVE   RestrictionSituationEnum = "ACTIVE"
	RestrictionSituationEnumINACTIVE RestrictionSituationEnum = "INACTIVE"
)

func (e *RestrictionSituationEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestrictionSituationEnum(s)
	case string:
		*e = RestrictionSituationEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RestrictionSituationEnum: %T", src)
	}
	return nil
}

type NullRestrictionSituationEnum struct {
	RestrictionSituationEnum RestrictionSituationEnum
	Valid                    bool // Valid is true if RestrictionSituationEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestrictionSituationEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RestrictionSituationEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestrictionSituationEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestrictionSituationEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestrictionSituationEnum), nil
}

type SalesDivisionAnalysisEnum string

const (
	SalesDivisionAnalysisEnumFREE          SalesDivisionAnalysisEnum = "FREE"
	SalesDivisionAnalysisEnumBLOCKALWAYS   SalesDivisionAnalysisEnum = "BLOCK_ALWAYS"
	SalesDivisionAnalysisEnumALWAYSANALYZE SalesDivisionAnalysisEnum = "ALWAYS_ANALYZE"
)

func (e *SalesDivisionAnalysisEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SalesDivisionAnalysisEnum(s)
	case string:
		*e = SalesDivisionAnalysisEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SalesDivisionAnalysisEnum: %T", src)
	}
	return nil
}

type NullSalesDivisionAnalysisEnum struct {
	SalesDivisionAnalysisEnum SalesDivisionAnalysisEnum
	Valid                     bool // Valid is true if SalesDivisionAnalysisEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSalesDivisionAnalysisEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SalesDivisionAnalysisEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SalesDivisionAnalysisEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSalesDivisionAnalysisEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SalesDivisionAnalysisEnum), nil
}

type SituationEnum string

const (
	SituationEnumACTIVE   SituationEnum = "ACTIVE"
	SituationEnumINACTIVE SituationEnum = "INACTIVE"
)

func (e *SituationEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SituationEnum(s)
	case string:
		*e = SituationEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SituationEnum: %T", src)
	}
	return nil
}

type NullSituationEnum struct {
	SituationEnum SituationEnum
	Valid         bool // Valid is true if SituationEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSituationEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SituationEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SituationEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSituationEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SituationEnum), nil
}

type TypeCcEnum string

const (
	TypeCcEnumAUXILIARY      TypeCcEnum = "AUXILIARY"
	TypeCcEnumPRODUCTIVE     TypeCcEnum = "PRODUCTIVE"
	TypeCcEnumADMINISTRATIVE TypeCcEnum = "ADMINISTRATIVE"
	TypeCcEnumCOMMERCIAL     TypeCcEnum = "COMMERCIAL"
)

func (e *TypeCcEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeCcEnum(s)
	case string:
		*e = TypeCcEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeCcEnum: %T", src)
	}
	return nil
}

type NullTypeCcEnum struct {
	TypeCcEnum TypeCcEnum
	Valid      bool // Valid is true if TypeCcEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeCcEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeCcEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeCcEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeCcEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeCcEnum), nil
}

type TypeItemEnum string

const (
	TypeItemEnumRAWMATERIAL  TypeItemEnum = "RAW_MATERIAL"
	TypeItemEnumSEMIFINISHED TypeItemEnum = "SEMI_FINISHED"
	TypeItemEnumFINISHED     TypeItemEnum = "FINISHED"
	TypeItemEnumPACKAGING    TypeItemEnum = "PACKAGING"
	TypeItemEnumSERVICE      TypeItemEnum = "SERVICE"
	TypeItemEnumCOMPONENT    TypeItemEnum = "COMPONENT"
)

func (e *TypeItemEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeItemEnum(s)
	case string:
		*e = TypeItemEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeItemEnum: %T", src)
	}
	return nil
}

type NullTypeItemEnum struct {
	TypeItemEnum TypeItemEnum
	Valid        bool // Valid is true if TypeItemEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeItemEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeItemEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeItemEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeItemEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeItemEnum), nil
}

type TypeMrpEnum string

const (
	TypeMrpEnumMRP          TypeMrpEnum = "MRP"
	TypeMrpEnumMINMAX       TypeMrpEnum = "MIN_MAX"
	TypeMrpEnumREORDERPOINT TypeMrpEnum = "REORDER_POINT"
	TypeMrpEnumMPS          TypeMrpEnum = "MPS"
	TypeMrpEnumKANBAN       TypeMrpEnum = "KANBAN"
)

func (e *TypeMrpEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeMrpEnum(s)
	case string:
		*e = TypeMrpEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeMrpEnum: %T", src)
	}
	return nil
}

type NullTypeMrpEnum struct {
	TypeMrpEnum TypeMrpEnum
	Valid       bool // Valid is true if TypeMrpEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeMrpEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeMrpEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeMrpEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeMrpEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeMrpEnum), nil
}

type TypeOfUseItemEnum string

const (
	TypeOfUseItemEnumPURCHASE    TypeOfUseItemEnum = "PURCHASE"
	TypeOfUseItemEnumPRODUCTION  TypeOfUseItemEnum = "PRODUCTION"
	TypeOfUseItemEnumOUTSOURCING TypeOfUseItemEnum = "OUTSOURCING"
	TypeOfUseItemEnumCONSUMPTION TypeOfUseItemEnum = "CONSUMPTION"
)

func (e *TypeOfUseItemEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeOfUseItemEnum(s)
	case string:
		*e = TypeOfUseItemEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeOfUseItemEnum: %T", src)
	}
	return nil
}

type NullTypeOfUseItemEnum struct {
	TypeOfUseItemEnum TypeOfUseItemEnum
	Valid             bool // Valid is true if TypeOfUseItemEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeOfUseItemEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeOfUseItemEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeOfUseItemEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeOfUseItemEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeOfUseItemEnum), nil
}

type TypeSituationEnum string

const (
	TypeSituationEnumACTIVE   TypeSituationEnum = "ACTIVE"
	TypeSituationEnumINACTIVE TypeSituationEnum = "INACTIVE"
	TypeSituationEnumPENDING  TypeSituationEnum = "PENDING"
)

func (e *TypeSituationEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeSituationEnum(s)
	case string:
		*e = TypeSituationEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeSituationEnum: %T", src)
	}
	return nil
}

type NullTypeSituationEnum struct {
	TypeSituationEnum TypeSituationEnum
	Valid             bool // Valid is true if TypeSituationEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeSituationEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeSituationEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeSituationEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeSituationEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeSituationEnum), nil
}

type TypeSituationItemEnum string

const (
	TypeSituationItemEnumACTIVE   TypeSituationItemEnum = "ACTIVE"
	TypeSituationItemEnumINACTIVE TypeSituationItemEnum = "INACTIVE"
	TypeSituationItemEnumBLOCKED  TypeSituationItemEnum = "BLOCKED"
)

func (e *TypeSituationItemEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeSituationItemEnum(s)
	case string:
		*e = TypeSituationItemEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeSituationItemEnum: %T", src)
	}
	return nil
}

type NullTypeSituationItemEnum struct {
	TypeSituationItemEnum TypeSituationItemEnum
	Valid                 bool // Valid is true if TypeSituationItemEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeSituationItemEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeSituationItemEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeSituationItemEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeSituationItemEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeSituationItemEnum), nil
}

type TypeStructItemEnum string

const (
	TypeStructItemEnumPHANTOM TypeStructItemEnum = "PHANTOM"
	TypeStructItemEnumREAL    TypeStructItemEnum = "REAL"
)

func (e *TypeStructItemEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeStructItemEnum(s)
	case string:
		*e = TypeStructItemEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeStructItemEnum: %T", src)
	}
	return nil
}

type NullTypeStructItemEnum struct {
	TypeStructItemEnum TypeStructItemEnum
	Valid              bool // Valid is true if TypeStructItemEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeStructItemEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeStructItemEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeStructItemEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeStructItemEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeStructItemEnum), nil
}

type UnitOfMeasurementEnum string

const (
	UnitOfMeasurementEnumMM         UnitOfMeasurementEnum = "MM"
	UnitOfMeasurementEnumCM         UnitOfMeasurementEnum = "CM"
	UnitOfMeasurementEnumM          UnitOfMeasurementEnum = "M"
	UnitOfMeasurementEnumIN         UnitOfMeasurementEnum = "IN"
	UnitOfMeasurementEnumKG         UnitOfMeasurementEnum = "KG"
	UnitOfMeasurementEnumM2         UnitOfMeasurementEnum = "M2"
	UnitOfMeasurementEnumM3         UnitOfMeasurementEnum = "M3"
	UnitOfMeasurementEnumUN         UnitOfMeasurementEnum = "UN"
	UnitOfMeasurementEnumMICROMETRO UnitOfMeasurementEnum = "MICROMETRO"
	UnitOfMeasurementEnumTONELADA   UnitOfMeasurementEnum = "TONELADA"
)

func (e *UnitOfMeasurementEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitOfMeasurementEnum(s)
	case string:
		*e = UnitOfMeasurementEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitOfMeasurementEnum: %T", src)
	}
	return nil
}

type NullUnitOfMeasurementEnum struct {
	UnitOfMeasurementEnum UnitOfMeasurementEnum
	Valid                 bool // Valid is true if UnitOfMeasurementEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitOfMeasurementEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UnitOfMeasurementEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitOfMeasurementEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitOfMeasurementEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitOfMeasurementEnum), nil
}

type AllocationBaseItem struct {
	ID                 int64
	Amount             float64
	Percentage         float64
	CreatedAt          pgtype.Timestamptz
	AllocationBaseCode int32
	CostCenterCode     int32
}

type AllocationBasis struct {
	ID          int64
	Code        int32
	Description string
	Period      string
	Observation pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

type AppropriationTable struct {
	ID           int64
	Description  string
	MondayPct    pgtype.Numeric
	TuesdayPct   pgtype.Numeric
	WednesdayPct pgtype.Numeric
	ThursdayPct  pgtype.Numeric
	FridayPct    pgtype.Numeric
	SaturdayPct  pgtype.Numeric
	SundayPct    pgtype.Numeric
	IsDefault    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
}

type Bom struct {
	ID        int64
	ProductID int64
	BomType   string
	Version   int32
	Status    string
	ValidFrom pgtype.Date
	CreatedAt pgtype.Timestamp
	Mask      int64
}

type BomItem struct {
	ID            int64
	BomID         int64
	ComponentID   int64
	Quantity      pgtype.Numeric
	Uom           pgtype.Text
	ScrapPercent  pgtype.Numeric
	OperationID   int64
	CreatedAt     pgtype.Timestamp
	MaskComponent int64
}

type ComplementA struct {
	ID    int64
	Value string
}

type ComplementB struct {
	ID    int64
	Value string
}

type Component struct {
	ID        int64
	Code      string
	Warehouse *int64
	GroupCode string
	Name      string
	Type      interface{}
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ComponentMask struct {
	ID          int64
	ComponentID int64
	Mask        string
	MaskHash    string
	BusinessID  string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type ConfiguredItemRule struct {
	ID        int64
	ItemCode  int64
	TableType string
	FieldName string
	RuleType  string
	RuleValue string
	Sequence  int32
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	Code      pgtype.Int8
}

type CostCenter struct {
	ID          int64
	Code        int32
	Description string
	ParentCode  *int32
	Type        TypeCcEnum
	IsRatio     bool
	StartDate   pgtype.Date
	EndDate     *time.Time
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

type DeliveryPromiseParam struct {
	ID                      int64
	UseDeliveryPromise      bool
	BlockedOrdersInPromise  bool
	DefaultOrderSort        string
	ShowOrderValues         int32
	BlockedExportInPromise  bool
	BreakTankOccupation     bool
	RecalculateAfterRelease bool
	ReprogramLoadedOrders   bool
	AllowDeliveryDateChange bool
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	UpdatedBy               pgtype.UUID
}

type DeliveryReschedule struct {
	ID             int64
	Code           int64
	SalesOrderCode int64
	ItemCode       int64
	OldDate        pgtype.Date
	NewDate        pgtype.Date
	Reason         pgtype.Text
	CreatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
}

type Employee struct {
	ID           int64
	EnterpriseID int32
	Code         int32
	Description  pgtype.Text
	Name         string
	CreatedAt    pgtype.Timestamptz
}

type Enterprise struct {
	ID        int64
	Code      int32
	Name      string
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

type Group struct {
	ID           int64
	Code         int32
	Description  string
	EnterpriseID int64
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type IndependentDemand struct {
	ID             int64
	Code           int64
	ItemCode       int64
	Mask           pgtype.Text
	CostCenterCode pgtype.Int8
	Quantity       pgtype.Numeric
	DemandDate     pgtype.Date
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
}

type IndustrialCalendar struct {
	ID          int64
	Year        int32
	Month       int32
	Day         int32
	IsWorkday   bool
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Item struct {
	ID                                   int64
	WarehouseCode                        int64
	Code                                 int64
	Health                               HealthEnum
	CreatedBy                            pgtype.UUID
	CreatedAt                            pgtype.Timestamp
	Complement                           pgtype.Text
	Nature                               int16
	Situation                            int16
	PdmGroupCode                         int64
	PdmModifierCode                      int64
	PdmAttributes                        []byte
	PdmDescriptionTechnique              string
	WarehouseUnitOfMeasurement           UnitOfMeasurementEnum
	WarehouseAutomaticLow                bool
	WarehouseCyclicalCountConfig         []byte
	WarehouseMinimumStock                int32
	WarehouseAvgMonthlyConsumptionManual *int32
	EngineeringItemBaseCode              *int64
	EngineeringWeight                    []byte
	EngineeringDimensions                []byte
	EngineeringType                      int16
	EngineeringTypeStruct                int16
	EngineeringOem                       bool
	PlanningTypeMrp                      int16
	PlanningLlc                          int32
	PlanningReorderPoint                 []byte
	PlanningTankCode                     *int64
	PlanningGhost                        bool
	PlannerEmployeeCode                  *int64
	SuppliesTypeOfUse                    int16
	Inherit                              bool
}

type ItemCalendarPromise struct {
	ID          int64
	ItemCode    int64
	Mask        string
	Year        int32
	Month       int32
	Day         int32
	IsWorkday   bool
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ItemMachineTime struct {
	ID                 int64
	ItemCode           int64
	Mask               string
	ProductionTime     pgtype.Numeric
	SetupTime          pgtype.Numeric
	Priority           int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	MachineCode        int64
	ProductionTimeUnit CapacityPeriodEnum
	ProductionBaseQty  int32
}

type ItemMask struct {
	ID        int64
	ItemCode  int64
	Mask      string
	MaskHash  string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ItemMaskAnswer struct {
	ID         int64
	QuestionID int64
	OptionID   int64
	Position   int32
	MaskID     int64
}

type ItemQuestion struct {
	ItemCode   int64
	QuestionID int64
	Position   int32
	CreatedAt  pgtype.Timestamptz
}

type ItemQuestionAnswer struct {
	ID         int64
	ItemID     int64
	QuestionID int64
	Answer     string
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type ItemStructure struct {
	ID                int64
	ParentMask        pgtype.Text
	Quantity          float64
	UnitOfMeasurement UnitOfMeasurementEnum
	LossPercentage    float64
	Sequence          int32
	Notes             pgtype.Text
	IsActive          bool
	CreatedBy         pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ParentCode        int64
	ChildCode         int64
	Health            HealthEnum
}

type Machine struct {
	ID              int64
	Code            int64
	Name            string
	Capacity        pgtype.Numeric
	EfficiencyRate  pgtype.Numeric
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	MachineTypeCode int64
	CostCenterCode  *int64
	CapacityUnit    MachineCapacityUnitEnum
	CapacityPeriod  CapacityPeriodEnum
}

type MachineSchedule struct {
	ID               int64
	ScheduleDate     pgtype.Date
	StartTime        pgtype.Time
	EndTime          pgtype.Time
	PlannedQty       pgtype.Numeric
	ProducedQty      pgtype.Numeric
	Status           string
	Sequence         int32
	PriorityOverride *int32
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	MachineCode      int64
	OrderCode        int64
	Code             int64
}

type MachineType struct {
	ID          int64
	Code        int64
	Name        string
	Description pgtype.Text
	Type        MachineTypeEnum
	SetupTime   pgtype.Numeric
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

type MaskComposition struct {
	ParentMaskID int64
	ChildMaskID  int64
	Quantity     pgtype.Numeric
}

type MaterialConsumption struct {
	ComponentMaskID int64
	MaterialID      int64
	Quantity        pgtype.Numeric
	Unit            string
}

type Modifier struct {
	ID          int64
	Description string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type MrpCalculationLog struct {
	ID          int64
	PlanCode    int64
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	Status      string
	Errors      []byte
	TotalItems  int32
	TotalOrders int32
	CreatedAt   pgtype.Timestamptz
	Code        pgtype.Int8
}

type MrpExceptionMessage struct {
	Code        int64
	PlanCode    int64
	ItemCode    int64
	MessageType string
	SourceCode  *int64
	SourceType  pgtype.Text
	Description string
	CreatedAt   pgtype.Timestamptz
}

type MrpItemProfile struct {
	ID              int64
	ItemCode        int64
	PlanCode        int64
	CalculationDate pgtype.Date
	Demand          pgtype.Numeric
	OrdersPlanned   pgtype.Numeric
	OrdersFirm      pgtype.Numeric
	StockProjected  pgtype.Numeric
	Llc             int32
	NeedDate        pgtype.Date
	CreatedAt       pgtype.Timestamptz
	Code            pgtype.Int8
}

type MrpParameter struct {
	ProductID    int64
	PlanningType string
	LeadTimeDays int32
	SafetyStock  pgtype.Numeric
}

type MrpPlannedSuggestion struct {
	Code           int64
	PlanCode       int64
	ItemCode       int64
	Quantity       pgtype.Numeric
	NeedDate       pgtype.Date
	StartDate      pgtype.Date
	OrderType      string
	DemandType     string
	ParentItemCode *int64
	Llc            int32
	CreatedAt      pgtype.Timestamptz
}

type Operation struct {
	ID   int64
	Code string
	Name string
}

type OrderPriority struct {
	ID            int64
	IntervalStart pgtype.Numeric
	IntervalEnd   pgtype.Numeric
	Priority      string
	Description   pgtype.Text
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	Code          int64
}

type OverheadAllocation struct {
	ID              int64
	CostCenterID    int64
	PlanAccountID   *int64
	AccountCode     pgtype.Text
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	AllocationType  string
	BaseID          *int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	Code            int64
	CostCenterCode  *int32
	PlanAccountCode *int32
	BaseCode        *int64
}

type OverheadAllocationTarget struct {
	ID             int64
	OverheadID     int64
	CostCenterID   int64
	Percentage     pgtype.Numeric
	Amount         pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	Code           int64
	OverheadCode   *int64
	CostCenterCode *int32
}

type PlannedOrder struct {
	ID                int64
	OrderNumber       int64
	ItemCode          int64
	Mask              string
	Quantity          pgtype.Numeric
	QuantityLoss      pgtype.Numeric
	QuantityCorrected pgtype.Numeric
	OrderType         OrderTypeEnum
	Status            OrderStatusEnum
	DemandType        DemandTypeEnum
	DemandID          *int64
	NeedDate          pgtype.Date
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	ProductionTime    pgtype.Numeric
	Priority          pgtype.Text
	Llc               int32
	Notes             pgtype.Text
	IsFirm            bool
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	Code              int64
	MachineCode       *int64
	CostCenterCode    *int64
	EmployeeCode      *int64
	ParentOrderCode   *int64
	PlanCode          *int64
	DemandCode        int32
	SalesOrderCode    *int64
}

type PlanningParam struct {
	ID          int64
	ParamNumber int32
	ParamKey    string
	Value       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   pgtype.UUID
}

type Product struct {
	ID        int64
	Code      string
	GroupCode pgtype.Text
	Name      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ProductionOrder struct {
	ID                 int64
	ProductID          int64
	BomID              int64
	Quantity           pgtype.Numeric
	Status             string
	CurrentOperationID *int64
	CreatedAt          pgtype.Timestamp
}

type ProductionPlan struct {
	ID                  int64
	Code                int64
	Name                string
	IndependentDemands  string
	GroupSameDateOrders bool
	PlanningTypes       []string
	Classification      pgtype.Text
	ClassItemCodes      pgtype.Text
	OrderItemCode       *int64
	LastCalculatedAt    pgtype.Timestamptz
	Parameters          []byte
	IsActive            bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
}

type Question struct {
	ID        int64
	Name      string
	Createdby pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type QuestionOption struct {
	ID         int64
	QuestionID int64
	Value      string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
}

type Restriction struct {
	ID                   int64
	Code                 pgtype.Int8
	Situation            RestrictionSituationEnum
	ItemCode             *int64
	ReasonCode           *int64
	ClassificationType   pgtype.Text
	ClassificationOrigin pgtype.Text
	DivisionID           *int64
	Weight               int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            pgtype.UUID
}

type RestrictionDeterminant struct {
	ID            int64
	RestrictionID int64
	QuestionID    int64
	Operator      RestrictionOperatorEnum
	AnswerValue   pgtype.Text
}

type RestrictionDominant struct {
	ID            int64
	RestrictionID int64
	QuestionID    int64
	Operator      RestrictionOperatorEnum
	ConditionType RestrictionConditionEnum
	AnswerValue   string
	Sequence      int32
}

type SalesDivision struct {
	ID                      int64
	Code                    int64
	Description             string
	CommercialAnalysis      SalesDivisionAnalysisEnum
	FinancialAnalysis       SalesDivisionAnalysisEnum
	IsTechnicalAssistance   bool
	ConsiderDeliveryPromise bool
	ConsiderMrp             bool
	AllowOutsideLimits      bool
	MinimumDeliveryDays     int32
	FinancialDelayDays      int32
	PisPercentage           pgtype.Numeric
	CofinsPercentage        pgtype.Numeric
	ParentDivisionID        *int64
	IsActive                bool
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	CreatedBy               pgtype.UUID
}

type SalesForecast struct {
	ID        int64
	ItemCode  int64
	Mask      pgtype.Text
	Week      int32
	Year      int32
	Quantity  pgtype.Numeric
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SalesForecastBlock struct {
	ID        int64
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Reason    pgtype.Text
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

type SalesOrderDemand struct {
	ID             int64
	SalesOrderCode int64
	ItemCode       int64
	Mask           string
	Quantity       pgtype.Numeric
	DeliveredQty   pgtype.Numeric
	DeliveryDate   pgtype.Date
	DivisionCode   *int64
	Status         string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Code           pgtype.Int8
}

type Stock struct {
	ProductID int64
	Quantity  pgtype.Numeric
}

type StockMovement struct {
	ID            int64
	ProductID     int64
	MovementType  string
	Quantity      pgtype.Numeric
	ReferenceType pgtype.Text
	ReferenceID   *int64
	CreatedAt     pgtype.Timestamp
}

type StockSnapshot struct {
	ID            int64
	ItemCode      int64
	WarehouseCode int64
	Quantity      pgtype.Numeric
	ReservedQty   pgtype.Numeric
	SafetyStock   pgtype.Numeric
	SnapshotDate  pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}


type Warehouse struct {
	ID                  int64
	Code                string
	Description         string
	CreatedAt           pgtype.Timestamp
	CreatedBy           pgtype.UUID
	Location            WarehouseLocation
	Type                WarehouseType
	Disposition         bool
	ReservationsAllowed bool
}