// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modifier.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModifier = `-- name: CreateModifier :one
INSERT INTO modifier (
    description,
    enterprise_id,
    created_by
) VALUES (
$1, $2, $3
)
RETURNING id, description, created_by, created_at, enterprise_id
`

type CreateModifierParams struct {
	Description  string
	EnterpriseID int64
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateModifier(ctx context.Context, arg CreateModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, createModifier, arg.Description, arg.EnterpriseID, arg.CreatedBy)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EnterpriseID,
	)
	return i, err
}

const getModifierByID = `-- name: GetModifierByID :one
SELECT id, description, created_by, created_at, enterprise_id FROM modifier WHERE enterprise_id = $1 AND id = $2
`

type GetModifierByIDParams struct {
	EnterpriseID int64
	ID           int64
}

func (q *Queries) GetModifierByID(ctx context.Context, arg GetModifierByIDParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, getModifierByID, arg.EnterpriseID, arg.ID)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EnterpriseID,
	)
	return i, err
}

const listModifiers = `-- name: ListModifiers :many
SELECT id, description, created_by, created_at, enterprise_id FROM modifier WHERE enterprise_id = $1 ORDER BY id
`

func (q *Queries) ListModifiers(ctx context.Context, enterpriseID int64) ([]Modifier, error) {
	rows, err := q.db.Query(ctx, listModifiers, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modifier
	for rows.Next() {
		var i Modifier
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EnterpriseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModifier = `-- name: UpdateModifier :one
UPDATE modifier
SET description = $3
WHERE enterprise_id = $1 AND id = $2
RETURNING id, description, created_by, created_at, enterprise_id
`

type UpdateModifierParams struct {
	EnterpriseID int64
	ID           int64
	Description  string
}

func (q *Queries) UpdateModifier(ctx context.Context, arg UpdateModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, updateModifier, arg.EnterpriseID, arg.ID, arg.Description)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EnterpriseID,
	)
	return i, err
}
