// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mrp_demand_sources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOpenSalesOrderDemands = `-- name: ListOpenSalesOrderDemands :many
SELECT
    soi.item_code,
    soi.mask,
    GREATEST(soi.requested_qty - soi.attended_qty - soi.cancelled_qty, 0)::numeric AS quantity,
    COALESCE(soi.delivery_date, so.delivery_date, CURRENT_DATE)::date AS need_date,
    soi.code AS source_code,
    soi.warehouse_code,
    COALESCE(sd.is_technical_assistance, FALSE)::boolean AS technical_assistance,
    (e.id <> $1)::boolean AS inter_factory,
    COALESCE(CASE WHEN e.id <> $1 THEN e.code END, 0)::bigint AS source_enterprise_code,
    CASE WHEN e.id <> $1 THEN COALESCE(pif.auto_release, FALSE) ELSE FALSE END::boolean AS auto_release
FROM sales_order_items soi
JOIN sales_orders so ON so.code = soi.sales_order_code
JOIN enterprise e ON e.code = so.enterprise_code
LEFT JOIN sales_divisions sd ON sd.id = so.sales_division_code AND sd.is_active = TRUE
LEFT JOIN production_plan_inter_factories pif
  ON pif.plan_code = $2
 AND pif.enterprise_id = $1
 AND pif.source_enterprise_id = e.id
WHERE (e.id = $1 OR (so.origin = 'INTER_FACTORY' AND pif.source_enterprise_id IS NOT NULL))
  AND so.is_active = TRUE
  AND so.is_blocked = FALSE
  AND so.status NOT IN ('F', 'CANCELLED')
  AND soi.is_active = TRUE
  AND soi.status IN ('OPEN', 'PARTIAL')
  AND soi.requested_qty > soi.attended_qty + soi.cancelled_qty
  AND ($3::bigint IS NULL OR soi.code = $3)
ORDER BY need_date, soi.code
`

type ListOpenSalesOrderDemandsParams struct {
	EnterpriseID       int64
	PlanCode           int64
	SalesOrderItemCode *int64
}

type ListOpenSalesOrderDemandsRow struct {
	ItemCode             int64
	Mask                 string
	Quantity             pgtype.Numeric
	NeedDate             pgtype.Date
	SourceCode           int64
	WarehouseCode        *int64
	TechnicalAssistance  bool
	InterFactory         bool
	SourceEnterpriseCode int64
	AutoRelease          bool
}

func (q *Queries) ListOpenSalesOrderDemands(ctx context.Context, arg ListOpenSalesOrderDemandsParams) ([]ListOpenSalesOrderDemandsRow, error) {
	rows, err := q.db.Query(ctx, listOpenSalesOrderDemands, arg.EnterpriseID, arg.PlanCode, arg.SalesOrderItemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenSalesOrderDemandsRow
	for rows.Next() {
		var i ListOpenSalesOrderDemandsRow
		if err := rows.Scan(
			&i.ItemCode,
			&i.Mask,
			&i.Quantity,
			&i.NeedDate,
			&i.SourceCode,
			&i.WarehouseCode,
			&i.TechnicalAssistance,
			&i.InterFactory,
			&i.SourceEnterpriseCode,
			&i.AutoRelease,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveClassificationItemCodes = `-- name: ResolveClassificationItemCodes :many
WITH RECURSIVE selected AS (
    SELECT classification.id
    FROM item_classifications classification
    JOIN item_classification_masks mask ON mask.id = classification.mask_id
    WHERE mask.code::text = $2::text
      AND classification.code = ANY($3::text[])
      AND classification.is_active = TRUE
    UNION ALL
    SELECT child.id
    FROM item_classifications child
    JOIN selected parent ON child.parent_id = parent.id
    WHERE child.is_active = TRUE
)
SELECT DISTINCT assignment.item_code
FROM item_classification_assignments assignment
JOIN selected ON selected.id = assignment.classification_id
WHERE assignment.enterprise_id = $1
ORDER BY assignment.item_code
`

type ResolveClassificationItemCodesParams struct {
	EnterpriseID   int64
	Classification string
	ClassCodes     []string
}

func (q *Queries) ResolveClassificationItemCodes(ctx context.Context, arg ResolveClassificationItemCodesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, resolveClassificationItemCodes, arg.EnterpriseID, arg.Classification, arg.ClassCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var item_code int64
		if err := rows.Scan(&item_code); err != nil {
			return nil, err
		}
		items = append(items, item_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
