// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mrp_calculation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConfiguredItemRule = `-- name: CreateConfiguredItemRule :one
INSERT INTO configured_item_rules (item_code, table_type, field_name, rule_type, rule_value, sequence, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, item_code, table_type, field_name, rule_type, rule_value, sequence, is_active, created_at, updated_at, created_by, code
`

type CreateConfiguredItemRuleParams struct {
	ItemCode  int64
	TableType string
	FieldName string
	RuleType  string
	RuleValue string
	Sequence  int32
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateConfiguredItemRule(ctx context.Context, arg CreateConfiguredItemRuleParams) (ConfiguredItemRule, error) {
	row := q.db.QueryRow(ctx, createConfiguredItemRule,
		arg.ItemCode,
		arg.TableType,
		arg.FieldName,
		arg.RuleType,
		arg.RuleValue,
		arg.Sequence,
		arg.CreatedBy,
	)
	var i ConfiguredItemRule
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.TableType,
		&i.FieldName,
		&i.RuleType,
		&i.RuleValue,
		&i.Sequence,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
	)
	return i, err
}

const createMRPItemProfile = `-- name: CreateMRPItemProfile :one
INSERT INTO mrp_item_profiles (item_code, plan_code, calculation_date, demand, orders_planned, orders_firm, stock_projected, llc, need_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING id, item_code, plan_code, calculation_date, demand, orders_planned, orders_firm, stock_projected, llc, need_date, created_at, code
`

type CreateMRPItemProfileParams struct {
	ItemCode        int64
	PlanCode        int64
	CalculationDate pgtype.Date
	Demand          pgtype.Numeric
	OrdersPlanned   pgtype.Numeric
	OrdersFirm      pgtype.Numeric
	StockProjected  pgtype.Numeric
	Llc             int32
	NeedDate        pgtype.Date
}

func (q *Queries) CreateMRPItemProfile(ctx context.Context, arg CreateMRPItemProfileParams) (MrpItemProfile, error) {
	row := q.db.QueryRow(ctx, createMRPItemProfile,
		arg.ItemCode,
		arg.PlanCode,
		arg.CalculationDate,
		arg.Demand,
		arg.OrdersPlanned,
		arg.OrdersFirm,
		arg.StockProjected,
		arg.Llc,
		arg.NeedDate,
	)
	var i MrpItemProfile
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.PlanCode,
		&i.CalculationDate,
		&i.Demand,
		&i.OrdersPlanned,
		&i.OrdersFirm,
		&i.StockProjected,
		&i.Llc,
		&i.NeedDate,
		&i.CreatedAt,
		&i.Code,
	)
	return i, err
}

const createMRPPlannedSuggestion = `-- name: CreateMRPPlannedSuggestion :one
INSERT INTO mrp_planned_suggestions (plan_code, item_code, quantity, need_date, start_date, order_type, demand_type, parent_item_code, llc)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING code, plan_code, item_code, quantity, need_date, start_date, order_type, demand_type, parent_item_code, llc, created_at
`

type CreateMRPPlannedSuggestionParams struct {
	PlanCode       int64
	ItemCode       int64
	Quantity       pgtype.Numeric
	NeedDate       pgtype.Date
	StartDate      pgtype.Date
	OrderType      string
	DemandType     string
	ParentItemCode *int64
	Llc            int32
}

func (q *Queries) CreateMRPPlannedSuggestion(ctx context.Context, arg CreateMRPPlannedSuggestionParams) (MrpPlannedSuggestion, error) {
	row := q.db.QueryRow(ctx, createMRPPlannedSuggestion,
		arg.PlanCode,
		arg.ItemCode,
		arg.Quantity,
		arg.NeedDate,
		arg.StartDate,
		arg.OrderType,
		arg.DemandType,
		arg.ParentItemCode,
		arg.Llc,
	)
	var i MrpPlannedSuggestion
	err := row.Scan(
		&i.Code,
		&i.PlanCode,
		&i.ItemCode,
		&i.Quantity,
		&i.NeedDate,
		&i.StartDate,
		&i.OrderType,
		&i.DemandType,
		&i.ParentItemCode,
		&i.Llc,
		&i.CreatedAt,
	)
	return i, err
}

const createSalesOrderDemand = `-- name: CreateSalesOrderDemand :one
INSERT INTO sales_order_demands (sales_order_code, item_code, mask, quantity, delivered_qty, delivery_date, division_code, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, sales_order_code, item_code, mask, quantity, delivered_qty, delivery_date, division_code, status, is_active, created_at, updated_at, code
`

type CreateSalesOrderDemandParams struct {
	SalesOrderCode int64
	ItemCode       int64
	Mask           string
	Quantity       pgtype.Numeric
	DeliveredQty   pgtype.Numeric
	DeliveryDate   pgtype.Date
	DivisionCode   *int64
	Status         string
}

func (q *Queries) CreateSalesOrderDemand(ctx context.Context, arg CreateSalesOrderDemandParams) (SalesOrderDemand, error) {
	row := q.db.QueryRow(ctx, createSalesOrderDemand,
		arg.SalesOrderCode,
		arg.ItemCode,
		arg.Mask,
		arg.Quantity,
		arg.DeliveredQty,
		arg.DeliveryDate,
		arg.DivisionCode,
		arg.Status,
	)
	var i SalesOrderDemand
	err := row.Scan(
		&i.ID,
		&i.SalesOrderCode,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.DeliveredQty,
		&i.DeliveryDate,
		&i.DivisionCode,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
	)
	return i, err
}

const createStockSnapshot = `-- name: CreateStockSnapshot :one
INSERT INTO stock_snapshots (item_code, warehouse_code, quantity, reserved_qty, safety_stock, snapshot_date)
VALUES ($1, $2, $3, $4, $5, NOW())
    RETURNING id, item_code, warehouse_code, quantity, reserved_qty, safety_stock, snapshot_date, created_at, maximum_stock, min_max_active
`

type CreateStockSnapshotParams struct {
	ItemCode      int64
	WarehouseCode int64
	Quantity      pgtype.Numeric
	ReservedQty   pgtype.Numeric
	SafetyStock   pgtype.Numeric
}

func (q *Queries) CreateStockSnapshot(ctx context.Context, arg CreateStockSnapshotParams) (StockSnapshot, error) {
	row := q.db.QueryRow(ctx, createStockSnapshot,
		arg.ItemCode,
		arg.WarehouseCode,
		arg.Quantity,
		arg.ReservedQty,
		arg.SafetyStock,
	)
	var i StockSnapshot
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.WarehouseCode,
		&i.Quantity,
		&i.ReservedQty,
		&i.SafetyStock,
		&i.SnapshotDate,
		&i.CreatedAt,
		&i.MaximumStock,
		&i.MinMaxActive,
	)
	return i, err
}

const deleteConfiguredItemRule = `-- name: DeleteConfiguredItemRule :exec
UPDATE configured_item_rules SET is_active = FALSE, updated_at = NOW() WHERE code = $1
`

func (q *Queries) DeleteConfiguredItemRule(ctx context.Context, code pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteConfiguredItemRule, code)
	return err
}

const deleteMRPPlannedSuggestions = `-- name: DeleteMRPPlannedSuggestions :exec
DELETE FROM mrp_planned_suggestions WHERE plan_code = $1
`

func (q *Queries) DeleteMRPPlannedSuggestions(ctx context.Context, planCode int64) error {
	_, err := q.db.Exec(ctx, deleteMRPPlannedSuggestions, planCode)
	return err
}

const deleteProfilesByPlan = `-- name: DeleteProfilesByPlan :exec
DELETE FROM mrp_item_profiles WHERE plan_code = $1
`

func (q *Queries) DeleteProfilesByPlan(ctx context.Context, planCode int64) error {
	_, err := q.db.Exec(ctx, deleteProfilesByPlan, planCode)
	return err
}

const finishMRPCalculation = `-- name: FinishMRPCalculation :one
UPDATE mrp_calculation_logs
SET finished_at = NOW(),
    status = $1,
    errors = $2,
    total_items = $3,
    total_orders = $4
WHERE code = $5
    RETURNING id, plan_code, started_at, finished_at, status, errors, total_items, total_orders, created_at, code
`

type FinishMRPCalculationParams struct {
	Status      string
	Errors      []byte
	TotalItems  int32
	TotalOrders int32
	Code        pgtype.Int8
}

func (q *Queries) FinishMRPCalculation(ctx context.Context, arg FinishMRPCalculationParams) (MrpCalculationLog, error) {
	row := q.db.QueryRow(ctx, finishMRPCalculation,
		arg.Status,
		arg.Errors,
		arg.TotalItems,
		arg.TotalOrders,
		arg.Code,
	)
	var i MrpCalculationLog
	err := row.Scan(
		&i.ID,
		&i.PlanCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Errors,
		&i.TotalItems,
		&i.TotalOrders,
		&i.CreatedAt,
		&i.Code,
	)
	return i, err
}

const getConfiguredItemRules = `-- name: GetConfiguredItemRules :many
SELECT id, item_code, table_type, field_name, rule_type, rule_value, sequence, is_active, created_at, updated_at, created_by, code FROM configured_item_rules WHERE item_code = $1 AND is_active = TRUE ORDER BY sequence
`

func (q *Queries) GetConfiguredItemRules(ctx context.Context, itemCode int64) ([]ConfiguredItemRule, error) {
	rows, err := q.db.Query(ctx, getConfiguredItemRules, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfiguredItemRule
	for rows.Next() {
		var i ConfiguredItemRule
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.TableType,
			&i.FieldName,
			&i.RuleType,
			&i.RuleValue,
			&i.Sequence,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMRPCalculationLog = `-- name: GetMRPCalculationLog :one
SELECT id, plan_code, started_at, finished_at, status, errors, total_items, total_orders, created_at, code FROM mrp_calculation_logs WHERE code = $1
`

func (q *Queries) GetMRPCalculationLog(ctx context.Context, code pgtype.Int8) (MrpCalculationLog, error) {
	row := q.db.QueryRow(ctx, getMRPCalculationLog, code)
	var i MrpCalculationLog
	err := row.Scan(
		&i.ID,
		&i.PlanCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Errors,
		&i.TotalItems,
		&i.TotalOrders,
		&i.CreatedAt,
		&i.Code,
	)
	return i, err
}

const getMRPItemProfiles = `-- name: GetMRPItemProfiles :many
SELECT id, item_code, plan_code, calculation_date, demand, orders_planned, orders_firm, stock_projected, llc, need_date, created_at, code FROM mrp_item_profiles WHERE item_code = $1 AND plan_code = $2 ORDER BY need_date
`

type GetMRPItemProfilesParams struct {
	ItemCode int64
	PlanCode int64
}

func (q *Queries) GetMRPItemProfiles(ctx context.Context, arg GetMRPItemProfilesParams) ([]MrpItemProfile, error) {
	rows, err := q.db.Query(ctx, getMRPItemProfiles, arg.ItemCode, arg.PlanCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MrpItemProfile
	for rows.Next() {
		var i MrpItemProfile
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.PlanCode,
			&i.CalculationDate,
			&i.Demand,
			&i.OrdersPlanned,
			&i.OrdersFirm,
			&i.StockProjected,
			&i.Llc,
			&i.NeedDate,
			&i.CreatedAt,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesOrderDemandByCode = `-- name: GetSalesOrderDemandByCode :one
SELECT id, sales_order_code, item_code, mask, quantity, delivered_qty, delivery_date, division_code, status, is_active, created_at, updated_at, code FROM sales_order_demands WHERE code = $1
`

func (q *Queries) GetSalesOrderDemandByCode(ctx context.Context, code pgtype.Int8) (SalesOrderDemand, error) {
	row := q.db.QueryRow(ctx, getSalesOrderDemandByCode, code)
	var i SalesOrderDemand
	err := row.Scan(
		&i.ID,
		&i.SalesOrderCode,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.DeliveredQty,
		&i.DeliveryDate,
		&i.DivisionCode,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
	)
	return i, err
}

const getStockSnapshot = `-- name: GetStockSnapshot :one
SELECT id, item_code, warehouse_code, quantity, reserved_qty, safety_stock, snapshot_date, created_at, maximum_stock, min_max_active FROM stock_snapshots WHERE item_code = $1 ORDER BY snapshot_date DESC LIMIT 1
`

func (q *Queries) GetStockSnapshot(ctx context.Context, itemCode int64) (StockSnapshot, error) {
	row := q.db.QueryRow(ctx, getStockSnapshot, itemCode)
	var i StockSnapshot
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.WarehouseCode,
		&i.Quantity,
		&i.ReservedQty,
		&i.SafetyStock,
		&i.SnapshotDate,
		&i.CreatedAt,
		&i.MaximumStock,
		&i.MinMaxActive,
	)
	return i, err
}

const listMRPCalculationLogsByPlan = `-- name: ListMRPCalculationLogsByPlan :many
SELECT id, plan_code, started_at, finished_at, status, errors, total_items, total_orders, created_at, code FROM mrp_calculation_logs WHERE plan_code = $1 ORDER BY started_at DESC
`

func (q *Queries) ListMRPCalculationLogsByPlan(ctx context.Context, planCode int64) ([]MrpCalculationLog, error) {
	rows, err := q.db.Query(ctx, listMRPCalculationLogsByPlan, planCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MrpCalculationLog
	for rows.Next() {
		var i MrpCalculationLog
		if err := rows.Scan(
			&i.ID,
			&i.PlanCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Errors,
			&i.TotalItems,
			&i.TotalOrders,
			&i.CreatedAt,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMRPPlannedSuggestions = `-- name: ListMRPPlannedSuggestions :many
SELECT code, plan_code, item_code, quantity, need_date, start_date, order_type, demand_type, parent_item_code, llc, created_at FROM mrp_planned_suggestions WHERE plan_code = $1 ORDER BY llc, need_date
`

func (q *Queries) ListMRPPlannedSuggestions(ctx context.Context, planCode int64) ([]MrpPlannedSuggestion, error) {
	rows, err := q.db.Query(ctx, listMRPPlannedSuggestions, planCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MrpPlannedSuggestion
	for rows.Next() {
		var i MrpPlannedSuggestion
		if err := rows.Scan(
			&i.Code,
			&i.PlanCode,
			&i.ItemCode,
			&i.Quantity,
			&i.NeedDate,
			&i.StartDate,
			&i.OrderType,
			&i.DemandType,
			&i.ParentItemCode,
			&i.Llc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrderDemandsByItem = `-- name: ListSalesOrderDemandsByItem :many
SELECT id, sales_order_code, item_code, mask, quantity, delivered_qty, delivery_date, division_code, status, is_active, created_at, updated_at, code FROM sales_order_demands WHERE item_code = $1 AND is_active = TRUE ORDER BY delivery_date
`

func (q *Queries) ListSalesOrderDemandsByItem(ctx context.Context, itemCode int64) ([]SalesOrderDemand, error) {
	rows, err := q.db.Query(ctx, listSalesOrderDemandsByItem, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrderDemand
	for rows.Next() {
		var i SalesOrderDemand
		if err := rows.Scan(
			&i.ID,
			&i.SalesOrderCode,
			&i.ItemCode,
			&i.Mask,
			&i.Quantity,
			&i.DeliveredQty,
			&i.DeliveryDate,
			&i.DivisionCode,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startMRPCalculation = `-- name: StartMRPCalculation :one
INSERT INTO mrp_calculation_logs (plan_code, status, started_at)
VALUES ($1, 'RUNNING', NOW())
    RETURNING id, plan_code, started_at, finished_at, status, errors, total_items, total_orders, created_at, code
`

func (q *Queries) StartMRPCalculation(ctx context.Context, planCode int64) (MrpCalculationLog, error) {
	row := q.db.QueryRow(ctx, startMRPCalculation, planCode)
	var i MrpCalculationLog
	err := row.Scan(
		&i.ID,
		&i.PlanCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Errors,
		&i.TotalItems,
		&i.TotalOrders,
		&i.CreatedAt,
		&i.Code,
	)
	return i, err
}

const updateSalesOrderDemandStatus = `-- name: UpdateSalesOrderDemandStatus :one
UPDATE sales_order_demands SET status = $1, delivered_qty = $2, updated_at = NOW() WHERE code = $3 RETURNING id, sales_order_code, item_code, mask, quantity, delivered_qty, delivery_date, division_code, status, is_active, created_at, updated_at, code
`

type UpdateSalesOrderDemandStatusParams struct {
	Status       string
	DeliveredQty pgtype.Numeric
	Code         pgtype.Int8
}

func (q *Queries) UpdateSalesOrderDemandStatus(ctx context.Context, arg UpdateSalesOrderDemandStatusParams) (SalesOrderDemand, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderDemandStatus, arg.Status, arg.DeliveredQty, arg.Code)
	var i SalesOrderDemand
	err := row.Scan(
		&i.ID,
		&i.SalesOrderCode,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.DeliveredQty,
		&i.DeliveryDate,
		&i.DivisionCode,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
	)
	return i, err
}
