// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_execution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const freezeProductionRoutingDependencies = `-- name: FreezeProductionRoutingDependencies :exec
INSERT INTO production_order_operation_dependencies(production_order_id,enterprise_id,predecessor_id,successor_id)
SELECT ord.id,ord.enterprise_id,prior.id,current.id
FROM production_orders ord
JOIN production_order_operations current ON current.production_order_id=ord.id
JOIN production_order_operations prior ON prior.production_order_id=ord.id
LEFT JOIN route_operations step ON step.id=current.route_operation_id
WHERE (
 EXISTS(SELECT 1 FROM route_operation_network edge WHERE edge.predecessor_id=prior.route_operation_id AND edge.successor_id=current.route_operation_id)
 OR (NOT EXISTS(SELECT 1 FROM route_operation_network edge JOIN route_operations source ON source.id=edge.predecessor_id WHERE source.route_id=step.route_id) AND prior.sequence<current.sequence)
) AND ord.id=$1 AND ord.enterprise_id=$2 AND ord.routing_snapshot_at IS NULL
ON CONFLICT DO NOTHING
`

type FreezeProductionRoutingDependenciesParams struct {
	ID           int64
	EnterpriseID *int64
}

func (q *Queries) FreezeProductionRoutingDependencies(ctx context.Context, arg FreezeProductionRoutingDependenciesParams) error {
	_, err := q.db.Exec(ctx, freezeProductionRoutingDependencies, arg.ID, arg.EnterpriseID)
	return err
}

const getProductionExecution = `-- name: GetProductionExecution :one
SELECT id, status FROM production_orders WHERE id = $1 AND enterprise_id = $2
`

type GetProductionExecutionParams struct {
	ID           int64
	EnterpriseID *int64
}

type GetProductionExecutionRow struct {
	ID     int64
	Status string
}

func (q *Queries) GetProductionExecution(ctx context.Context, arg GetProductionExecutionParams) (GetProductionExecutionRow, error) {
	row := q.db.QueryRow(ctx, getProductionExecution, arg.ID, arg.EnterpriseID)
	var i GetProductionExecutionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const listProductionExecutionEvents = `-- name: ListProductionExecutionEvents :many
SELECT e.id,e.old_status,e.new_status,e.actual_hours_delta,e.notes,e.occurred_at,
 COALESCE(u.name, e.actor_id::text, 'Sistema (legado)')::text AS actor_name
FROM production_operation_execution_events e
JOIN production_orders ord ON ord.id=e.production_order_id AND ord.enterprise_id=e.enterprise_id
LEFT JOIN users u ON u.id=e.actor_id
WHERE e.operation_id=$1 AND e.enterprise_id=$2
ORDER BY e.id
`

type ListProductionExecutionEventsParams struct {
	OperationID  int64
	EnterpriseID int64
}

type ListProductionExecutionEventsRow struct {
	ID               int64
	OldStatus        string
	NewStatus        string
	ActualHoursDelta pgtype.Numeric
	Notes            pgtype.Text
	OccurredAt       pgtype.Timestamptz
	ActorName        string
}

func (q *Queries) ListProductionExecutionEvents(ctx context.Context, arg ListProductionExecutionEventsParams) ([]ListProductionExecutionEventsRow, error) {
	rows, err := q.db.Query(ctx, listProductionExecutionEvents, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionExecutionEventsRow
	for rows.Next() {
		var i ListProductionExecutionEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OldStatus,
			&i.NewStatus,
			&i.ActualHoursDelta,
			&i.Notes,
			&i.OccurredAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOperationExecution = `-- name: LockOperationExecution :one
SELECT op.id, op.production_order_id, op.status, ord.status AS order_status
FROM production_order_operations op
JOIN production_orders ord ON ord.id = op.production_order_id
WHERE op.id = $1 AND ord.enterprise_id = $2
FOR UPDATE OF ord, op
`

type LockOperationExecutionParams struct {
	ID           int64
	EnterpriseID *int64
}

type LockOperationExecutionRow struct {
	ID                int64
	ProductionOrderID int64
	Status            string
	OrderStatus       string
}

func (q *Queries) LockOperationExecution(ctx context.Context, arg LockOperationExecutionParams) (LockOperationExecutionRow, error) {
	row := q.db.QueryRow(ctx, lockOperationExecution, arg.ID, arg.EnterpriseID)
	var i LockOperationExecutionRow
	err := row.Scan(
		&i.ID,
		&i.ProductionOrderID,
		&i.Status,
		&i.OrderStatus,
	)
	return i, err
}

const lockProductionExecution = `-- name: LockProductionExecution :one
SELECT id, status, item_code, COALESCE(mask,'')::text AS mask FROM production_orders WHERE id = $1 AND enterprise_id = $2 FOR UPDATE
`

type LockProductionExecutionParams struct {
	ID           int64
	EnterpriseID *int64
}

type LockProductionExecutionRow struct {
	ID       int64
	Status   string
	ItemCode int64
	Mask     string
}

func (q *Queries) LockProductionExecution(ctx context.Context, arg LockProductionExecutionParams) (LockProductionExecutionRow, error) {
	row := q.db.QueryRow(ctx, lockProductionExecution, arg.ID, arg.EnterpriseID)
	var i LockProductionExecutionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ItemCode,
		&i.Mask,
	)
	return i, err
}

const markProductionRoutingFrozen = `-- name: MarkProductionRoutingFrozen :exec
UPDATE production_orders SET routing_snapshot_at=COALESCE(routing_snapshot_at,NOW()) WHERE id=$1 AND enterprise_id=$2
`

type MarkProductionRoutingFrozenParams struct {
	ID           int64
	EnterpriseID *int64
}

func (q *Queries) MarkProductionRoutingFrozen(ctx context.Context, arg MarkProductionRoutingFrozenParams) error {
	_, err := q.db.Exec(ctx, markProductionRoutingFrozen, arg.ID, arg.EnterpriseID)
	return err
}

const operationHasSuccessors = `-- name: OperationHasSuccessors :one
SELECT CASE WHEN (SELECT ord.routing_snapshot_at IS NOT NULL FROM production_orders ord JOIN production_order_operations op ON op.production_order_id=ord.id WHERE op.id=$1) THEN EXISTS(SELECT 1 FROM production_order_operation_dependencies WHERE predecessor_id=$1) ELSE EXISTS (
 SELECT 1 FROM production_order_operations next
 JOIN production_order_operations current ON current.production_order_id = next.production_order_id
 LEFT JOIN route_operations step ON step.id = current.route_operation_id
 WHERE current.id = $1 AND (
  EXISTS (SELECT 1 FROM route_operation_network edge WHERE edge.predecessor_id = current.route_operation_id AND edge.successor_id = next.route_operation_id)
  OR (NOT EXISTS (SELECT 1 FROM route_operation_network edge JOIN route_operations source ON source.id=edge.predecessor_id WHERE source.route_id=step.route_id) AND next.sequence > current.sequence)
 )
) END::boolean
`

func (q *Queries) OperationHasSuccessors(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, operationHasSuccessors, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const operationPredecessorsPending = `-- name: OperationPredecessorsPending :one
SELECT CASE WHEN (SELECT ord.routing_snapshot_at IS NOT NULL FROM production_orders ord JOIN production_order_operations op ON op.production_order_id=ord.id WHERE op.id=$1) THEN EXISTS(SELECT 1 FROM production_order_operation_dependencies d JOIN production_order_operations prior ON prior.id=d.predecessor_id WHERE d.successor_id=$1 AND prior.status NOT IN ('DONE','SKIPPED')) ELSE EXISTS (
 SELECT 1 FROM production_order_operations prior
 JOIN production_order_operations current ON current.production_order_id = prior.production_order_id
 LEFT JOIN route_operations step ON step.id = current.route_operation_id
 WHERE current.id = $1 AND prior.status NOT IN ('DONE', 'SKIPPED')
 AND (
   (EXISTS (SELECT 1 FROM route_operation_network edge WHERE edge.predecessor_id = prior.route_operation_id AND edge.successor_id = current.route_operation_id))
   OR (NOT EXISTS (SELECT 1 FROM route_operation_network edge JOIN route_operations source ON source.id = edge.predecessor_id WHERE source.route_id = step.route_id) AND prior.sequence < current.sequence)
 )
) END::boolean AS blocked
`

func (q *Queries) OperationPredecessorsPending(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, operationPredecessorsPending, id)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const productionOperationsPending = `-- name: ProductionOperationsPending :one
SELECT EXISTS(SELECT 1 FROM production_order_operations WHERE production_order_id = $1 AND status NOT IN ('DONE','SKIPPED'))::boolean
`

func (q *Queries) ProductionOperationsPending(ctx context.Context, productionOrderID int64) (bool, error) {
	row := q.db.QueryRow(ctx, productionOperationsPending, productionOrderID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setProductionExecutionActor = `-- name: SetProductionExecutionActor :exec
SELECT set_config('venture.execution_actor',$1::text,true),set_config('venture.execution_source',$2::text,true)
`

type SetProductionExecutionActorParams struct {
	Actor  string
	Source string
}

func (q *Queries) SetProductionExecutionActor(ctx context.Context, arg SetProductionExecutionActorParams) error {
	_, err := q.db.Exec(ctx, setProductionExecutionActor, arg.Actor, arg.Source)
	return err
}

const updateOperationExecution = `-- name: UpdateOperationExecution :exec
UPDATE production_order_operations SET status = $1::text,
 started_at = CASE WHEN $1::text = 'IN_PROGRESS' THEN COALESCE(started_at, NOW()) ELSE started_at END,
 completed_at = CASE WHEN $1::text IN ('DONE','SKIPPED') THEN NOW() ELSE completed_at END,
 actual_hours = actual_hours + $2::numeric,
 notes = concat_ws(E'\n', notes, to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS TZ') || ' · ' || CASE $1::text WHEN 'IN_PROGRESS' THEN 'Em andamento' WHEN 'PAUSED' THEN 'Pausada' WHEN 'INTERRUPTED' THEN 'Interrompida' WHEN 'DONE' THEN 'Concluída' ELSE 'Dispensada' END || CASE WHEN $3::text <> '' THEN ': ' || $3::text ELSE '' END),
 updated_at = NOW()
WHERE id = $4
`

type UpdateOperationExecutionParams struct {
	Status string
	Hours  pgtype.Numeric
	Reason string
	ID     int64
}

func (q *Queries) UpdateOperationExecution(ctx context.Context, arg UpdateOperationExecutionParams) error {
	_, err := q.db.Exec(ctx, updateOperationExecution,
		arg.Status,
		arg.Hours,
		arg.Reason,
		arg.ID,
	)
	return err
}
