// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_priority.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderPriority = `-- name: CreateOrderPriority :one
INSERT INTO order_priorities (code, interval_start, interval_end, priority, description, created_by, enterprise_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, interval_start, interval_end, priority, description, is_active, created_at, updated_at, created_by, code, enterprise_id
`

type CreateOrderPriorityParams struct {
	Code          int64
	IntervalStart pgtype.Numeric
	IntervalEnd   pgtype.Numeric
	Priority      string
	Description   pgtype.Text
	CreatedBy     pgtype.UUID
	EnterpriseID  *int64
}

func (q *Queries) CreateOrderPriority(ctx context.Context, arg CreateOrderPriorityParams) (OrderPriority, error) {
	row := q.db.QueryRow(ctx, createOrderPriority,
		arg.Code,
		arg.IntervalStart,
		arg.IntervalEnd,
		arg.Priority,
		arg.Description,
		arg.CreatedBy,
		arg.EnterpriseID,
	)
	var i OrderPriority
	err := row.Scan(
		&i.ID,
		&i.IntervalStart,
		&i.IntervalEnd,
		&i.Priority,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.EnterpriseID,
	)
	return i, err
}

const deleteOrderPriority = `-- name: DeleteOrderPriority :exec
UPDATE order_priorities SET is_active = FALSE, updated_at = NOW() WHERE code = $1 AND enterprise_id = $2
`

type DeleteOrderPriorityParams struct {
	Code         int64
	EnterpriseID *int64
}

func (q *Queries) DeleteOrderPriority(ctx context.Context, arg DeleteOrderPriorityParams) error {
	_, err := q.db.Exec(ctx, deleteOrderPriority, arg.Code, arg.EnterpriseID)
	return err
}

const findPriorityByValue = `-- name: FindPriorityByValue :one
SELECT id, interval_start, interval_end, priority, description, is_active, created_at, updated_at, created_by, code, enterprise_id FROM order_priorities
WHERE $1 >= interval_start AND $1 < interval_end AND enterprise_id = $2 AND is_active = TRUE
ORDER BY interval_start
    LIMIT 1
`

type FindPriorityByValueParams struct {
	IntervalStart pgtype.Numeric
	EnterpriseID  *int64
}

func (q *Queries) FindPriorityByValue(ctx context.Context, arg FindPriorityByValueParams) (OrderPriority, error) {
	row := q.db.QueryRow(ctx, findPriorityByValue, arg.IntervalStart, arg.EnterpriseID)
	var i OrderPriority
	err := row.Scan(
		&i.ID,
		&i.IntervalStart,
		&i.IntervalEnd,
		&i.Priority,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.EnterpriseID,
	)
	return i, err
}

const getOrderPriorityByCode = `-- name: GetOrderPriorityByCode :one
SELECT id, interval_start, interval_end, priority, description, is_active, created_at, updated_at, created_by, code, enterprise_id FROM order_priorities WHERE code = $1 AND enterprise_id = $2
`

type GetOrderPriorityByCodeParams struct {
	Code         int64
	EnterpriseID *int64
}

func (q *Queries) GetOrderPriorityByCode(ctx context.Context, arg GetOrderPriorityByCodeParams) (OrderPriority, error) {
	row := q.db.QueryRow(ctx, getOrderPriorityByCode, arg.Code, arg.EnterpriseID)
	var i OrderPriority
	err := row.Scan(
		&i.ID,
		&i.IntervalStart,
		&i.IntervalEnd,
		&i.Priority,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.EnterpriseID,
	)
	return i, err
}

const listOrderPriorities = `-- name: ListOrderPriorities :many
SELECT id, interval_start, interval_end, priority, description, is_active, created_at, updated_at, created_by, code, enterprise_id FROM order_priorities WHERE enterprise_id = $1 AND is_active = TRUE ORDER BY interval_start
`

func (q *Queries) ListOrderPriorities(ctx context.Context, enterpriseID *int64) ([]OrderPriority, error) {
	rows, err := q.db.Query(ctx, listOrderPriorities, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderPriority
	for rows.Next() {
		var i OrderPriority
		if err := rows.Scan(
			&i.ID,
			&i.IntervalStart,
			&i.IntervalEnd,
			&i.Priority,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Code,
			&i.EnterpriseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPriority = `-- name: UpdateOrderPriority :one
UPDATE order_priorities
SET interval_start = $1,
    interval_end = $2,
    priority = $3,
    description = $4,
    updated_at = NOW()
WHERE code = $5 AND enterprise_id = $6
    RETURNING id, interval_start, interval_end, priority, description, is_active, created_at, updated_at, created_by, code, enterprise_id
`

type UpdateOrderPriorityParams struct {
	IntervalStart pgtype.Numeric
	IntervalEnd   pgtype.Numeric
	Priority      string
	Description   pgtype.Text
	Code          int64
	EnterpriseID  *int64
}

func (q *Queries) UpdateOrderPriority(ctx context.Context, arg UpdateOrderPriorityParams) (OrderPriority, error) {
	row := q.db.QueryRow(ctx, updateOrderPriority,
		arg.IntervalStart,
		arg.IntervalEnd,
		arg.Priority,
		arg.Description,
		arg.Code,
		arg.EnterpriseID,
	)
	var i OrderPriority
	err := row.Scan(
		&i.ID,
		&i.IntervalStart,
		&i.IntervalEnd,
		&i.Priority,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.EnterpriseID,
	)
	return i, err
}
