// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planned_order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlannedOrder = `-- name: CreatePlannedOrder :one
INSERT INTO planned_orders (
    order_number,
    item_code,
    mask,
    quantity,
    quantity_loss,
    quantity_corrected,
    order_type,
    status,
    plan_code,
    demand_type,
    demand_code,
    need_date,
    start_date,
    end_date,
    cost_center_code,
    employee_code,
    machine_code,
    production_time,
    priority,
    llc,
    notes,
    parent_order_code,
    sales_order_code,
    created_by
)
VALUES (
           $1, $2, $3, $4, $5, $6,
           $7, $8, $9, $10, $11, $12,
           $13, $14, $15, $16, $17, $18,
           $19, $20, $21, $22, $23, $24
       )
    RETURNING id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days
`

type CreatePlannedOrderParams struct {
	OrderNumber       int64
	ItemCode          int64
	Mask              string
	Quantity          pgtype.Numeric
	QuantityLoss      pgtype.Numeric
	QuantityCorrected pgtype.Numeric
	OrderType         OrderTypeEnum
	Status            OrderStatusEnum
	PlanCode          *int64
	DemandType        DemandTypeEnum
	DemandCode        int32
	NeedDate          pgtype.Date
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	CostCenterCode    *int64
	EmployeeCode      *int64
	MachineCode       *int64
	ProductionTime    pgtype.Numeric
	Priority          pgtype.Text
	Llc               int32
	Notes             pgtype.Text
	ParentOrderCode   *int64
	SalesOrderCode    *int64
	CreatedBy         pgtype.UUID
}

func (q *Queries) CreatePlannedOrder(ctx context.Context, arg CreatePlannedOrderParams) (PlannedOrder, error) {
	row := q.db.QueryRow(ctx, createPlannedOrder,
		arg.OrderNumber,
		arg.ItemCode,
		arg.Mask,
		arg.Quantity,
		arg.QuantityLoss,
		arg.QuantityCorrected,
		arg.OrderType,
		arg.Status,
		arg.PlanCode,
		arg.DemandType,
		arg.DemandCode,
		arg.NeedDate,
		arg.StartDate,
		arg.EndDate,
		arg.CostCenterCode,
		arg.EmployeeCode,
		arg.MachineCode,
		arg.ProductionTime,
		arg.Priority,
		arg.Llc,
		arg.Notes,
		arg.ParentOrderCode,
		arg.SalesOrderCode,
		arg.CreatedBy,
	)
	var i PlannedOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.QuantityLoss,
		&i.QuantityCorrected,
		&i.OrderType,
		&i.Status,
		&i.DemandType,
		&i.DemandID,
		&i.NeedDate,
		&i.StartDate,
		&i.EndDate,
		&i.ProductionTime,
		&i.Priority,
		&i.Llc,
		&i.Notes,
		&i.IsFirm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.MachineCode,
		&i.CostCenterCode,
		&i.EmployeeCode,
		&i.ParentOrderCode,
		&i.PlanCode,
		&i.DemandCode,
		&i.SalesOrderCode,
		&i.SafetyTimeDays,
		&i.CoverageDays,
	)
	return i, err
}

const deleteOrdersByPlan = `-- name: DeleteOrdersByPlan :exec
UPDATE planned_orders SET is_active = FALSE, updated_at = NOW() WHERE plan_code = $1
`

func (q *Queries) DeleteOrdersByPlan(ctx context.Context, planCode *int64) error {
	_, err := q.db.Exec(ctx, deleteOrdersByPlan, planCode)
	return err
}

const deletePlannedOrder = `-- name: DeletePlannedOrder :exec
UPDATE planned_orders SET is_active = FALSE, updated_at = NOW() WHERE code = $1
`

func (q *Queries) DeletePlannedOrder(ctx context.Context, code int64) error {
	_, err := q.db.Exec(ctx, deletePlannedOrder, code)
	return err
}

const firmPlannedOrder = `-- name: FirmPlannedOrder :one
UPDATE planned_orders SET is_firm = TRUE, status = 'RELEASED', updated_at = NOW() WHERE code = $1 RETURNING id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days
`

func (q *Queries) FirmPlannedOrder(ctx context.Context, code int64) (PlannedOrder, error) {
	row := q.db.QueryRow(ctx, firmPlannedOrder, code)
	var i PlannedOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.QuantityLoss,
		&i.QuantityCorrected,
		&i.OrderType,
		&i.Status,
		&i.DemandType,
		&i.DemandID,
		&i.NeedDate,
		&i.StartDate,
		&i.EndDate,
		&i.ProductionTime,
		&i.Priority,
		&i.Llc,
		&i.Notes,
		&i.IsFirm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.MachineCode,
		&i.CostCenterCode,
		&i.EmployeeCode,
		&i.ParentOrderCode,
		&i.PlanCode,
		&i.DemandCode,
		&i.SalesOrderCode,
		&i.SafetyTimeDays,
		&i.CoverageDays,
	)
	return i, err
}

const getNextOrderNumber = `-- name: GetNextOrderNumber :one
SELECT COALESCE(MAX(order_number), 0) + 1 AS next_number FROM planned_orders
`

func (q *Queries) GetNextOrderNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextOrderNumber)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getPlannedOrderByCode = `-- name: GetPlannedOrderByCode :one
SELECT id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days FROM planned_orders WHERE code = $1
`

func (q *Queries) GetPlannedOrderByCode(ctx context.Context, code int64) (PlannedOrder, error) {
	row := q.db.QueryRow(ctx, getPlannedOrderByCode, code)
	var i PlannedOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.QuantityLoss,
		&i.QuantityCorrected,
		&i.OrderType,
		&i.Status,
		&i.DemandType,
		&i.DemandID,
		&i.NeedDate,
		&i.StartDate,
		&i.EndDate,
		&i.ProductionTime,
		&i.Priority,
		&i.Llc,
		&i.Notes,
		&i.IsFirm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.MachineCode,
		&i.CostCenterCode,
		&i.EmployeeCode,
		&i.ParentOrderCode,
		&i.PlanCode,
		&i.DemandCode,
		&i.SalesOrderCode,
		&i.SafetyTimeDays,
		&i.CoverageDays,
	)
	return i, err
}

const getPlannedOrderByNumber = `-- name: GetPlannedOrderByNumber :one
SELECT id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days FROM planned_orders WHERE order_number = $1
`

func (q *Queries) GetPlannedOrderByNumber(ctx context.Context, orderNumber int64) (PlannedOrder, error) {
	row := q.db.QueryRow(ctx, getPlannedOrderByNumber, orderNumber)
	var i PlannedOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.QuantityLoss,
		&i.QuantityCorrected,
		&i.OrderType,
		&i.Status,
		&i.DemandType,
		&i.DemandID,
		&i.NeedDate,
		&i.StartDate,
		&i.EndDate,
		&i.ProductionTime,
		&i.Priority,
		&i.Llc,
		&i.Notes,
		&i.IsFirm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.MachineCode,
		&i.CostCenterCode,
		&i.EmployeeCode,
		&i.ParentOrderCode,
		&i.PlanCode,
		&i.DemandCode,
		&i.SalesOrderCode,
		&i.SafetyTimeDays,
		&i.CoverageDays,
	)
	return i, err
}

const listFirmPlannedOrdersByItems = `-- name: ListFirmPlannedOrdersByItems :many
SELECT code, item_code, quantity, need_date
FROM planned_orders
WHERE item_code = ANY($1::bigint[])
  AND is_firm = TRUE
  AND is_active = TRUE
ORDER BY item_code, need_date
`

type ListFirmPlannedOrdersByItemsRow struct {
	Code     int64
	ItemCode int64
	Quantity pgtype.Numeric
	NeedDate pgtype.Date
}

func (q *Queries) ListFirmPlannedOrdersByItems(ctx context.Context, itemCodes []int64) ([]ListFirmPlannedOrdersByItemsRow, error) {
	rows, err := q.db.Query(ctx, listFirmPlannedOrdersByItems, itemCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFirmPlannedOrdersByItemsRow
	for rows.Next() {
		var i ListFirmPlannedOrdersByItemsRow
		if err := rows.Scan(
			&i.Code,
			&i.ItemCode,
			&i.Quantity,
			&i.NeedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedOrders = `-- name: ListPlannedOrders :many
SELECT id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days FROM planned_orders WHERE is_active = TRUE ORDER BY need_date
`

func (q *Queries) ListPlannedOrders(ctx context.Context) ([]PlannedOrder, error) {
	rows, err := q.db.Query(ctx, listPlannedOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedOrder
	for rows.Next() {
		var i PlannedOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.ItemCode,
			&i.Mask,
			&i.Quantity,
			&i.QuantityLoss,
			&i.QuantityCorrected,
			&i.OrderType,
			&i.Status,
			&i.DemandType,
			&i.DemandID,
			&i.NeedDate,
			&i.StartDate,
			&i.EndDate,
			&i.ProductionTime,
			&i.Priority,
			&i.Llc,
			&i.Notes,
			&i.IsFirm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Code,
			&i.MachineCode,
			&i.CostCenterCode,
			&i.EmployeeCode,
			&i.ParentOrderCode,
			&i.PlanCode,
			&i.DemandCode,
			&i.SalesOrderCode,
			&i.SafetyTimeDays,
			&i.CoverageDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedOrdersByItem = `-- name: ListPlannedOrdersByItem :many
SELECT id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days FROM planned_orders WHERE item_code = $1 AND is_active = TRUE ORDER BY need_date
`

func (q *Queries) ListPlannedOrdersByItem(ctx context.Context, itemCode int64) ([]PlannedOrder, error) {
	rows, err := q.db.Query(ctx, listPlannedOrdersByItem, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedOrder
	for rows.Next() {
		var i PlannedOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.ItemCode,
			&i.Mask,
			&i.Quantity,
			&i.QuantityLoss,
			&i.QuantityCorrected,
			&i.OrderType,
			&i.Status,
			&i.DemandType,
			&i.DemandID,
			&i.NeedDate,
			&i.StartDate,
			&i.EndDate,
			&i.ProductionTime,
			&i.Priority,
			&i.Llc,
			&i.Notes,
			&i.IsFirm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Code,
			&i.MachineCode,
			&i.CostCenterCode,
			&i.EmployeeCode,
			&i.ParentOrderCode,
			&i.PlanCode,
			&i.DemandCode,
			&i.SalesOrderCode,
			&i.SafetyTimeDays,
			&i.CoverageDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedOrdersByPlan = `-- name: ListPlannedOrdersByPlan :many
SELECT id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days FROM planned_orders WHERE plan_code = $1 AND is_active = TRUE ORDER BY need_date
`

func (q *Queries) ListPlannedOrdersByPlan(ctx context.Context, planCode *int64) ([]PlannedOrder, error) {
	rows, err := q.db.Query(ctx, listPlannedOrdersByPlan, planCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedOrder
	for rows.Next() {
		var i PlannedOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.ItemCode,
			&i.Mask,
			&i.Quantity,
			&i.QuantityLoss,
			&i.QuantityCorrected,
			&i.OrderType,
			&i.Status,
			&i.DemandType,
			&i.DemandID,
			&i.NeedDate,
			&i.StartDate,
			&i.EndDate,
			&i.ProductionTime,
			&i.Priority,
			&i.Llc,
			&i.Notes,
			&i.IsFirm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Code,
			&i.MachineCode,
			&i.CostCenterCode,
			&i.EmployeeCode,
			&i.ParentOrderCode,
			&i.PlanCode,
			&i.DemandCode,
			&i.SalesOrderCode,
			&i.SafetyTimeDays,
			&i.CoverageDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedOrdersByStatus = `-- name: ListPlannedOrdersByStatus :many
SELECT id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days FROM planned_orders WHERE status = $1 AND is_active = TRUE ORDER BY need_date
`

func (q *Queries) ListPlannedOrdersByStatus(ctx context.Context, status OrderStatusEnum) ([]PlannedOrder, error) {
	rows, err := q.db.Query(ctx, listPlannedOrdersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedOrder
	for rows.Next() {
		var i PlannedOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.ItemCode,
			&i.Mask,
			&i.Quantity,
			&i.QuantityLoss,
			&i.QuantityCorrected,
			&i.OrderType,
			&i.Status,
			&i.DemandType,
			&i.DemandID,
			&i.NeedDate,
			&i.StartDate,
			&i.EndDate,
			&i.ProductionTime,
			&i.Priority,
			&i.Llc,
			&i.Notes,
			&i.IsFirm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Code,
			&i.MachineCode,
			&i.CostCenterCode,
			&i.EmployeeCode,
			&i.ParentOrderCode,
			&i.PlanCode,
			&i.DemandCode,
			&i.SalesOrderCode,
			&i.SafetyTimeDays,
			&i.CoverageDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedOrdersByType = `-- name: ListPlannedOrdersByType :many
SELECT id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days FROM planned_orders WHERE order_type = $1 AND is_active = TRUE ORDER BY need_date
`

func (q *Queries) ListPlannedOrdersByType(ctx context.Context, orderType OrderTypeEnum) ([]PlannedOrder, error) {
	rows, err := q.db.Query(ctx, listPlannedOrdersByType, orderType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedOrder
	for rows.Next() {
		var i PlannedOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.ItemCode,
			&i.Mask,
			&i.Quantity,
			&i.QuantityLoss,
			&i.QuantityCorrected,
			&i.OrderType,
			&i.Status,
			&i.DemandType,
			&i.DemandID,
			&i.NeedDate,
			&i.StartDate,
			&i.EndDate,
			&i.ProductionTime,
			&i.Priority,
			&i.Llc,
			&i.Notes,
			&i.IsFirm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Code,
			&i.MachineCode,
			&i.CostCenterCode,
			&i.EmployeeCode,
			&i.ParentOrderCode,
			&i.PlanCode,
			&i.DemandCode,
			&i.SalesOrderCode,
			&i.SafetyTimeDays,
			&i.CoverageDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlannedOrderDates = `-- name: UpdatePlannedOrderDates :one
UPDATE planned_orders SET start_date = $1, end_date = $2, updated_at = NOW() WHERE code = $3 RETURNING id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days
`

type UpdatePlannedOrderDatesParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Code      int64
}

func (q *Queries) UpdatePlannedOrderDates(ctx context.Context, arg UpdatePlannedOrderDatesParams) (PlannedOrder, error) {
	row := q.db.QueryRow(ctx, updatePlannedOrderDates, arg.StartDate, arg.EndDate, arg.Code)
	var i PlannedOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.QuantityLoss,
		&i.QuantityCorrected,
		&i.OrderType,
		&i.Status,
		&i.DemandType,
		&i.DemandID,
		&i.NeedDate,
		&i.StartDate,
		&i.EndDate,
		&i.ProductionTime,
		&i.Priority,
		&i.Llc,
		&i.Notes,
		&i.IsFirm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.MachineCode,
		&i.CostCenterCode,
		&i.EmployeeCode,
		&i.ParentOrderCode,
		&i.PlanCode,
		&i.DemandCode,
		&i.SalesOrderCode,
		&i.SafetyTimeDays,
		&i.CoverageDays,
	)
	return i, err
}

const updatePlannedOrderStatus = `-- name: UpdatePlannedOrderStatus :one
UPDATE planned_orders SET status = $1, updated_at = NOW() WHERE code = $2 RETURNING id, order_number, item_code, mask, quantity, quantity_loss, quantity_corrected, order_type, status, demand_type, demand_id, need_date, start_date, end_date, production_time, priority, llc, notes, is_firm, is_active, created_at, updated_at, created_by, code, machine_code, cost_center_code, employee_code, parent_order_code, plan_code, demand_code, sales_order_code, safety_time_days, coverage_days
`

type UpdatePlannedOrderStatusParams struct {
	Status OrderStatusEnum
	Code   int64
}

func (q *Queries) UpdatePlannedOrderStatus(ctx context.Context, arg UpdatePlannedOrderStatusParams) (PlannedOrder, error) {
	row := q.db.QueryRow(ctx, updatePlannedOrderStatus, arg.Status, arg.Code)
	var i PlannedOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ItemCode,
		&i.Mask,
		&i.Quantity,
		&i.QuantityLoss,
		&i.QuantityCorrected,
		&i.OrderType,
		&i.Status,
		&i.DemandType,
		&i.DemandID,
		&i.NeedDate,
		&i.StartDate,
		&i.EndDate,
		&i.ProductionTime,
		&i.Priority,
		&i.Llc,
		&i.Notes,
		&i.IsFirm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Code,
		&i.MachineCode,
		&i.CostCenterCode,
		&i.EmployeeCode,
		&i.ParentOrderCode,
		&i.PlanCode,
		&i.DemandCode,
		&i.SalesOrderCode,
		&i.SafetyTimeDays,
		&i.CoverageDays,
	)
	return i, err
}
