// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planning_params.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlanningParamByKey = `-- name: GetPlanningParamByKey :one
SELECT id, param_number, param_key, value, description, created_at, updated_at, updated_by, enterprise_id FROM planning_params WHERE param_key = $1 AND enterprise_id = $2
`

type GetPlanningParamByKeyParams struct {
	ParamKey     string
	EnterpriseID *int64
}

func (q *Queries) GetPlanningParamByKey(ctx context.Context, arg GetPlanningParamByKeyParams) (PlanningParam, error) {
	row := q.db.QueryRow(ctx, getPlanningParamByKey, arg.ParamKey, arg.EnterpriseID)
	var i PlanningParam
	err := row.Scan(
		&i.ID,
		&i.ParamNumber,
		&i.ParamKey,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.EnterpriseID,
	)
	return i, err
}

const getPlanningParamByNumber = `-- name: GetPlanningParamByNumber :one
SELECT id, param_number, param_key, value, description, created_at, updated_at, updated_by, enterprise_id FROM planning_params WHERE param_number = $1 AND enterprise_id = $2
`

type GetPlanningParamByNumberParams struct {
	ParamNumber  int32
	EnterpriseID *int64
}

func (q *Queries) GetPlanningParamByNumber(ctx context.Context, arg GetPlanningParamByNumberParams) (PlanningParam, error) {
	row := q.db.QueryRow(ctx, getPlanningParamByNumber, arg.ParamNumber, arg.EnterpriseID)
	var i PlanningParam
	err := row.Scan(
		&i.ID,
		&i.ParamNumber,
		&i.ParamKey,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.EnterpriseID,
	)
	return i, err
}

const listPlanningParams = `-- name: ListPlanningParams :many
SELECT id, param_number, param_key, value, description, created_at, updated_at, updated_by, enterprise_id FROM planning_params WHERE enterprise_id = $1 ORDER BY param_number
`

func (q *Queries) ListPlanningParams(ctx context.Context, enterpriseID *int64) ([]PlanningParam, error) {
	rows, err := q.db.Query(ctx, listPlanningParams, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanningParam
	for rows.Next() {
		var i PlanningParam
		if err := rows.Scan(
			&i.ID,
			&i.ParamNumber,
			&i.ParamKey,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.EnterpriseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanningParam = `-- name: UpdatePlanningParam :one
UPDATE planning_params
SET value      = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE param_number = $1 AND enterprise_id = $4
RETURNING id, param_number, param_key, value, description, created_at, updated_at, updated_by, enterprise_id
`

type UpdatePlanningParamParams struct {
	ParamNumber  int32
	Value        string
	UpdatedBy    pgtype.UUID
	EnterpriseID *int64
}

func (q *Queries) UpdatePlanningParam(ctx context.Context, arg UpdatePlanningParamParams) (PlanningParam, error) {
	row := q.db.QueryRow(ctx, updatePlanningParam,
		arg.ParamNumber,
		arg.Value,
		arg.UpdatedBy,
		arg.EnterpriseID,
	)
	var i PlanningParam
	err := row.Scan(
		&i.ID,
		&i.ParamNumber,
		&i.ParamKey,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.EnterpriseID,
	)
	return i, err
}
