// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_mask.sql

package sqlc

import (
	"context"
)

const deleteProductMask = `-- name: DeleteProductMask :exec
DELETE FROM product_masks
WHERE id = $1
`

func (q *Queries) DeleteProductMask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProductMask, id)
	return err
}

const getProductMaskByProductCode = `-- name: GetProductMaskByProductCode :one
SELECT id, product_code, mask, mask_hash, created_by, created_at
FROM product_masks
WHERE product_code = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetProductMaskByProductCode(ctx context.Context, productCode string) (ItemMask, error) {
	row := q.db.QueryRow(ctx, getProductMaskByProductCode, productCode)
	var i ItemMask
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.Mask,
		&i.MaskHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
