// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production_plan.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductionPlan = `-- name: CreateProductionPlan :one
INSERT INTO production_plans (
    code, name, independent_demands, group_same_date_orders,
    planning_types, classification, class_item_codes, order_item_code,
    parameters, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, code, name, independent_demands, group_same_date_orders, planning_types, classification, class_item_codes, order_item_code, last_calculated_at, parameters, is_active, created_at, updated_at, created_by
`

type CreateProductionPlanParams struct {
	Code                int64
	Name                string
	IndependentDemands  string
	GroupSameDateOrders bool
	PlanningTypes       []string
	Classification      pgtype.Text
	ClassItemCodes      pgtype.Text
	OrderItemCode       *int64
	Parameters          []byte
	CreatedBy           pgtype.UUID
}

func (q *Queries) CreateProductionPlan(ctx context.Context, arg CreateProductionPlanParams) (ProductionPlan, error) {
	row := q.db.QueryRow(ctx, createProductionPlan,
		arg.Code,
		arg.Name,
		arg.IndependentDemands,
		arg.GroupSameDateOrders,
		arg.PlanningTypes,
		arg.Classification,
		arg.ClassItemCodes,
		arg.OrderItemCode,
		arg.Parameters,
		arg.CreatedBy,
	)
	var i ProductionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IndependentDemands,
		&i.GroupSameDateOrders,
		&i.PlanningTypes,
		&i.Classification,
		&i.ClassItemCodes,
		&i.OrderItemCode,
		&i.LastCalculatedAt,
		&i.Parameters,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteProductionPlan = `-- name: DeleteProductionPlan :exec
UPDATE production_plans SET is_active = FALSE, updated_at = NOW() WHERE code = $1
`

func (q *Queries) DeleteProductionPlan(ctx context.Context, code int64) error {
	_, err := q.db.Exec(ctx, deleteProductionPlan, code)
	return err
}

const getProductionPlanByCode = `-- name: GetProductionPlanByCode :one
SELECT id, code, name, independent_demands, group_same_date_orders, planning_types, classification, class_item_codes, order_item_code, last_calculated_at, parameters, is_active, created_at, updated_at, created_by FROM production_plans WHERE code = $1 AND is_active = TRUE
`

func (q *Queries) GetProductionPlanByCode(ctx context.Context, code int64) (ProductionPlan, error) {
	row := q.db.QueryRow(ctx, getProductionPlanByCode, code)
	var i ProductionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IndependentDemands,
		&i.GroupSameDateOrders,
		&i.PlanningTypes,
		&i.Classification,
		&i.ClassItemCodes,
		&i.OrderItemCode,
		&i.LastCalculatedAt,
		&i.Parameters,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listProductionPlans = `-- name: ListProductionPlans :many
SELECT id, code, name, independent_demands, group_same_date_orders, planning_types, classification, class_item_codes, order_item_code, last_calculated_at, parameters, is_active, created_at, updated_at, created_by FROM production_plans WHERE is_active = TRUE ORDER BY code
`

func (q *Queries) ListProductionPlans(ctx context.Context) ([]ProductionPlan, error) {
	rows, err := q.db.Query(ctx, listProductionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductionPlan
	for rows.Next() {
		var i ProductionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IndependentDemands,
			&i.GroupSameDateOrders,
			&i.PlanningTypes,
			&i.Classification,
			&i.ClassItemCodes,
			&i.OrderItemCode,
			&i.LastCalculatedAt,
			&i.Parameters,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductionPlan = `-- name: UpdateProductionPlan :one
UPDATE production_plans
SET name                  = $2,
    independent_demands   = $3,
    group_same_date_orders = $4,
    planning_types        = $5,
    classification        = $6,
    class_item_codes      = $7,
    order_item_code       = $8,
    parameters            = $9,
    updated_at            = NOW()
WHERE code = $1
RETURNING id, code, name, independent_demands, group_same_date_orders, planning_types, classification, class_item_codes, order_item_code, last_calculated_at, parameters, is_active, created_at, updated_at, created_by
`

type UpdateProductionPlanParams struct {
	Code                int64
	Name                string
	IndependentDemands  string
	GroupSameDateOrders bool
	PlanningTypes       []string
	Classification      pgtype.Text
	ClassItemCodes      pgtype.Text
	OrderItemCode       *int64
	Parameters          []byte
}

func (q *Queries) UpdateProductionPlan(ctx context.Context, arg UpdateProductionPlanParams) (ProductionPlan, error) {
	row := q.db.QueryRow(ctx, updateProductionPlan,
		arg.Code,
		arg.Name,
		arg.IndependentDemands,
		arg.GroupSameDateOrders,
		arg.PlanningTypes,
		arg.Classification,
		arg.ClassItemCodes,
		arg.OrderItemCode,
		arg.Parameters,
	)
	var i ProductionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IndependentDemands,
		&i.GroupSameDateOrders,
		&i.PlanningTypes,
		&i.Classification,
		&i.ClassItemCodes,
		&i.OrderItemCode,
		&i.LastCalculatedAt,
		&i.Parameters,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateProductionPlanLastCalculated = `-- name: UpdateProductionPlanLastCalculated :exec
UPDATE production_plans SET last_calculated_at = NOW(), updated_at = NOW() WHERE code = $1
`

func (q *Queries) UpdateProductionPlanLastCalculated(ctx context.Context, code int64) error {
	_, err := q.db.Exec(ctx, updateProductionPlanLastCalculated, code)
	return err
}
