// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchase_requisition.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchaseRequisition = `-- name: CreatePurchaseRequisition :one

INSERT INTO purchase_requisitions (code, enterprise_code, request_type_code, requester_employee_code, emission_date, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, enterprise_code, request_type_code, requester_employee_code, emission_date, status, notes, is_active, created_at, created_by, updated_at
`

type CreatePurchaseRequisitionParams struct {
	Code                  int64
	EnterpriseCode        int64
	RequestTypeCode       *int64
	RequesterEmployeeCode *int64
	EmissionDate          pgtype.Date
	Notes                 pgtype.Text
	CreatedBy             pgtype.UUID
}

// ─── Purchase Requisitions ────────────────────────────────────────────────────
func (q *Queries) CreatePurchaseRequisition(ctx context.Context, arg CreatePurchaseRequisitionParams) (PurchaseRequisition, error) {
	row := q.db.QueryRow(ctx, createPurchaseRequisition,
		arg.Code,
		arg.EnterpriseCode,
		arg.RequestTypeCode,
		arg.RequesterEmployeeCode,
		arg.EmissionDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var i PurchaseRequisition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.EnterpriseCode,
		&i.RequestTypeCode,
		&i.RequesterEmployeeCode,
		&i.EmissionDate,
		&i.Status,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createPurchaseRequisitionItem = `-- name: CreatePurchaseRequisitionItem :one

INSERT INTO purchase_requisition_items (
    requisition_code, sequence, item_code, quantity, uom, cost_center_code,
    accounting_account, suggested_price, delivery_date, application, utilization_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, requisition_code, sequence, item_code, quantity, attended_qty, cancelled_qty, uom, cost_center_code, accounting_account, suggested_price, delivery_date, application, utilization_type, status, is_active, created_at
`

type CreatePurchaseRequisitionItemParams struct {
	RequisitionCode   int64
	Sequence          int32
	ItemCode          int64
	Quantity          pgtype.Numeric
	Uom               pgtype.Text
	CostCenterCode    *int64
	AccountingAccount pgtype.Text
	SuggestedPrice    pgtype.Numeric
	DeliveryDate      pgtype.Date
	Application       pgtype.Text
	UtilizationType   pgtype.Text
}

// ─── Items ────────────────────────────────────────────────────────────────────
func (q *Queries) CreatePurchaseRequisitionItem(ctx context.Context, arg CreatePurchaseRequisitionItemParams) (PurchaseRequisitionItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseRequisitionItem,
		arg.RequisitionCode,
		arg.Sequence,
		arg.ItemCode,
		arg.Quantity,
		arg.Uom,
		arg.CostCenterCode,
		arg.AccountingAccount,
		arg.SuggestedPrice,
		arg.DeliveryDate,
		arg.Application,
		arg.UtilizationType,
	)
	var i PurchaseRequisitionItem
	err := row.Scan(
		&i.ID,
		&i.RequisitionCode,
		&i.Sequence,
		&i.ItemCode,
		&i.Quantity,
		&i.AttendedQty,
		&i.CancelledQty,
		&i.Uom,
		&i.CostCenterCode,
		&i.AccountingAccount,
		&i.SuggestedPrice,
		&i.DeliveryDate,
		&i.Application,
		&i.UtilizationType,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchaseRequisitionByCode = `-- name: GetPurchaseRequisitionByCode :one
SELECT id, code, enterprise_code, request_type_code, requester_employee_code, emission_date, status, notes, is_active, created_at, created_by, updated_at FROM purchase_requisitions WHERE code = $1
`

func (q *Queries) GetPurchaseRequisitionByCode(ctx context.Context, code int64) (PurchaseRequisition, error) {
	row := q.db.QueryRow(ctx, getPurchaseRequisitionByCode, code)
	var i PurchaseRequisition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.EnterpriseCode,
		&i.RequestTypeCode,
		&i.RequesterEmployeeCode,
		&i.EmissionDate,
		&i.Status,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseRequisitionItem = `-- name: GetPurchaseRequisitionItem :one
SELECT id, requisition_code, sequence, item_code, quantity, attended_qty, cancelled_qty, uom, cost_center_code, accounting_account, suggested_price, delivery_date, application, utilization_type, status, is_active, created_at FROM purchase_requisition_items WHERE id = $1
`

func (q *Queries) GetPurchaseRequisitionItem(ctx context.Context, id int64) (PurchaseRequisitionItem, error) {
	row := q.db.QueryRow(ctx, getPurchaseRequisitionItem, id)
	var i PurchaseRequisitionItem
	err := row.Scan(
		&i.ID,
		&i.RequisitionCode,
		&i.Sequence,
		&i.ItemCode,
		&i.Quantity,
		&i.AttendedQty,
		&i.CancelledQty,
		&i.Uom,
		&i.CostCenterCode,
		&i.AccountingAccount,
		&i.SuggestedPrice,
		&i.DeliveryDate,
		&i.Application,
		&i.UtilizationType,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listPurchaseRequisitionItems = `-- name: ListPurchaseRequisitionItems :many
SELECT id, requisition_code, sequence, item_code, quantity, attended_qty, cancelled_qty, uom, cost_center_code, accounting_account, suggested_price, delivery_date, application, utilization_type, status, is_active, created_at FROM purchase_requisition_items
WHERE requisition_code = $1 AND is_active = TRUE
ORDER BY sequence
`

func (q *Queries) ListPurchaseRequisitionItems(ctx context.Context, requisitionCode int64) ([]PurchaseRequisitionItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseRequisitionItems, requisitionCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRequisitionItem
	for rows.Next() {
		var i PurchaseRequisitionItem
		if err := rows.Scan(
			&i.ID,
			&i.RequisitionCode,
			&i.Sequence,
			&i.ItemCode,
			&i.Quantity,
			&i.AttendedQty,
			&i.CancelledQty,
			&i.Uom,
			&i.CostCenterCode,
			&i.AccountingAccount,
			&i.SuggestedPrice,
			&i.DeliveryDate,
			&i.Application,
			&i.UtilizationType,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseRequisitions = `-- name: ListPurchaseRequisitions :many
SELECT id, code, enterprise_code, request_type_code, requester_employee_code, emission_date, status, notes, is_active, created_at, created_by, updated_at FROM purchase_requisitions
WHERE is_active = TRUE AND ($1::BOOLEAN = FALSE OR status IN ('OPEN','PARTIAL'))
ORDER BY code DESC
`

func (q *Queries) ListPurchaseRequisitions(ctx context.Context, dollar_1 bool) ([]PurchaseRequisition, error) {
	rows, err := q.db.Query(ctx, listPurchaseRequisitions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRequisition
	for rows.Next() {
		var i PurchaseRequisition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.EnterpriseCode,
			&i.RequestTypeCode,
			&i.RequesterEmployeeCode,
			&i.EmissionDate,
			&i.Status,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPurchaseRequisitionCode = `-- name: NextPurchaseRequisitionCode :one
SELECT COALESCE(MAX(code), 0) + 1 AS next_code FROM purchase_requisitions
`

func (q *Queries) NextPurchaseRequisitionCode(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextPurchaseRequisitionCode)
	var next_code int32
	err := row.Scan(&next_code)
	return next_code, err
}

const registerRequisitionItemAttendance = `-- name: RegisterRequisitionItemAttendance :one
UPDATE purchase_requisition_items
SET attended_qty = attended_qty + $2,
    status = CASE
        WHEN attended_qty + $2 + cancelled_qty >= quantity THEN 'ATTENDED'
        WHEN attended_qty + $2 > 0 THEN 'PARTIAL'
        ELSE status
    END
WHERE id = $1
RETURNING id, requisition_code, sequence, item_code, quantity, attended_qty, cancelled_qty, uom, cost_center_code, accounting_account, suggested_price, delivery_date, application, utilization_type, status, is_active, created_at
`

type RegisterRequisitionItemAttendanceParams struct {
	ID          int64
	AttendedQty pgtype.Numeric
}

func (q *Queries) RegisterRequisitionItemAttendance(ctx context.Context, arg RegisterRequisitionItemAttendanceParams) (PurchaseRequisitionItem, error) {
	row := q.db.QueryRow(ctx, registerRequisitionItemAttendance, arg.ID, arg.AttendedQty)
	var i PurchaseRequisitionItem
	err := row.Scan(
		&i.ID,
		&i.RequisitionCode,
		&i.Sequence,
		&i.ItemCode,
		&i.Quantity,
		&i.AttendedQty,
		&i.CancelledQty,
		&i.Uom,
		&i.CostCenterCode,
		&i.AccountingAccount,
		&i.SuggestedPrice,
		&i.DeliveryDate,
		&i.Application,
		&i.UtilizationType,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updatePurchaseRequisitionStatus = `-- name: UpdatePurchaseRequisitionStatus :exec
UPDATE purchase_requisitions SET status = $2, updated_at = NOW() WHERE code = $1
`

type UpdatePurchaseRequisitionStatusParams struct {
	Code   int64
	Status string
}

func (q *Queries) UpdatePurchaseRequisitionStatus(ctx context.Context, arg UpdatePurchaseRequisitionStatusParams) error {
	_, err := q.db.Exec(ctx, updatePurchaseRequisitionStatus, arg.Code, arg.Status)
	return err
}
