// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    name,
    createdby
) VALUES (
    $1,
    $2
) RETURNING id, name, createdby, created_at
`

type CreateQuestionParams struct {
	Name      string
	Createdby pgtype.UUID
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, arg.Name, arg.Createdby)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const existsQuestionByName = `-- name: ExistsQuestionByName :one
SELECT EXISTS (
    SELECT 1 FROM questions WHERE name = $1
)
`

func (q *Queries) ExistsQuestionByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, existsQuestionByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findQuestionByName = `-- name: FindQuestionByName :many
SELECT id, name, createdby, created_at
FROM questions
WHERE name = $1
`

func (q *Queries) FindQuestionByName(ctx context.Context, name string) ([]Question, error) {
	rows, err := q.db.Query(ctx, findQuestionByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Createdby,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, name, createdby, created_at
FROM questions
WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.CreatedAt,
	)
	return i, err
}
