// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions_options.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestionOption = `-- name: CreateQuestionOption :one
INSERT INTO question_options (
    question_id,
    created_by,
    value
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, question_id, value, created_at, created_by
`

type CreateQuestionOptionParams struct {
	QuestionID int64
	CreatedBy  pgtype.UUID
	Value      string
}

func (q *Queries) CreateQuestionOption(ctx context.Context, arg CreateQuestionOptionParams) (QuestionOption, error) {
	row := q.db.QueryRow(ctx, createQuestionOption, arg.QuestionID, arg.CreatedBy, arg.Value)
	var i QuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Value,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteQuestionOption = `-- name: DeleteQuestionOption :exec
DELETE FROM question_options
WHERE id = $1
`

func (q *Queries) DeleteQuestionOption(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuestionOption, id)
	return err
}

const existsQuestionOptionByValue = `-- name: ExistsQuestionOptionByValue :one
SELECT EXISTS (
    SELECT 1
    FROM question_options
    WHERE value = $1
      AND question_id = $2
)
`

type ExistsQuestionOptionByValueParams struct {
	Value      string
	QuestionID int64
}

func (q *Queries) ExistsQuestionOptionByValue(ctx context.Context, arg ExistsQuestionOptionByValueParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsQuestionOptionByValue, arg.Value, arg.QuestionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getQuestionOptionByID = `-- name: GetQuestionOptionByID :one
SELECT id, question_id, value, created_at, created_by
FROM question_options
WHERE id = $1
`

func (q *Queries) GetQuestionOptionByID(ctx context.Context, id int64) (QuestionOption, error) {
	row := q.db.QueryRow(ctx, getQuestionOptionByID, id)
	var i QuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Value,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
