// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restriction_reason.sql

package sqlc

import (
	"context"
)

const createRestrictionReason = `-- name: CreateRestrictionReason :one
INSERT INTO restriction_reasons (description, situation, enterprise_id)
VALUES ($1, $2, $3)
RETURNING id, code, description, situation, created_at, updated_at, enterprise_id
`

type CreateRestrictionReasonParams struct {
	Description  string
	Situation    string
	EnterpriseID int64
}

func (q *Queries) CreateRestrictionReason(ctx context.Context, arg CreateRestrictionReasonParams) (RestrictionReason, error) {
	row := q.db.QueryRow(ctx, createRestrictionReason, arg.Description, arg.Situation, arg.EnterpriseID)
	var i RestrictionReason
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Situation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnterpriseID,
	)
	return i, err
}

const deleteRestrictionReason = `-- name: DeleteRestrictionReason :execrows
DELETE FROM restriction_reasons
WHERE code = $1 AND enterprise_id = $2
`

type DeleteRestrictionReasonParams struct {
	Code         int64
	EnterpriseID int64
}

func (q *Queries) DeleteRestrictionReason(ctx context.Context, arg DeleteRestrictionReasonParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRestrictionReason, arg.Code, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRestrictionReasonByCode = `-- name: GetRestrictionReasonByCode :one
SELECT id, code, description, situation, created_at, updated_at, enterprise_id FROM restriction_reasons
WHERE code = $1 AND enterprise_id = $2
`

type GetRestrictionReasonByCodeParams struct {
	Code         int64
	EnterpriseID int64
}

func (q *Queries) GetRestrictionReasonByCode(ctx context.Context, arg GetRestrictionReasonByCodeParams) (RestrictionReason, error) {
	row := q.db.QueryRow(ctx, getRestrictionReasonByCode, arg.Code, arg.EnterpriseID)
	var i RestrictionReason
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Situation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnterpriseID,
	)
	return i, err
}

const listRestrictionReasons = `-- name: ListRestrictionReasons :many
SELECT id, code, description, situation, created_at, updated_at, enterprise_id FROM restriction_reasons
WHERE enterprise_id = $1
ORDER BY code
`

func (q *Queries) ListRestrictionReasons(ctx context.Context, enterpriseID int64) ([]RestrictionReason, error) {
	rows, err := q.db.Query(ctx, listRestrictionReasons, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestrictionReason
	for rows.Next() {
		var i RestrictionReason
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Situation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnterpriseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestrictionReason = `-- name: UpdateRestrictionReason :one
UPDATE restriction_reasons
SET description = $2,
    situation   = $3,
    updated_at  = NOW()
WHERE code = $1 AND enterprise_id = $4
RETURNING id, code, description, situation, created_at, updated_at, enterprise_id
`

type UpdateRestrictionReasonParams struct {
	Code         int64
	Description  string
	Situation    string
	EnterpriseID int64
}

func (q *Queries) UpdateRestrictionReason(ctx context.Context, arg UpdateRestrictionReasonParams) (RestrictionReason, error) {
	row := q.db.QueryRow(ctx, updateRestrictionReason,
		arg.Code,
		arg.Description,
		arg.Situation,
		arg.EnterpriseID,
	)
	var i RestrictionReason
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Situation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnterpriseID,
	)
	return i, err
}
