// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_forecast.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultAppropriationTable = `-- name: ClearDefaultAppropriationTable :exec
UPDATE appropriation_tables SET is_default = FALSE
`

func (q *Queries) ClearDefaultAppropriationTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultAppropriationTable)
	return err
}

const createAppropriationTable = `-- name: CreateAppropriationTable :one
INSERT INTO appropriation_tables (
    description, monday_pct, tuesday_pct, wednesday_pct,
    thursday_pct, friday_pct, saturday_pct, sunday_pct,
    is_default, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, description, monday_pct, tuesday_pct, wednesday_pct, thursday_pct, friday_pct, saturday_pct, sunday_pct, is_default, created_at, updated_at, created_by
`

type CreateAppropriationTableParams struct {
	Description  string
	MondayPct    pgtype.Numeric
	TuesdayPct   pgtype.Numeric
	WednesdayPct pgtype.Numeric
	ThursdayPct  pgtype.Numeric
	FridayPct    pgtype.Numeric
	SaturdayPct  pgtype.Numeric
	SundayPct    pgtype.Numeric
	IsDefault    bool
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateAppropriationTable(ctx context.Context, arg CreateAppropriationTableParams) (AppropriationTable, error) {
	row := q.db.QueryRow(ctx, createAppropriationTable,
		arg.Description,
		arg.MondayPct,
		arg.TuesdayPct,
		arg.WednesdayPct,
		arg.ThursdayPct,
		arg.FridayPct,
		arg.SaturdayPct,
		arg.SundayPct,
		arg.IsDefault,
		arg.CreatedBy,
	)
	var i AppropriationTable
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.MondayPct,
		&i.TuesdayPct,
		&i.WednesdayPct,
		&i.ThursdayPct,
		&i.FridayPct,
		&i.SaturdayPct,
		&i.SundayPct,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createSalesForecast = `-- name: CreateSalesForecast :one
INSERT INTO sales_forecasts (item_code, mask, week, year, quantity, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, item_code, mask, week, year, quantity, created_by, created_at, updated_at
`

type CreateSalesForecastParams struct {
	ItemCode  int64
	Mask      pgtype.Text
	Week      int32
	Year      int32
	Quantity  pgtype.Numeric
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateSalesForecast(ctx context.Context, arg CreateSalesForecastParams) (SalesForecast, error) {
	row := q.db.QueryRow(ctx, createSalesForecast,
		arg.ItemCode,
		arg.Mask,
		arg.Week,
		arg.Year,
		arg.Quantity,
		arg.CreatedBy,
	)
	var i SalesForecast
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.Mask,
		&i.Week,
		&i.Year,
		&i.Quantity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesForecastBlock = `-- name: CreateSalesForecastBlock :one
INSERT INTO sales_forecast_blocks (start_date, end_date, reason, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, start_date, end_date, reason, created_at, created_by
`

type CreateSalesForecastBlockParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Reason    pgtype.Text
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateSalesForecastBlock(ctx context.Context, arg CreateSalesForecastBlockParams) (SalesForecastBlock, error) {
	row := q.db.QueryRow(ctx, createSalesForecastBlock,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
		arg.CreatedBy,
	)
	var i SalesForecastBlock
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteSalesForecast = `-- name: DeleteSalesForecast :exec
DELETE FROM sales_forecasts WHERE id = $1
`

func (q *Queries) DeleteSalesForecast(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSalesForecast, id)
	return err
}

const deleteSalesForecastBlock = `-- name: DeleteSalesForecastBlock :exec
DELETE FROM sales_forecast_blocks WHERE id = $1
`

func (q *Queries) DeleteSalesForecastBlock(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSalesForecastBlock, id)
	return err
}

const getDefaultAppropriationTable = `-- name: GetDefaultAppropriationTable :one
SELECT id, description, monday_pct, tuesday_pct, wednesday_pct, thursday_pct, friday_pct, saturday_pct, sunday_pct, is_default, created_at, updated_at, created_by FROM appropriation_tables WHERE is_default = TRUE LIMIT 1
`

func (q *Queries) GetDefaultAppropriationTable(ctx context.Context) (AppropriationTable, error) {
	row := q.db.QueryRow(ctx, getDefaultAppropriationTable)
	var i AppropriationTable
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.MondayPct,
		&i.TuesdayPct,
		&i.WednesdayPct,
		&i.ThursdayPct,
		&i.FridayPct,
		&i.SaturdayPct,
		&i.SundayPct,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSalesForecastsByItem = `-- name: GetSalesForecastsByItem :many
SELECT id, item_code, mask, week, year, quantity, created_by, created_at, updated_at FROM sales_forecasts WHERE item_code = $1 ORDER BY year, week
`

func (q *Queries) GetSalesForecastsByItem(ctx context.Context, itemCode int64) ([]SalesForecast, error) {
	rows, err := q.db.Query(ctx, getSalesForecastsByItem, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesForecast
	for rows.Next() {
		var i SalesForecast
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.Mask,
			&i.Week,
			&i.Year,
			&i.Quantity,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isForecastBlocked = `-- name: IsForecastBlocked :one
SELECT EXISTS(
    SELECT 1 FROM sales_forecast_blocks
    WHERE start_date <= $1 AND end_date >= $1
) AS blocked
`

func (q *Queries) IsForecastBlocked(ctx context.Context, startDate pgtype.Date) (bool, error) {
	row := q.db.QueryRow(ctx, isForecastBlocked, startDate)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listAppropriationTables = `-- name: ListAppropriationTables :many
SELECT id, description, monday_pct, tuesday_pct, wednesday_pct, thursday_pct, friday_pct, saturday_pct, sunday_pct, is_default, created_at, updated_at, created_by FROM appropriation_tables ORDER BY id
`

func (q *Queries) ListAppropriationTables(ctx context.Context) ([]AppropriationTable, error) {
	rows, err := q.db.Query(ctx, listAppropriationTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppropriationTable
	for rows.Next() {
		var i AppropriationTable
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.MondayPct,
			&i.TuesdayPct,
			&i.WednesdayPct,
			&i.ThursdayPct,
			&i.FridayPct,
			&i.SaturdayPct,
			&i.SundayPct,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesForecastBlocks = `-- name: ListSalesForecastBlocks :many
SELECT id, start_date, end_date, reason, created_at, created_by FROM sales_forecast_blocks ORDER BY start_date
`

func (q *Queries) ListSalesForecastBlocks(ctx context.Context) ([]SalesForecastBlock, error) {
	rows, err := q.db.Query(ctx, listSalesForecastBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesForecastBlock
	for rows.Next() {
		var i SalesForecastBlock
		if err := rows.Scan(
			&i.ID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesForecastsByYear = `-- name: ListSalesForecastsByYear :many
SELECT id, item_code, mask, week, year, quantity, created_by, created_at, updated_at FROM sales_forecasts WHERE year = $1 ORDER BY item_code, week
`

func (q *Queries) ListSalesForecastsByYear(ctx context.Context, year int32) ([]SalesForecast, error) {
	rows, err := q.db.Query(ctx, listSalesForecastsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesForecast
	for rows.Next() {
		var i SalesForecast
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.Mask,
			&i.Week,
			&i.Year,
			&i.Quantity,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSingleDefaultAppropriationTable = `-- name: SetSingleDefaultAppropriationTable :exec
UPDATE appropriation_tables SET is_default = TRUE WHERE id = $1
`

func (q *Queries) SetSingleDefaultAppropriationTable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setSingleDefaultAppropriationTable, id)
	return err
}

const updateAppropriationTable = `-- name: UpdateAppropriationTable :one
UPDATE appropriation_tables
SET description   = $2,
    monday_pct    = $3,
    tuesday_pct   = $4,
    wednesday_pct = $5,
    thursday_pct  = $6,
    friday_pct    = $7,
    saturday_pct  = $8,
    sunday_pct    = $9,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, description, monday_pct, tuesday_pct, wednesday_pct, thursday_pct, friday_pct, saturday_pct, sunday_pct, is_default, created_at, updated_at, created_by
`

type UpdateAppropriationTableParams struct {
	ID           int64
	Description  string
	MondayPct    pgtype.Numeric
	TuesdayPct   pgtype.Numeric
	WednesdayPct pgtype.Numeric
	ThursdayPct  pgtype.Numeric
	FridayPct    pgtype.Numeric
	SaturdayPct  pgtype.Numeric
	SundayPct    pgtype.Numeric
}

func (q *Queries) UpdateAppropriationTable(ctx context.Context, arg UpdateAppropriationTableParams) (AppropriationTable, error) {
	row := q.db.QueryRow(ctx, updateAppropriationTable,
		arg.ID,
		arg.Description,
		arg.MondayPct,
		arg.TuesdayPct,
		arg.WednesdayPct,
		arg.ThursdayPct,
		arg.FridayPct,
		arg.SaturdayPct,
		arg.SundayPct,
	)
	var i AppropriationTable
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.MondayPct,
		&i.TuesdayPct,
		&i.WednesdayPct,
		&i.ThursdayPct,
		&i.FridayPct,
		&i.SaturdayPct,
		&i.SundayPct,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateSalesForecast = `-- name: UpdateSalesForecast :one
UPDATE sales_forecasts
SET quantity = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, item_code, mask, week, year, quantity, created_by, created_at, updated_at
`

type UpdateSalesForecastParams struct {
	ID       int64
	Quantity pgtype.Numeric
}

func (q *Queries) UpdateSalesForecast(ctx context.Context, arg UpdateSalesForecastParams) (SalesForecast, error) {
	row := q.db.QueryRow(ctx, updateSalesForecast, arg.ID, arg.Quantity)
	var i SalesForecast
	err := row.Scan(
		&i.ID,
		&i.ItemCode,
		&i.Mask,
		&i.Week,
		&i.Year,
		&i.Quantity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
