// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_division.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSalesDivision = `-- name: CreateSalesDivision :one
INSERT INTO sales_divisions (
    code, description, commercial_analysis, financial_analysis,
    is_technical_assistance, consider_delivery_promise, consider_mrp,
    allow_outside_limits, minimum_delivery_days, financial_delay_days,
    pis_percentage, cofins_percentage, parent_division_id, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, code, description, commercial_analysis, financial_analysis, is_technical_assistance, consider_delivery_promise, consider_mrp, allow_outside_limits, minimum_delivery_days, financial_delay_days, pis_percentage, cofins_percentage, parent_division_id, is_active, created_at, updated_at, created_by
`

type CreateSalesDivisionParams struct {
	Code                    int64
	Description             string
	CommercialAnalysis      SalesDivisionAnalysisEnum
	FinancialAnalysis       SalesDivisionAnalysisEnum
	IsTechnicalAssistance   bool
	ConsiderDeliveryPromise bool
	ConsiderMrp             bool
	AllowOutsideLimits      bool
	MinimumDeliveryDays     int32
	FinancialDelayDays      int32
	PisPercentage           pgtype.Numeric
	CofinsPercentage        pgtype.Numeric
	ParentDivisionID        *int64
	CreatedBy               pgtype.UUID
}

func (q *Queries) CreateSalesDivision(ctx context.Context, arg CreateSalesDivisionParams) (SalesDivision, error) {
	row := q.db.QueryRow(ctx, createSalesDivision,
		arg.Code,
		arg.Description,
		arg.CommercialAnalysis,
		arg.FinancialAnalysis,
		arg.IsTechnicalAssistance,
		arg.ConsiderDeliveryPromise,
		arg.ConsiderMrp,
		arg.AllowOutsideLimits,
		arg.MinimumDeliveryDays,
		arg.FinancialDelayDays,
		arg.PisPercentage,
		arg.CofinsPercentage,
		arg.ParentDivisionID,
		arg.CreatedBy,
	)
	var i SalesDivision
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.CommercialAnalysis,
		&i.FinancialAnalysis,
		&i.IsTechnicalAssistance,
		&i.ConsiderDeliveryPromise,
		&i.ConsiderMrp,
		&i.AllowOutsideLimits,
		&i.MinimumDeliveryDays,
		&i.FinancialDelayDays,
		&i.PisPercentage,
		&i.CofinsPercentage,
		&i.ParentDivisionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteSalesDivision = `-- name: DeleteSalesDivision :exec
UPDATE sales_divisions SET is_active = FALSE, updated_at = NOW() WHERE code = $1
`

func (q *Queries) DeleteSalesDivision(ctx context.Context, code int64) error {
	_, err := q.db.Exec(ctx, deleteSalesDivision, code)
	return err
}

const getSalesDivisionByCode = `-- name: GetSalesDivisionByCode :one
SELECT id, code, description, commercial_analysis, financial_analysis, is_technical_assistance, consider_delivery_promise, consider_mrp, allow_outside_limits, minimum_delivery_days, financial_delay_days, pis_percentage, cofins_percentage, parent_division_id, is_active, created_at, updated_at, created_by FROM sales_divisions WHERE code = $1
`

func (q *Queries) GetSalesDivisionByCode(ctx context.Context, code int64) (SalesDivision, error) {
	row := q.db.QueryRow(ctx, getSalesDivisionByCode, code)
	var i SalesDivision
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.CommercialAnalysis,
		&i.FinancialAnalysis,
		&i.IsTechnicalAssistance,
		&i.ConsiderDeliveryPromise,
		&i.ConsiderMrp,
		&i.AllowOutsideLimits,
		&i.MinimumDeliveryDays,
		&i.FinancialDelayDays,
		&i.PisPercentage,
		&i.CofinsPercentage,
		&i.ParentDivisionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listActiveSalesDivisions = `-- name: ListActiveSalesDivisions :many
SELECT id, code, description, commercial_analysis, financial_analysis, is_technical_assistance, consider_delivery_promise, consider_mrp, allow_outside_limits, minimum_delivery_days, financial_delay_days, pis_percentage, cofins_percentage, parent_division_id, is_active, created_at, updated_at, created_by FROM sales_divisions WHERE is_active = TRUE ORDER BY code
`

func (q *Queries) ListActiveSalesDivisions(ctx context.Context) ([]SalesDivision, error) {
	rows, err := q.db.Query(ctx, listActiveSalesDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesDivision
	for rows.Next() {
		var i SalesDivision
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.CommercialAnalysis,
			&i.FinancialAnalysis,
			&i.IsTechnicalAssistance,
			&i.ConsiderDeliveryPromise,
			&i.ConsiderMrp,
			&i.AllowOutsideLimits,
			&i.MinimumDeliveryDays,
			&i.FinancialDelayDays,
			&i.PisPercentage,
			&i.CofinsPercentage,
			&i.ParentDivisionID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesDivisions = `-- name: ListSalesDivisions :many
SELECT id, code, description, commercial_analysis, financial_analysis, is_technical_assistance, consider_delivery_promise, consider_mrp, allow_outside_limits, minimum_delivery_days, financial_delay_days, pis_percentage, cofins_percentage, parent_division_id, is_active, created_at, updated_at, created_by FROM sales_divisions ORDER BY code
`

func (q *Queries) ListSalesDivisions(ctx context.Context) ([]SalesDivision, error) {
	rows, err := q.db.Query(ctx, listSalesDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesDivision
	for rows.Next() {
		var i SalesDivision
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.CommercialAnalysis,
			&i.FinancialAnalysis,
			&i.IsTechnicalAssistance,
			&i.ConsiderDeliveryPromise,
			&i.ConsiderMrp,
			&i.AllowOutsideLimits,
			&i.MinimumDeliveryDays,
			&i.FinancialDelayDays,
			&i.PisPercentage,
			&i.CofinsPercentage,
			&i.ParentDivisionID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSalesDivision = `-- name: UpdateSalesDivision :one
UPDATE sales_divisions
SET description              = $2,
    commercial_analysis      = $3,
    financial_analysis       = $4,
    is_technical_assistance  = $5,
    consider_delivery_promise = $6,
    consider_mrp             = $7,
    allow_outside_limits     = $8,
    minimum_delivery_days    = $9,
    financial_delay_days     = $10,
    pis_percentage           = $11,
    cofins_percentage        = $12,
    parent_division_id       = $13,
    updated_at               = NOW()
WHERE code = $1
RETURNING id, code, description, commercial_analysis, financial_analysis, is_technical_assistance, consider_delivery_promise, consider_mrp, allow_outside_limits, minimum_delivery_days, financial_delay_days, pis_percentage, cofins_percentage, parent_division_id, is_active, created_at, updated_at, created_by
`

type UpdateSalesDivisionParams struct {
	Code                    int64
	Description             string
	CommercialAnalysis      SalesDivisionAnalysisEnum
	FinancialAnalysis       SalesDivisionAnalysisEnum
	IsTechnicalAssistance   bool
	ConsiderDeliveryPromise bool
	ConsiderMrp             bool
	AllowOutsideLimits      bool
	MinimumDeliveryDays     int32
	FinancialDelayDays      int32
	PisPercentage           pgtype.Numeric
	CofinsPercentage        pgtype.Numeric
	ParentDivisionID        *int64
}

func (q *Queries) UpdateSalesDivision(ctx context.Context, arg UpdateSalesDivisionParams) (SalesDivision, error) {
	row := q.db.QueryRow(ctx, updateSalesDivision,
		arg.Code,
		arg.Description,
		arg.CommercialAnalysis,
		arg.FinancialAnalysis,
		arg.IsTechnicalAssistance,
		arg.ConsiderDeliveryPromise,
		arg.ConsiderMrp,
		arg.AllowOutsideLimits,
		arg.MinimumDeliveryDays,
		arg.FinancialDelayDays,
		arg.PisPercentage,
		arg.CofinsPercentage,
		arg.ParentDivisionID,
	)
	var i SalesDivision
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.CommercialAnalysis,
		&i.FinancialAnalysis,
		&i.IsTechnicalAssistance,
		&i.ConsiderDeliveryPromise,
		&i.ConsiderMrp,
		&i.AllowOutsideLimits,
		&i.MinimumDeliveryDays,
		&i.FinancialDelayDays,
		&i.PisPercentage,
		&i.CofinsPercentage,
		&i.ParentDivisionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
