// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: structure.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStructureComponent = `-- name: CreateStructureComponent :one
INSERT INTO item_structures (
    parent_code,
    child_code,
    parent_mask,
    quantity,
    unit_of_measurement,
    loss_percentage,
    sequence,
    health,
    notes,
    created_by
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
         )
    RETURNING id, parent_mask, quantity, unit_of_measurement, loss_percentage, sequence, notes, is_active, created_by, created_at, updated_at, parent_code, child_code, health
`

type CreateStructureComponentParams struct {
	ParentCode        int64
	ChildCode         int64
	ParentMask        pgtype.Text
	Quantity          float64
	UnitOfMeasurement UnitOfMeasurementEnum
	LossPercentage    float64
	Sequence          int32
	Health            HealthEnum
	Notes             pgtype.Text
	CreatedBy         pgtype.UUID
}

func (q *Queries) CreateStructureComponent(ctx context.Context, arg CreateStructureComponentParams) (ItemStructure, error) {
	row := q.db.QueryRow(ctx, createStructureComponent,
		arg.ParentCode,
		arg.ChildCode,
		arg.ParentMask,
		arg.Quantity,
		arg.UnitOfMeasurement,
		arg.LossPercentage,
		arg.Sequence,
		arg.Health,
		arg.Notes,
		arg.CreatedBy,
	)
	var i ItemStructure
	err := row.Scan(
		&i.ID,
		&i.ParentMask,
		&i.Quantity,
		&i.UnitOfMeasurement,
		&i.LossPercentage,
		&i.Sequence,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentCode,
		&i.ChildCode,
		&i.Health,
	)
	return i, err
}

const deactivateStructureComponent = `-- name: DeactivateStructureComponent :exec
UPDATE item_structures
SET
    is_active  = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStructureComponent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateStructureComponent, id)
	return err
}

const getAllDirectChildren = `-- name: GetAllDirectChildren :many
SELECT
    s.id,
    s.parent_code,
    s.child_code,
    i.pdm_description_technique AS child_description,
    s.parent_mask,
    s.quantity,
    s.loss_percentage,
    s.unit_of_measurement,
    s.health,
    s.sequence,
    s.notes,
    s.is_active,
    s.created_by,
    s.created_at,
    s.updated_at
FROM item_structures s
         JOIN items i ON i.code = s.child_code
WHERE s.parent_code = $1
  AND s.is_active = TRUE
ORDER BY s.sequence, s.id
`

type GetAllDirectChildrenRow struct {
	ID                int64
	ParentCode        int64
	ChildCode         int64
	ChildDescription  string
	ParentMask        pgtype.Text
	Quantity          float64
	LossPercentage    float64
	UnitOfMeasurement UnitOfMeasurementEnum
	Health            HealthEnum
	Sequence          int32
	Notes             pgtype.Text
	IsActive          bool
	CreatedBy         pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetAllDirectChildren(ctx context.Context, parentCode int64) ([]GetAllDirectChildrenRow, error) {
	rows, err := q.db.Query(ctx, getAllDirectChildren, parentCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDirectChildrenRow
	for rows.Next() {
		var i GetAllDirectChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentCode,
			&i.ChildCode,
			&i.ChildDescription,
			&i.ParentMask,
			&i.Quantity,
			&i.LossPercentage,
			&i.UnitOfMeasurement,
			&i.Health,
			&i.Sequence,
			&i.Notes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectChildrenForMask = `-- name: GetDirectChildrenForMask :many
SELECT
    s.id,
    s.parent_code,
    s.child_code,
    s.parent_mask,
    s.quantity,
    s.loss_percentage,
    s.unit_of_measurement,
    s.health,
    s.sequence,
    s.notes,
    s.is_active,
    s.created_by,
    s.created_at,
    s.updated_at,
    i.pdm_description_technique AS child_description
FROM item_structures s
         JOIN items i ON i.code = s.child_code
WHERE s.parent_code = $1
  AND s.is_active = TRUE
  AND (
    s.parent_mask IS NULL
        OR s.parent_mask = $2
    )
ORDER BY
    CASE WHEN s.parent_mask IS NOT NULL THEN 0 ELSE 1 END,
    s.sequence,
    s.id
`

type GetDirectChildrenForMaskParams struct {
	ParentCode int64
	ParentMask pgtype.Text
}

type GetDirectChildrenForMaskRow struct {
	ID                int64
	ParentCode        int64
	ChildCode         int64
	ParentMask        pgtype.Text
	Quantity          float64
	LossPercentage    float64
	UnitOfMeasurement UnitOfMeasurementEnum
	Health            HealthEnum
	Sequence          int32
	Notes             pgtype.Text
	IsActive          bool
	CreatedBy         pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ChildDescription  string
}

func (q *Queries) GetDirectChildrenForMask(ctx context.Context, arg GetDirectChildrenForMaskParams) ([]GetDirectChildrenForMaskRow, error) {
	rows, err := q.db.Query(ctx, getDirectChildrenForMask, arg.ParentCode, arg.ParentMask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDirectChildrenForMaskRow
	for rows.Next() {
		var i GetDirectChildrenForMaskRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentCode,
			&i.ChildCode,
			&i.ParentMask,
			&i.Quantity,
			&i.LossPercentage,
			&i.UnitOfMeasurement,
			&i.Health,
			&i.Sequence,
			&i.Notes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChildDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenericChildren = `-- name: GetGenericChildren :many
SELECT id, parent_mask, quantity, unit_of_measurement, loss_percentage, sequence, notes, is_active, created_by, created_at, updated_at, parent_code, child_code, health
FROM item_structures
WHERE parent_code = $1
  AND parent_mask IS NULL
  AND is_active = TRUE
ORDER BY sequence, id
`

func (q *Queries) GetGenericChildren(ctx context.Context, parentCode int64) ([]ItemStructure, error) {
	rows, err := q.db.Query(ctx, getGenericChildren, parentCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemStructure
	for rows.Next() {
		var i ItemStructure
		if err := rows.Scan(
			&i.ID,
			&i.ParentMask,
			&i.Quantity,
			&i.UnitOfMeasurement,
			&i.LossPercentage,
			&i.Sequence,
			&i.Notes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentCode,
			&i.ChildCode,
			&i.Health,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemCodeAndDescription = `-- name: GetItemCodeAndDescription :one
SELECT
    i.code::BIGINT AS code,
    i.pdm_description_technique AS description
FROM items i
WHERE i.code = $1
    LIMIT 1
`

type GetItemCodeAndDescriptionRow struct {
	Code        int64
	Description string
}

func (q *Queries) GetItemCodeAndDescription(ctx context.Context, code int64) (GetItemCodeAndDescriptionRow, error) {
	row := q.db.QueryRow(ctx, getItemCodeAndDescription, code)
	var i GetItemCodeAndDescriptionRow
	err := row.Scan(&i.Code, &i.Description)
	return i, err
}

const getItemMaskAnswersByValue = `-- name: GetItemMaskAnswersByValue :many
SELECT
    ima.question_id,
    ima.position,
    ima.option_id
FROM item_masks im
         JOIN item_mask_answers ima ON ima.mask_id = im.id
WHERE im.item_code = $1
  AND im.mask = $2
ORDER BY ima.position
`

type GetItemMaskAnswersByValueParams struct {
	ItemCode int64
	Mask     string
}

type GetItemMaskAnswersByValueRow struct {
	QuestionID int64
	Position   int32
	OptionID   int64
}

func (q *Queries) GetItemMaskAnswersByValue(ctx context.Context, arg GetItemMaskAnswersByValueParams) ([]GetItemMaskAnswersByValueRow, error) {
	rows, err := q.db.Query(ctx, getItemMaskAnswersByValue, arg.ItemCode, arg.Mask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemMaskAnswersByValueRow
	for rows.Next() {
		var i GetItemMaskAnswersByValueRow
		if err := rows.Scan(&i.QuestionID, &i.Position, &i.OptionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemQuestions = `-- name: GetItemQuestions :many
SELECT
    iq.question_id,
    iq.position
FROM item_questions iq
WHERE iq.item_code = $1
ORDER BY iq.position
`

type GetItemQuestionsRow struct {
	QuestionID int64
	Position   int32
}

func (q *Queries) GetItemQuestions(ctx context.Context, itemCode int64) ([]GetItemQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getItemQuestions, itemCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemQuestionsRow
	for rows.Next() {
		var i GetItemQuestionsRow
		if err := rows.Scan(&i.QuestionID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStructureComponentByID = `-- name: GetStructureComponentByID :one
SELECT id, parent_mask, quantity, unit_of_measurement, loss_percentage, sequence, notes, is_active, created_by, created_at, updated_at, parent_code, child_code, health
FROM item_structures
WHERE id = $1
`

func (q *Queries) GetStructureComponentByID(ctx context.Context, id int64) (ItemStructure, error) {
	row := q.db.QueryRow(ctx, getStructureComponentByID, id)
	var i ItemStructure
	err := row.Scan(
		&i.ID,
		&i.ParentMask,
		&i.Quantity,
		&i.UnitOfMeasurement,
		&i.LossPercentage,
		&i.Sequence,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentCode,
		&i.ChildCode,
		&i.Health,
	)
	return i, err
}

const hasCyclicReference = `-- name: HasCyclicReference :one
SELECT has_cycle($1, $2) AS has_cycle
`

type HasCyclicReferenceParams struct {
	StartCode  int64
	TargetCode int64
}

func (q *Queries) HasCyclicReference(ctx context.Context, arg HasCyclicReferenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCyclicReference, arg.StartCode, arg.TargetCode)
	var has_cycle bool
	err := row.Scan(&has_cycle)
	return has_cycle, err
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS (
    SELECT 1
    FROM items
    WHERE code = $1
) AS "exists"
`

func (q *Queries) ItemExists(ctx context.Context, code int64) (bool, error) {
	row := q.db.QueryRow(ctx, itemExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sequenceExists = `-- name: SequenceExists :one
SELECT EXISTS (
    SELECT 1
    FROM item_structures
    WHERE parent_code = $1
      AND sequence    = $2
      AND is_active   = TRUE
) AS "exists"
`

type SequenceExistsParams struct {
	ParentCode int64
	Sequence   int32
}

func (q *Queries) SequenceExists(ctx context.Context, arg SequenceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sequenceExists, arg.ParentCode, arg.Sequence)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStructureComponent = `-- name: UpdateStructureComponent :one
UPDATE item_structures
SET
    quantity            = $4,
    unit_of_measurement = $5,
    loss_percentage     = $6,
    sequence            = $7,
    health              = $8,
    notes               = $9,
    updated_at          = NOW()
WHERE parent_code = $1
  AND child_code  = $2
  AND (
    parent_mask = $3
        OR (parent_mask IS NULL AND $3 IS NULL)
    )
  AND is_active = TRUE
    RETURNING id, parent_mask, quantity, unit_of_measurement, loss_percentage, sequence, notes, is_active, created_by, created_at, updated_at, parent_code, child_code, health
`

type UpdateStructureComponentParams struct {
	ParentCode        int64
	ChildCode         int64
	ParentMask        pgtype.Text
	Quantity          float64
	UnitOfMeasurement UnitOfMeasurementEnum
	LossPercentage    float64
	Sequence          int32
	Health            HealthEnum
	Notes             pgtype.Text
}

func (q *Queries) UpdateStructureComponent(ctx context.Context, arg UpdateStructureComponentParams) (ItemStructure, error) {
	row := q.db.QueryRow(ctx, updateStructureComponent,
		arg.ParentCode,
		arg.ChildCode,
		arg.ParentMask,
		arg.Quantity,
		arg.UnitOfMeasurement,
		arg.LossPercentage,
		arg.Sequence,
		arg.Health,
		arg.Notes,
	)
	var i ItemStructure
	err := row.Scan(
		&i.ID,
		&i.ParentMask,
		&i.Quantity,
		&i.UnitOfMeasurement,
		&i.LossPercentage,
		&i.Sequence,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentCode,
		&i.ChildCode,
		&i.Health,
	)
	return i, err
}
