// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplier.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockSupplier = `-- name: BlockSupplier :exec
UPDATE suppliers SET blocked = TRUE, block_reason = $2, updated_at = NOW() WHERE code = $1
`

type BlockSupplierParams struct {
	Code        int64
	BlockReason pgtype.Text
}

func (q *Queries) BlockSupplier(ctx context.Context, arg BlockSupplierParams) error {
	_, err := q.db.Exec(ctx, blockSupplier, arg.Code, arg.BlockReason)
	return err
}

const createSupplier = `-- name: CreateSupplier :one

INSERT INTO suppliers (
    code, corporate_code, is_active, is_representative, is_customer,
    name, trade_name, person_type, document_type, document_number,
    state_registration, municipal_registration, supplier_type_id,
    payment_condition_id, carrier_id, region_id, freight_type, register_date,
    viticola_obligation, gln_code, agriculture_ministry_registration,
    icms_contributor, is_mei, tracking_platform, homologated, created_by
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20, $21,
    $22, $23, $24, $25, $26
)
RETURNING id, code, corporate_code, is_active, is_representative, is_customer, name, trade_name, person_type, document_type, document_number, state_registration, municipal_registration, supplier_type_id, payment_condition_id, carrier_id, region_id, freight_type, register_date, viticola_obligation, gln_code, agriculture_ministry_registration, icms_contributor, is_mei, tracking_platform, homologated, last_sefaz_query, billing_receipt_status, last_sefaz_update, sefaz_update_user, blocked, block_reason, created_at, created_by, updated_at
`

type CreateSupplierParams struct {
	Code                            int64
	CorporateCode                   *int64
	IsActive                        bool
	IsRepresentative                bool
	IsCustomer                      bool
	Name                            string
	TradeName                       pgtype.Text
	PersonType                      string
	DocumentType                    string
	DocumentNumber                  string
	StateRegistration               pgtype.Text
	MunicipalRegistration           pgtype.Text
	SupplierTypeID                  *int64
	PaymentConditionID              *int64
	CarrierID                       *int64
	RegionID                        *int64
	FreightType                     string
	RegisterDate                    pgtype.Date
	ViticolaObligation              string
	GlnCode                         pgtype.Text
	AgricultureMinistryRegistration pgtype.Text
	IcmsContributor                 string
	IsMei                           bool
	TrackingPlatform                string
	Homologated                     bool
	CreatedBy                       pgtype.UUID
}

// ─── Suppliers ────────────────────────────────────────────────────────────────
func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Code,
		arg.CorporateCode,
		arg.IsActive,
		arg.IsRepresentative,
		arg.IsCustomer,
		arg.Name,
		arg.TradeName,
		arg.PersonType,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.StateRegistration,
		arg.MunicipalRegistration,
		arg.SupplierTypeID,
		arg.PaymentConditionID,
		arg.CarrierID,
		arg.RegionID,
		arg.FreightType,
		arg.RegisterDate,
		arg.ViticolaObligation,
		arg.GlnCode,
		arg.AgricultureMinistryRegistration,
		arg.IcmsContributor,
		arg.IsMei,
		arg.TrackingPlatform,
		arg.Homologated,
		arg.CreatedBy,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CorporateCode,
		&i.IsActive,
		&i.IsRepresentative,
		&i.IsCustomer,
		&i.Name,
		&i.TradeName,
		&i.PersonType,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.StateRegistration,
		&i.MunicipalRegistration,
		&i.SupplierTypeID,
		&i.PaymentConditionID,
		&i.CarrierID,
		&i.RegionID,
		&i.FreightType,
		&i.RegisterDate,
		&i.ViticolaObligation,
		&i.GlnCode,
		&i.AgricultureMinistryRegistration,
		&i.IcmsContributor,
		&i.IsMei,
		&i.TrackingPlatform,
		&i.Homologated,
		&i.LastSefazQuery,
		&i.BillingReceiptStatus,
		&i.LastSefazUpdate,
		&i.SefazUpdateUser,
		&i.Blocked,
		&i.BlockReason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createSupplierAddress = `-- name: CreateSupplierAddress :one

INSERT INTO supplier_addresses (
    supplier_id, address_type, zip_code, street, number, complement,
    neighborhood, city, uf, country, is_default
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, supplier_id, address_type, zip_code, street, number, complement, neighborhood, city, uf, country, is_default, created_at
`

type CreateSupplierAddressParams struct {
	SupplierID   int64
	AddressType  string
	ZipCode      pgtype.Text
	Street       pgtype.Text
	Number       pgtype.Text
	Complement   pgtype.Text
	Neighborhood pgtype.Text
	City         pgtype.Text
	Uf           pgtype.Text
	Country      string
	IsDefault    bool
}

// ─── Supplier Addresses ─────────────────────────────────────────────────────────
func (q *Queries) CreateSupplierAddress(ctx context.Context, arg CreateSupplierAddressParams) (SupplierAddress, error) {
	row := q.db.QueryRow(ctx, createSupplierAddress,
		arg.SupplierID,
		arg.AddressType,
		arg.ZipCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.Neighborhood,
		arg.City,
		arg.Uf,
		arg.Country,
		arg.IsDefault,
	)
	var i SupplierAddress
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.AddressType,
		&i.ZipCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.Uf,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierContact = `-- name: CreateSupplierContact :one

INSERT INTO supplier_contacts (
    supplier_id, contact_type_id, name, position, department, ranking,
    observation, purchase_order_tag
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, supplier_id, contact_type_id, name, position, department, ranking, observation, purchase_order_tag, is_active, created_at
`

type CreateSupplierContactParams struct {
	SupplierID       int64
	ContactTypeID    *int64
	Name             string
	Position         pgtype.Text
	Department       pgtype.Text
	Ranking          int32
	Observation      pgtype.Text
	PurchaseOrderTag pgtype.Text
}

// ─── Supplier Contacts ──────────────────────────────────────────────────────────
func (q *Queries) CreateSupplierContact(ctx context.Context, arg CreateSupplierContactParams) (SupplierContact, error) {
	row := q.db.QueryRow(ctx, createSupplierContact,
		arg.SupplierID,
		arg.ContactTypeID,
		arg.Name,
		arg.Position,
		arg.Department,
		arg.Ranking,
		arg.Observation,
		arg.PurchaseOrderTag,
	)
	var i SupplierContact
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ContactTypeID,
		&i.Name,
		&i.Position,
		&i.Department,
		&i.Ranking,
		&i.Observation,
		&i.PurchaseOrderTag,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierContactEmail = `-- name: CreateSupplierContactEmail :one
INSERT INTO supplier_contact_emails (contact_id, value, ranking)
VALUES ($1, $2, $3)
RETURNING id, contact_id, value, ranking
`

type CreateSupplierContactEmailParams struct {
	ContactID int64
	Value     string
	Ranking   int32
}

func (q *Queries) CreateSupplierContactEmail(ctx context.Context, arg CreateSupplierContactEmailParams) (SupplierContactEmail, error) {
	row := q.db.QueryRow(ctx, createSupplierContactEmail, arg.ContactID, arg.Value, arg.Ranking)
	var i SupplierContactEmail
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Value,
		&i.Ranking,
	)
	return i, err
}

const createSupplierContactPhone = `-- name: CreateSupplierContactPhone :one
INSERT INTO supplier_contact_phones (contact_id, value, ranking)
VALUES ($1, $2, $3)
RETURNING id, contact_id, value, ranking
`

type CreateSupplierContactPhoneParams struct {
	ContactID int64
	Value     string
	Ranking   int32
}

func (q *Queries) CreateSupplierContactPhone(ctx context.Context, arg CreateSupplierContactPhoneParams) (SupplierContactPhone, error) {
	row := q.db.QueryRow(ctx, createSupplierContactPhone, arg.ContactID, arg.Value, arg.Ranking)
	var i SupplierContactPhone
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Value,
		&i.Ranking,
	)
	return i, err
}

const createSupplierContactType = `-- name: CreateSupplierContactType :one

INSERT INTO supplier_contact_types (code, description)
VALUES ($1, $2)
RETURNING id, code, description, is_active, created_at
`

type CreateSupplierContactTypeParams struct {
	Code        int64
	Description string
}

// ─── Supplier Contact Types ─────────────────────────────────────────────────────
func (q *Queries) CreateSupplierContactType(ctx context.Context, arg CreateSupplierContactTypeParams) (SupplierContactType, error) {
	row := q.db.QueryRow(ctx, createSupplierContactType, arg.Code, arg.Description)
	var i SupplierContactType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierDueDate = `-- name: CreateSupplierDueDate :one

INSERT INTO supplier_due_dates (
    supplier_id, description, ranking, base_date, payment_condition_id,
    payment_type, subsequent_month, rounding, receipt_start_time,
    receipt_end_time, avg_unload_minutes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, supplier_id, description, ranking, base_date, payment_condition_id, payment_type, subsequent_month, rounding, receipt_start_time, receipt_end_time, avg_unload_minutes, created_at
`

type CreateSupplierDueDateParams struct {
	SupplierID         int64
	Description        string
	Ranking            int32
	BaseDate           string
	PaymentConditionID *int64
	PaymentType        string
	SubsequentMonth    bool
	Rounding           string
	ReceiptStartTime   pgtype.Text
	ReceiptEndTime     pgtype.Text
	AvgUnloadMinutes   *int32
}

// ─── Supplier Due Dates ─────────────────────────────────────────────────────────
func (q *Queries) CreateSupplierDueDate(ctx context.Context, arg CreateSupplierDueDateParams) (SupplierDueDate, error) {
	row := q.db.QueryRow(ctx, createSupplierDueDate,
		arg.SupplierID,
		arg.Description,
		arg.Ranking,
		arg.BaseDate,
		arg.PaymentConditionID,
		arg.PaymentType,
		arg.SubsequentMonth,
		arg.Rounding,
		arg.ReceiptStartTime,
		arg.ReceiptEndTime,
		arg.AvgUnloadMinutes,
	)
	var i SupplierDueDate
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Description,
		&i.Ranking,
		&i.BaseDate,
		&i.PaymentConditionID,
		&i.PaymentType,
		&i.SubsequentMonth,
		&i.Rounding,
		&i.ReceiptStartTime,
		&i.ReceiptEndTime,
		&i.AvgUnloadMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierEmail = `-- name: CreateSupplierEmail :one

INSERT INTO supplier_emails (supplier_id, email, ranking)
VALUES ($1, $2, $3)
RETURNING id, supplier_id, email, ranking, is_active, created_at
`

type CreateSupplierEmailParams struct {
	SupplierID int64
	Email      string
	Ranking    int32
}

// ─── Supplier Emails ──────────────────────────────────────────────────────────
func (q *Queries) CreateSupplierEmail(ctx context.Context, arg CreateSupplierEmailParams) (SupplierEmail, error) {
	row := q.db.QueryRow(ctx, createSupplierEmail, arg.SupplierID, arg.Email, arg.Ranking)
	var i SupplierEmail
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Email,
		&i.Ranking,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierEnterprise = `-- name: CreateSupplierEnterprise :one

INSERT INTO supplier_enterprises (
    supplier_id, enterprise_code, financial_account, applies_ipi,
    default_invoice_type_id, purchase_price_table_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, supplier_id, enterprise_code, financial_account, applies_ipi, default_invoice_type_id, purchase_price_table_id, is_active, created_at
`

type CreateSupplierEnterpriseParams struct {
	SupplierID           int64
	EnterpriseCode       int64
	FinancialAccount     pgtype.Text
	AppliesIpi           bool
	DefaultInvoiceTypeID *int64
	PurchasePriceTableID *int64
}

// ─── Supplier Enterprises ─────────────────────────────────────────────────────
func (q *Queries) CreateSupplierEnterprise(ctx context.Context, arg CreateSupplierEnterpriseParams) (SupplierEnterprise, error) {
	row := q.db.QueryRow(ctx, createSupplierEnterprise,
		arg.SupplierID,
		arg.EnterpriseCode,
		arg.FinancialAccount,
		arg.AppliesIpi,
		arg.DefaultInvoiceTypeID,
		arg.PurchasePriceTableID,
	)
	var i SupplierEnterprise
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.EnterpriseCode,
		&i.FinancialAccount,
		&i.AppliesIpi,
		&i.DefaultInvoiceTypeID,
		&i.PurchasePriceTableID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierPhone = `-- name: CreateSupplierPhone :one

INSERT INTO supplier_phones (supplier_id, number, ranking)
VALUES ($1, $2, $3)
RETURNING id, supplier_id, number, ranking, is_active, created_at
`

type CreateSupplierPhoneParams struct {
	SupplierID int64
	Number     string
	Ranking    int32
}

// ─── Supplier Phones ──────────────────────────────────────────────────────────
func (q *Queries) CreateSupplierPhone(ctx context.Context, arg CreateSupplierPhoneParams) (SupplierPhone, error) {
	row := q.db.QueryRow(ctx, createSupplierPhone, arg.SupplierID, arg.Number, arg.Ranking)
	var i SupplierPhone
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Number,
		&i.Ranking,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierType = `-- name: CreateSupplierType :one

INSERT INTO supplier_types (code, description, kind)
VALUES ($1, $2, $3)
RETURNING id, code, description, kind, is_active, created_at
`

type CreateSupplierTypeParams struct {
	Code        int64
	Description string
	Kind        string
}

// ─── Supplier Types ───────────────────────────────────────────────────────────
func (q *Queries) CreateSupplierType(ctx context.Context, arg CreateSupplierTypeParams) (SupplierType, error) {
	row := q.db.QueryRow(ctx, createSupplierType, arg.Code, arg.Description, arg.Kind)
	var i SupplierType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Kind,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers WHERE code = $1
`

// Hard delete. Fails with FK violation when purchase orders reference the
// supplier (the application surfaces a friendly message); inactivate instead.
func (q *Queries) DeleteSupplier(ctx context.Context, code int64) error {
	_, err := q.db.Exec(ctx, deleteSupplier, code)
	return err
}

const deleteSupplierAddress = `-- name: DeleteSupplierAddress :exec
DELETE FROM supplier_addresses WHERE id = $1
`

func (q *Queries) DeleteSupplierAddress(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSupplierAddress, id)
	return err
}

const deleteSupplierContact = `-- name: DeleteSupplierContact :exec
DELETE FROM supplier_contacts WHERE id = $1
`

func (q *Queries) DeleteSupplierContact(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSupplierContact, id)
	return err
}

const deleteSupplierDueDate = `-- name: DeleteSupplierDueDate :exec
DELETE FROM supplier_due_dates WHERE id = $1
`

func (q *Queries) DeleteSupplierDueDate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSupplierDueDate, id)
	return err
}

const deleteSupplierEmail = `-- name: DeleteSupplierEmail :exec
DELETE FROM supplier_emails WHERE id = $1
`

func (q *Queries) DeleteSupplierEmail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSupplierEmail, id)
	return err
}

const deleteSupplierEnterprise = `-- name: DeleteSupplierEnterprise :exec
DELETE FROM supplier_enterprises WHERE id = $1
`

func (q *Queries) DeleteSupplierEnterprise(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSupplierEnterprise, id)
	return err
}

const deleteSupplierPhone = `-- name: DeleteSupplierPhone :exec
DELETE FROM supplier_phones WHERE id = $1
`

func (q *Queries) DeleteSupplierPhone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSupplierPhone, id)
	return err
}

const getSupplierByCode = `-- name: GetSupplierByCode :one
SELECT id, code, corporate_code, is_active, is_representative, is_customer, name, trade_name, person_type, document_type, document_number, state_registration, municipal_registration, supplier_type_id, payment_condition_id, carrier_id, region_id, freight_type, register_date, viticola_obligation, gln_code, agriculture_ministry_registration, icms_contributor, is_mei, tracking_platform, homologated, last_sefaz_query, billing_receipt_status, last_sefaz_update, sefaz_update_user, blocked, block_reason, created_at, created_by, updated_at FROM suppliers WHERE code = $1
`

func (q *Queries) GetSupplierByCode(ctx context.Context, code int64) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByCode, code)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CorporateCode,
		&i.IsActive,
		&i.IsRepresentative,
		&i.IsCustomer,
		&i.Name,
		&i.TradeName,
		&i.PersonType,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.StateRegistration,
		&i.MunicipalRegistration,
		&i.SupplierTypeID,
		&i.PaymentConditionID,
		&i.CarrierID,
		&i.RegionID,
		&i.FreightType,
		&i.RegisterDate,
		&i.ViticolaObligation,
		&i.GlnCode,
		&i.AgricultureMinistryRegistration,
		&i.IcmsContributor,
		&i.IsMei,
		&i.TrackingPlatform,
		&i.Homologated,
		&i.LastSefazQuery,
		&i.BillingReceiptStatus,
		&i.LastSefazUpdate,
		&i.SefazUpdateUser,
		&i.Blocked,
		&i.BlockReason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByDocument = `-- name: GetSupplierByDocument :one
SELECT id, code, corporate_code, is_active, is_representative, is_customer, name, trade_name, person_type, document_type, document_number, state_registration, municipal_registration, supplier_type_id, payment_condition_id, carrier_id, region_id, freight_type, register_date, viticola_obligation, gln_code, agriculture_ministry_registration, icms_contributor, is_mei, tracking_platform, homologated, last_sefaz_query, billing_receipt_status, last_sefaz_update, sefaz_update_user, blocked, block_reason, created_at, created_by, updated_at FROM suppliers WHERE document_number = $1 LIMIT 1
`

func (q *Queries) GetSupplierByDocument(ctx context.Context, documentNumber string) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByDocument, documentNumber)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CorporateCode,
		&i.IsActive,
		&i.IsRepresentative,
		&i.IsCustomer,
		&i.Name,
		&i.TradeName,
		&i.PersonType,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.StateRegistration,
		&i.MunicipalRegistration,
		&i.SupplierTypeID,
		&i.PaymentConditionID,
		&i.CarrierID,
		&i.RegionID,
		&i.FreightType,
		&i.RegisterDate,
		&i.ViticolaObligation,
		&i.GlnCode,
		&i.AgricultureMinistryRegistration,
		&i.IcmsContributor,
		&i.IsMei,
		&i.TrackingPlatform,
		&i.Homologated,
		&i.LastSefazQuery,
		&i.BillingReceiptStatus,
		&i.LastSefazUpdate,
		&i.SefazUpdateUser,
		&i.Blocked,
		&i.BlockReason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierContactTypeByCode = `-- name: GetSupplierContactTypeByCode :one
SELECT id, code, description, is_active, created_at FROM supplier_contact_types WHERE code = $1
`

func (q *Queries) GetSupplierContactTypeByCode(ctx context.Context, code int64) (SupplierContactType, error) {
	row := q.db.QueryRow(ctx, getSupplierContactTypeByCode, code)
	var i SupplierContactType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierParameters = `-- name: GetSupplierParameters :one

SELECT id, enterprise_code, default_financial_account, unique_item_code_per_supplier, requires_financial_account, purchase_supplier_type_id, copy_obs_to_purchase_order, copy_obs_to_entry_invoice, homologation_default, use_stock_uom, generic_supplier_code, default_due_base_date, created_at, updated_at FROM supplier_parameters WHERE enterprise_code = $1
`

// ─── Supplier Parameters ────────────────────────────────────────────────────────
func (q *Queries) GetSupplierParameters(ctx context.Context, enterpriseCode int64) (SupplierParameter, error) {
	row := q.db.QueryRow(ctx, getSupplierParameters, enterpriseCode)
	var i SupplierParameter
	err := row.Scan(
		&i.ID,
		&i.EnterpriseCode,
		&i.DefaultFinancialAccount,
		&i.UniqueItemCodePerSupplier,
		&i.RequiresFinancialAccount,
		&i.PurchaseSupplierTypeID,
		&i.CopyObsToPurchaseOrder,
		&i.CopyObsToEntryInvoice,
		&i.HomologationDefault,
		&i.UseStockUom,
		&i.GenericSupplierCode,
		&i.DefaultDueBaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierTypeByCode = `-- name: GetSupplierTypeByCode :one
SELECT id, code, description, kind, is_active, created_at FROM supplier_types WHERE code = $1
`

func (q *Queries) GetSupplierTypeByCode(ctx context.Context, code int64) (SupplierType, error) {
	row := q.db.QueryRow(ctx, getSupplierTypeByCode, code)
	var i SupplierType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Kind,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listSupplierAddresses = `-- name: ListSupplierAddresses :many
SELECT id, supplier_id, address_type, zip_code, street, number, complement, neighborhood, city, uf, country, is_default, created_at FROM supplier_addresses WHERE supplier_id = $1 ORDER BY id
`

func (q *Queries) ListSupplierAddresses(ctx context.Context, supplierID int64) ([]SupplierAddress, error) {
	rows, err := q.db.Query(ctx, listSupplierAddresses, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierAddress
	for rows.Next() {
		var i SupplierAddress
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.AddressType,
			&i.ZipCode,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.Neighborhood,
			&i.City,
			&i.Uf,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierContactEmails = `-- name: ListSupplierContactEmails :many
SELECT id, contact_id, value, ranking FROM supplier_contact_emails WHERE contact_id = $1 ORDER BY ranking, id
`

func (q *Queries) ListSupplierContactEmails(ctx context.Context, contactID int64) ([]SupplierContactEmail, error) {
	rows, err := q.db.Query(ctx, listSupplierContactEmails, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierContactEmail
	for rows.Next() {
		var i SupplierContactEmail
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Value,
			&i.Ranking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierContactPhones = `-- name: ListSupplierContactPhones :many
SELECT id, contact_id, value, ranking FROM supplier_contact_phones WHERE contact_id = $1 ORDER BY ranking, id
`

func (q *Queries) ListSupplierContactPhones(ctx context.Context, contactID int64) ([]SupplierContactPhone, error) {
	rows, err := q.db.Query(ctx, listSupplierContactPhones, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierContactPhone
	for rows.Next() {
		var i SupplierContactPhone
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Value,
			&i.Ranking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierContactTypes = `-- name: ListSupplierContactTypes :many
SELECT id, code, description, is_active, created_at FROM supplier_contact_types
WHERE ($1::BOOLEAN = FALSE OR is_active = TRUE)
ORDER BY code
`

func (q *Queries) ListSupplierContactTypes(ctx context.Context, dollar_1 bool) ([]SupplierContactType, error) {
	rows, err := q.db.Query(ctx, listSupplierContactTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierContactType
	for rows.Next() {
		var i SupplierContactType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierContacts = `-- name: ListSupplierContacts :many
SELECT id, supplier_id, contact_type_id, name, position, department, ranking, observation, purchase_order_tag, is_active, created_at FROM supplier_contacts WHERE supplier_id = $1 ORDER BY ranking, id
`

func (q *Queries) ListSupplierContacts(ctx context.Context, supplierID int64) ([]SupplierContact, error) {
	rows, err := q.db.Query(ctx, listSupplierContacts, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierContact
	for rows.Next() {
		var i SupplierContact
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.ContactTypeID,
			&i.Name,
			&i.Position,
			&i.Department,
			&i.Ranking,
			&i.Observation,
			&i.PurchaseOrderTag,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierDueDates = `-- name: ListSupplierDueDates :many
SELECT id, supplier_id, description, ranking, base_date, payment_condition_id, payment_type, subsequent_month, rounding, receipt_start_time, receipt_end_time, avg_unload_minutes, created_at FROM supplier_due_dates WHERE supplier_id = $1 ORDER BY ranking, id
`

func (q *Queries) ListSupplierDueDates(ctx context.Context, supplierID int64) ([]SupplierDueDate, error) {
	rows, err := q.db.Query(ctx, listSupplierDueDates, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierDueDate
	for rows.Next() {
		var i SupplierDueDate
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Description,
			&i.Ranking,
			&i.BaseDate,
			&i.PaymentConditionID,
			&i.PaymentType,
			&i.SubsequentMonth,
			&i.Rounding,
			&i.ReceiptStartTime,
			&i.ReceiptEndTime,
			&i.AvgUnloadMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierEmails = `-- name: ListSupplierEmails :many
SELECT id, supplier_id, email, ranking, is_active, created_at FROM supplier_emails WHERE supplier_id = $1 ORDER BY ranking, id
`

func (q *Queries) ListSupplierEmails(ctx context.Context, supplierID int64) ([]SupplierEmail, error) {
	rows, err := q.db.Query(ctx, listSupplierEmails, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierEmail
	for rows.Next() {
		var i SupplierEmail
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Email,
			&i.Ranking,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierEnterprises = `-- name: ListSupplierEnterprises :many
SELECT id, supplier_id, enterprise_code, financial_account, applies_ipi, default_invoice_type_id, purchase_price_table_id, is_active, created_at FROM supplier_enterprises WHERE supplier_id = $1 ORDER BY enterprise_code
`

func (q *Queries) ListSupplierEnterprises(ctx context.Context, supplierID int64) ([]SupplierEnterprise, error) {
	rows, err := q.db.Query(ctx, listSupplierEnterprises, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierEnterprise
	for rows.Next() {
		var i SupplierEnterprise
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.EnterpriseCode,
			&i.FinancialAccount,
			&i.AppliesIpi,
			&i.DefaultInvoiceTypeID,
			&i.PurchasePriceTableID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierEstablishments = `-- name: ListSupplierEstablishments :many
SELECT id, code, corporate_code, is_active, is_representative, is_customer, name, trade_name, person_type, document_type, document_number, state_registration, municipal_registration, supplier_type_id, payment_condition_id, carrier_id, region_id, freight_type, register_date, viticola_obligation, gln_code, agriculture_ministry_registration, icms_contributor, is_mei, tracking_platform, homologated, last_sefaz_query, billing_receipt_status, last_sefaz_update, sefaz_update_user, blocked, block_reason, created_at, created_by, updated_at FROM suppliers WHERE corporate_code = $1 ORDER BY code
`

func (q *Queries) ListSupplierEstablishments(ctx context.Context, corporateCode *int64) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSupplierEstablishments, corporateCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CorporateCode,
			&i.IsActive,
			&i.IsRepresentative,
			&i.IsCustomer,
			&i.Name,
			&i.TradeName,
			&i.PersonType,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.StateRegistration,
			&i.MunicipalRegistration,
			&i.SupplierTypeID,
			&i.PaymentConditionID,
			&i.CarrierID,
			&i.RegionID,
			&i.FreightType,
			&i.RegisterDate,
			&i.ViticolaObligation,
			&i.GlnCode,
			&i.AgricultureMinistryRegistration,
			&i.IcmsContributor,
			&i.IsMei,
			&i.TrackingPlatform,
			&i.Homologated,
			&i.LastSefazQuery,
			&i.BillingReceiptStatus,
			&i.LastSefazUpdate,
			&i.SefazUpdateUser,
			&i.Blocked,
			&i.BlockReason,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierPhones = `-- name: ListSupplierPhones :many
SELECT id, supplier_id, number, ranking, is_active, created_at FROM supplier_phones WHERE supplier_id = $1 ORDER BY ranking, id
`

func (q *Queries) ListSupplierPhones(ctx context.Context, supplierID int64) ([]SupplierPhone, error) {
	rows, err := q.db.Query(ctx, listSupplierPhones, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierPhone
	for rows.Next() {
		var i SupplierPhone
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Number,
			&i.Ranking,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierTypes = `-- name: ListSupplierTypes :many
SELECT id, code, description, kind, is_active, created_at FROM supplier_types
WHERE ($1::BOOLEAN = FALSE OR is_active = TRUE)
ORDER BY code
`

func (q *Queries) ListSupplierTypes(ctx context.Context, dollar_1 bool) ([]SupplierType, error) {
	rows, err := q.db.Query(ctx, listSupplierTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierType
	for rows.Next() {
		var i SupplierType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Kind,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, code, corporate_code, is_active, is_representative, is_customer, name, trade_name, person_type, document_type, document_number, state_registration, municipal_registration, supplier_type_id, payment_condition_id, carrier_id, region_id, freight_type, register_date, viticola_obligation, gln_code, agriculture_ministry_registration, icms_contributor, is_mei, tracking_platform, homologated, last_sefaz_query, billing_receipt_status, last_sefaz_update, sefaz_update_user, blocked, block_reason, created_at, created_by, updated_at FROM suppliers
WHERE ($1::BOOLEAN = FALSE OR is_active = TRUE)
ORDER BY code
`

func (q *Queries) ListSuppliers(ctx context.Context, dollar_1 bool) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CorporateCode,
			&i.IsActive,
			&i.IsRepresentative,
			&i.IsCustomer,
			&i.Name,
			&i.TradeName,
			&i.PersonType,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.StateRegistration,
			&i.MunicipalRegistration,
			&i.SupplierTypeID,
			&i.PaymentConditionID,
			&i.CarrierID,
			&i.RegionID,
			&i.FreightType,
			&i.RegisterDate,
			&i.ViticolaObligation,
			&i.GlnCode,
			&i.AgricultureMinistryRegistration,
			&i.IcmsContributor,
			&i.IsMei,
			&i.TrackingPlatform,
			&i.Homologated,
			&i.LastSefazQuery,
			&i.BillingReceiptStatus,
			&i.LastSefazUpdate,
			&i.SefazUpdateUser,
			&i.Blocked,
			&i.BlockReason,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSupplierCode = `-- name: NextSupplierCode :one
SELECT COALESCE(MAX(code), 0) + 1 AS next_code FROM suppliers
`

func (q *Queries) NextSupplierCode(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextSupplierCode)
	var next_code int32
	err := row.Scan(&next_code)
	return next_code, err
}

const nextSupplierContactTypeCode = `-- name: NextSupplierContactTypeCode :one
SELECT COALESCE(MAX(code), 0) + 1 AS next_code FROM supplier_contact_types
`

func (q *Queries) NextSupplierContactTypeCode(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextSupplierContactTypeCode)
	var next_code int32
	err := row.Scan(&next_code)
	return next_code, err
}

const nextSupplierTypeCode = `-- name: NextSupplierTypeCode :one
SELECT COALESCE(MAX(code), 0) + 1 AS next_code FROM supplier_types
`

func (q *Queries) NextSupplierTypeCode(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextSupplierTypeCode)
	var next_code int32
	err := row.Scan(&next_code)
	return next_code, err
}

const propagateStateRegistration = `-- name: PropagateStateRegistration :exec
UPDATE suppliers
SET state_registration = $2, updated_at = NOW()
WHERE document_number = $1 AND code <> $3
`

type PropagateStateRegistrationParams struct {
	DocumentNumber    string
	StateRegistration pgtype.Text
	Code              int64
}

// Spec: ao alterar a IE, atualiza outros cadastros com o mesmo CNPJ/CPF.
func (q *Queries) PropagateStateRegistration(ctx context.Context, arg PropagateStateRegistrationParams) error {
	_, err := q.db.Exec(ctx, propagateStateRegistration, arg.DocumentNumber, arg.StateRegistration, arg.Code)
	return err
}

const unblockSupplier = `-- name: UnblockSupplier :exec
UPDATE suppliers SET blocked = FALSE, block_reason = NULL, updated_at = NOW() WHERE code = $1
`

func (q *Queries) UnblockSupplier(ctx context.Context, code int64) error {
	_, err := q.db.Exec(ctx, unblockSupplier, code)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET corporate_code = $2, is_active = $3, is_representative = $4, is_customer = $5,
    name = $6, trade_name = $7, person_type = $8, document_type = $9, document_number = $10,
    state_registration = $11, municipal_registration = $12, supplier_type_id = $13,
    payment_condition_id = $14, carrier_id = $15, region_id = $16, freight_type = $17,
    viticola_obligation = $18, gln_code = $19, agriculture_ministry_registration = $20,
    icms_contributor = $21, is_mei = $22, tracking_platform = $23, homologated = $24,
    updated_at = NOW()
WHERE code = $1
RETURNING id, code, corporate_code, is_active, is_representative, is_customer, name, trade_name, person_type, document_type, document_number, state_registration, municipal_registration, supplier_type_id, payment_condition_id, carrier_id, region_id, freight_type, register_date, viticola_obligation, gln_code, agriculture_ministry_registration, icms_contributor, is_mei, tracking_platform, homologated, last_sefaz_query, billing_receipt_status, last_sefaz_update, sefaz_update_user, blocked, block_reason, created_at, created_by, updated_at
`

type UpdateSupplierParams struct {
	Code                            int64
	CorporateCode                   *int64
	IsActive                        bool
	IsRepresentative                bool
	IsCustomer                      bool
	Name                            string
	TradeName                       pgtype.Text
	PersonType                      string
	DocumentType                    string
	DocumentNumber                  string
	StateRegistration               pgtype.Text
	MunicipalRegistration           pgtype.Text
	SupplierTypeID                  *int64
	PaymentConditionID              *int64
	CarrierID                       *int64
	RegionID                        *int64
	FreightType                     string
	ViticolaObligation              string
	GlnCode                         pgtype.Text
	AgricultureMinistryRegistration pgtype.Text
	IcmsContributor                 string
	IsMei                           bool
	TrackingPlatform                string
	Homologated                     bool
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Code,
		arg.CorporateCode,
		arg.IsActive,
		arg.IsRepresentative,
		arg.IsCustomer,
		arg.Name,
		arg.TradeName,
		arg.PersonType,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.StateRegistration,
		arg.MunicipalRegistration,
		arg.SupplierTypeID,
		arg.PaymentConditionID,
		arg.CarrierID,
		arg.RegionID,
		arg.FreightType,
		arg.ViticolaObligation,
		arg.GlnCode,
		arg.AgricultureMinistryRegistration,
		arg.IcmsContributor,
		arg.IsMei,
		arg.TrackingPlatform,
		arg.Homologated,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CorporateCode,
		&i.IsActive,
		&i.IsRepresentative,
		&i.IsCustomer,
		&i.Name,
		&i.TradeName,
		&i.PersonType,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.StateRegistration,
		&i.MunicipalRegistration,
		&i.SupplierTypeID,
		&i.PaymentConditionID,
		&i.CarrierID,
		&i.RegionID,
		&i.FreightType,
		&i.RegisterDate,
		&i.ViticolaObligation,
		&i.GlnCode,
		&i.AgricultureMinistryRegistration,
		&i.IcmsContributor,
		&i.IsMei,
		&i.TrackingPlatform,
		&i.Homologated,
		&i.LastSefazQuery,
		&i.BillingReceiptStatus,
		&i.LastSefazUpdate,
		&i.SefazUpdateUser,
		&i.Blocked,
		&i.BlockReason,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSupplierAddress = `-- name: UpdateSupplierAddress :one
UPDATE supplier_addresses
SET address_type = $2, zip_code = $3, street = $4, number = $5, complement = $6,
    neighborhood = $7, city = $8, uf = $9, country = $10, is_default = $11
WHERE id = $1
RETURNING id, supplier_id, address_type, zip_code, street, number, complement, neighborhood, city, uf, country, is_default, created_at
`

type UpdateSupplierAddressParams struct {
	ID           int64
	AddressType  string
	ZipCode      pgtype.Text
	Street       pgtype.Text
	Number       pgtype.Text
	Complement   pgtype.Text
	Neighborhood pgtype.Text
	City         pgtype.Text
	Uf           pgtype.Text
	Country      string
	IsDefault    bool
}

func (q *Queries) UpdateSupplierAddress(ctx context.Context, arg UpdateSupplierAddressParams) (SupplierAddress, error) {
	row := q.db.QueryRow(ctx, updateSupplierAddress,
		arg.ID,
		arg.AddressType,
		arg.ZipCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.Neighborhood,
		arg.City,
		arg.Uf,
		arg.Country,
		arg.IsDefault,
	)
	var i SupplierAddress
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.AddressType,
		&i.ZipCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.Uf,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateSupplierContactType = `-- name: UpdateSupplierContactType :one
UPDATE supplier_contact_types
SET description = $2, is_active = $3
WHERE code = $1
RETURNING id, code, description, is_active, created_at
`

type UpdateSupplierContactTypeParams struct {
	Code        int64
	Description string
	IsActive    bool
}

func (q *Queries) UpdateSupplierContactType(ctx context.Context, arg UpdateSupplierContactTypeParams) (SupplierContactType, error) {
	row := q.db.QueryRow(ctx, updateSupplierContactType, arg.Code, arg.Description, arg.IsActive)
	var i SupplierContactType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateSupplierEnterprise = `-- name: UpdateSupplierEnterprise :one
UPDATE supplier_enterprises
SET financial_account = $2, applies_ipi = $3, default_invoice_type_id = $4,
    purchase_price_table_id = $5, is_active = $6
WHERE id = $1
RETURNING id, supplier_id, enterprise_code, financial_account, applies_ipi, default_invoice_type_id, purchase_price_table_id, is_active, created_at
`

type UpdateSupplierEnterpriseParams struct {
	ID                   int64
	FinancialAccount     pgtype.Text
	AppliesIpi           bool
	DefaultInvoiceTypeID *int64
	PurchasePriceTableID *int64
	IsActive             bool
}

func (q *Queries) UpdateSupplierEnterprise(ctx context.Context, arg UpdateSupplierEnterpriseParams) (SupplierEnterprise, error) {
	row := q.db.QueryRow(ctx, updateSupplierEnterprise,
		arg.ID,
		arg.FinancialAccount,
		arg.AppliesIpi,
		arg.DefaultInvoiceTypeID,
		arg.PurchasePriceTableID,
		arg.IsActive,
	)
	var i SupplierEnterprise
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.EnterpriseCode,
		&i.FinancialAccount,
		&i.AppliesIpi,
		&i.DefaultInvoiceTypeID,
		&i.PurchasePriceTableID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateSupplierSefaz = `-- name: UpdateSupplierSefaz :exec
UPDATE suppliers
SET last_sefaz_query = $2, billing_receipt_status = $3,
    last_sefaz_update = $4, sefaz_update_user = $5, updated_at = NOW()
WHERE code = $1
`

type UpdateSupplierSefazParams struct {
	Code                 int64
	LastSefazQuery       pgtype.Date
	BillingReceiptStatus pgtype.Text
	LastSefazUpdate      pgtype.Date
	SefazUpdateUser      pgtype.Text
}

func (q *Queries) UpdateSupplierSefaz(ctx context.Context, arg UpdateSupplierSefazParams) error {
	_, err := q.db.Exec(ctx, updateSupplierSefaz,
		arg.Code,
		arg.LastSefazQuery,
		arg.BillingReceiptStatus,
		arg.LastSefazUpdate,
		arg.SefazUpdateUser,
	)
	return err
}

const updateSupplierType = `-- name: UpdateSupplierType :one
UPDATE supplier_types
SET description = $2, kind = $3, is_active = $4
WHERE code = $1
RETURNING id, code, description, kind, is_active, created_at
`

type UpdateSupplierTypeParams struct {
	Code        int64
	Description string
	Kind        string
	IsActive    bool
}

func (q *Queries) UpdateSupplierType(ctx context.Context, arg UpdateSupplierTypeParams) (SupplierType, error) {
	row := q.db.QueryRow(ctx, updateSupplierType,
		arg.Code,
		arg.Description,
		arg.Kind,
		arg.IsActive,
	)
	var i SupplierType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Kind,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSupplierParameters = `-- name: UpsertSupplierParameters :one
INSERT INTO supplier_parameters (
    enterprise_code, default_financial_account, unique_item_code_per_supplier,
    requires_financial_account, purchase_supplier_type_id, copy_obs_to_purchase_order,
    copy_obs_to_entry_invoice, homologation_default, use_stock_uom,
    generic_supplier_code, default_due_base_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (enterprise_code) DO UPDATE SET
    default_financial_account = EXCLUDED.default_financial_account,
    unique_item_code_per_supplier = EXCLUDED.unique_item_code_per_supplier,
    requires_financial_account = EXCLUDED.requires_financial_account,
    purchase_supplier_type_id = EXCLUDED.purchase_supplier_type_id,
    copy_obs_to_purchase_order = EXCLUDED.copy_obs_to_purchase_order,
    copy_obs_to_entry_invoice = EXCLUDED.copy_obs_to_entry_invoice,
    homologation_default = EXCLUDED.homologation_default,
    use_stock_uom = EXCLUDED.use_stock_uom,
    generic_supplier_code = EXCLUDED.generic_supplier_code,
    default_due_base_date = EXCLUDED.default_due_base_date,
    updated_at = NOW()
RETURNING id, enterprise_code, default_financial_account, unique_item_code_per_supplier, requires_financial_account, purchase_supplier_type_id, copy_obs_to_purchase_order, copy_obs_to_entry_invoice, homologation_default, use_stock_uom, generic_supplier_code, default_due_base_date, created_at, updated_at
`

type UpsertSupplierParametersParams struct {
	EnterpriseCode            int64
	DefaultFinancialAccount   pgtype.Text
	UniqueItemCodePerSupplier bool
	RequiresFinancialAccount  bool
	PurchaseSupplierTypeID    *int64
	CopyObsToPurchaseOrder    bool
	CopyObsToEntryInvoice     bool
	HomologationDefault       bool
	UseStockUom               bool
	GenericSupplierCode       *int64
	DefaultDueBaseDate        string
}

func (q *Queries) UpsertSupplierParameters(ctx context.Context, arg UpsertSupplierParametersParams) (SupplierParameter, error) {
	row := q.db.QueryRow(ctx, upsertSupplierParameters,
		arg.EnterpriseCode,
		arg.DefaultFinancialAccount,
		arg.UniqueItemCodePerSupplier,
		arg.RequiresFinancialAccount,
		arg.PurchaseSupplierTypeID,
		arg.CopyObsToPurchaseOrder,
		arg.CopyObsToEntryInvoice,
		arg.HomologationDefault,
		arg.UseStockUom,
		arg.GenericSupplierCode,
		arg.DefaultDueBaseDate,
	)
	var i SupplierParameter
	err := row.Scan(
		&i.ID,
		&i.EnterpriseCode,
		&i.DefaultFinancialAccount,
		&i.UniqueItemCodePerSupplier,
		&i.RequiresFinancialAccount,
		&i.PurchaseSupplierTypeID,
		&i.CopyObsToPurchaseOrder,
		&i.CopyObsToEntryInvoice,
		&i.HomologationDefault,
		&i.UseStockUom,
		&i.GenericSupplierCode,
		&i.DefaultDueBaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
