// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouse.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouse (
    code,
    description,
    location,
    type,
    disposition,
    reservations_allowed,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING
    code,
    description,
    location,
    type,
    disposition,
    reservations_allowed,
    created_by,
    created_at
`

type CreateWarehouseParams struct {
	Code                int
	Description         string
	Location            WarehouseLocation
	Type                WarehouseType
	Disposition         bool
	ReservationsAllowed bool
	CreatedBy           uuid.UUID
}

type CreateWarehouseRow struct {
	Code                int
	Description         string
	Location            WarehouseLocation
	Type                WarehouseType
	Disposition         bool
	ReservationsAllowed bool
	CreatedBy           uuid.UUID
	CreatedAt           time.Time
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (CreateWarehouseRow, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.Code,
		arg.Description,
		arg.Location,
		arg.Type,
		arg.Disposition,
		arg.ReservationsAllowed,
		arg.CreatedBy,
	)
	var i CreateWarehouseRow
	err := row.Scan(
		&i.Code,
		&i.Description,
		&i.Location,
		&i.Type,
		&i.Disposition,
		&i.ReservationsAllowed,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}